// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Access: BidKingRawTableRow[] = [
  {
    "id": "1001",
    "table": "Access",
    "columns": [
      "1001",
      "text_Access_1001_1",
      "",
      "0",
      "0",
      "access_desc_1001"
    ],
    "packaged_name": "功能入口1001",
    "packaged_desc": "功能入口配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002",
    "table": "Access",
    "columns": [
      "1002",
      "text_Access_1002_1",
      "",
      "1",
      "0",
      "access_desc_1002"
    ],
    "packaged_name": "功能入口1002",
    "packaged_desc": "功能入口配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003",
    "table": "Access",
    "columns": [
      "1003",
      "text_Access_1003_1",
      "",
      "2",
      "2",
      "access_desc_1003"
    ],
    "packaged_name": "功能入口1003",
    "packaged_desc": "功能入口配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1004",
    "table": "Access",
    "columns": [
      "1004",
      "text_Access_1004_1",
      "",
      "2",
      "5",
      "access_desc_1004"
    ],
    "packaged_name": "功能入口1004",
    "packaged_desc": "功能入口配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1005",
    "table": "Access",
    "columns": [
      "1005",
      "text_Access_1005_1",
      "",
      "2",
      "1",
      "access_desc_1005"
    ],
    "packaged_name": "功能入口1005",
    "packaged_desc": "功能入口配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1006",
    "table": "Access",
    "columns": [
      "1006",
      "text_Access_1006_1",
      "",
      "0",
      "0",
      "access_desc_1006"
    ],
    "packaged_name": "功能入口1006",
    "packaged_desc": "功能入口配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1007",
    "table": "Access",
    "columns": [
      "1007",
      "text_Access_1007_1",
      "",
      "2",
      "5",
      "access_desc_1007"
    ],
    "packaged_name": "功能入口1007",
    "packaged_desc": "功能入口配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1008",
    "table": "Access",
    "columns": [
      "1008",
      "text_Access_1008_1",
      "",
      "2",
      "5",
      "access_desc_1008"
    ],
    "packaged_name": "功能入口1008",
    "packaged_desc": "功能入口配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1009",
    "table": "Access",
    "columns": [
      "1009",
      "text_Access_1009_1",
      "",
      "2",
      "5",
      "access_desc_1009"
    ],
    "packaged_name": "功能入口1009",
    "packaged_desc": "功能入口配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
