// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Achievement: BidKingRawTableRow[] = [
  {
    "id": "1001101",
    "table": "Achievement",
    "columns": [
      "1001101",
      "text_Achievement_1001101_1",
      "",
      "1001",
      "101",
      "[5101001,5101002,5101003,5101004]",
      "achievement_tipsname_1001"
    ],
    "packaged_name": "成就1001101",
    "packaged_desc": "成就配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002201",
    "table": "Achievement",
    "columns": [
      "1002201",
      "text_Achievement_1002201_1",
      "",
      "1002",
      "201",
      "[5201001,5201002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002201",
    "packaged_desc": "成就配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002202",
    "table": "Achievement",
    "columns": [
      "1002202",
      "text_Achievement_1002202_1",
      "",
      "1002",
      "202",
      "[5202001,5202002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002202",
    "packaged_desc": "成就配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002203",
    "table": "Achievement",
    "columns": [
      "1002203",
      "text_Achievement_1002203_1",
      "",
      "1002",
      "203",
      "[5203001,5203002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002203",
    "packaged_desc": "成就配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002204",
    "table": "Achievement",
    "columns": [
      "1002204",
      "text_Achievement_1002204_1",
      "",
      "1002",
      "204",
      "[5204001,5204002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002204",
    "packaged_desc": "成就配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002205",
    "table": "Achievement",
    "columns": [
      "1002205",
      "text_Achievement_1002205_1",
      "",
      "1002",
      "205",
      "[5205001,5205002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002205",
    "packaged_desc": "成就配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002206",
    "table": "Achievement",
    "columns": [
      "1002206",
      "text_Achievement_1002206_1",
      "",
      "1002",
      "206",
      "[5206001,5206002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002206",
    "packaged_desc": "成就配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002207",
    "table": "Achievement",
    "columns": [
      "1002207",
      "text_Achievement_1002207_1",
      "",
      "1002",
      "207",
      "[5207001,5207002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002207",
    "packaged_desc": "成就配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002208",
    "table": "Achievement",
    "columns": [
      "1002208",
      "text_Achievement_1002208_1",
      "",
      "1002",
      "208",
      "[5208001,5208002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002208",
    "packaged_desc": "成就配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002209",
    "table": "Achievement",
    "columns": [
      "1002209",
      "text_Achievement_1002209_1",
      "",
      "1002",
      "209",
      "[5209001,5209002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002209",
    "packaged_desc": "成就配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002210",
    "table": "Achievement",
    "columns": [
      "1002210",
      "text_Achievement_1002210_1",
      "",
      "1002",
      "210",
      "[5210001,5210002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002210",
    "packaged_desc": "成就配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002211",
    "table": "Achievement",
    "columns": [
      "1002211",
      "text_Achievement_1002211_1",
      "",
      "1002",
      "211",
      "[5211001,5211002]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002211",
    "packaged_desc": "成就配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002212",
    "table": "Achievement",
    "columns": [
      "1002212",
      "text_Achievement_1002212_1",
      "",
      "1002",
      "212",
      "[5212001,5212002,5212003,5212004]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002212",
    "packaged_desc": "成就配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002213",
    "table": "Achievement",
    "columns": [
      "1002213",
      "text_Achievement_1002213_1",
      "",
      "1002",
      "213",
      "[5213001,5213002,5213003,5213004]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002213",
    "packaged_desc": "成就配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002214",
    "table": "Achievement",
    "columns": [
      "1002214",
      "text_Achievement_1002214_1",
      "",
      "1002",
      "214",
      "[5214001,5214002,5214003,5214004]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002214",
    "packaged_desc": "成就配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002215",
    "table": "Achievement",
    "columns": [
      "1002215",
      "text_Achievement_1002215_1",
      "",
      "1002",
      "215",
      "[5215001,5215002,5215003,5215004]",
      "achievement_tipsname_1002"
    ],
    "packaged_name": "成就1002215",
    "packaged_desc": "成就配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003301",
    "table": "Achievement",
    "columns": [
      "1003301",
      "text_Achievement_1003301_1",
      "",
      "1003",
      "301",
      "[5301001,5301002,5301003,5301004]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003301",
    "packaged_desc": "成就配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003302",
    "table": "Achievement",
    "columns": [
      "1003302",
      "text_Achievement_1003302_1",
      "",
      "1003",
      "302",
      "[5304001]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003302",
    "packaged_desc": "成就配置行 18，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003303",
    "table": "Achievement",
    "columns": [
      "1003303",
      "text_Achievement_1003303_1",
      "",
      "1003",
      "303",
      "[5305001]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003303",
    "packaged_desc": "成就配置行 19，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003304",
    "table": "Achievement",
    "columns": [
      "1003304",
      "text_Achievement_1003304_1",
      "",
      "1003",
      "304",
      "[5306001]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003304",
    "packaged_desc": "成就配置行 20，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003305",
    "table": "Achievement",
    "columns": [
      "1003305",
      "text_Achievement_1003305_1",
      "",
      "1003",
      "305",
      "[5307001]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003305",
    "packaged_desc": "成就配置行 21，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003306",
    "table": "Achievement",
    "columns": [
      "1003306",
      "text_Achievement_1003306_1",
      "",
      "1003",
      "306",
      "[5308001]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003306",
    "packaged_desc": "成就配置行 22，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003307",
    "table": "Achievement",
    "columns": [
      "1003307",
      "text_Achievement_1003307_1",
      "",
      "1003",
      "307",
      "[5310001,5310002,5310003,5310004]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003307",
    "packaged_desc": "成就配置行 23，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003308",
    "table": "Achievement",
    "columns": [
      "1003308",
      "text_Achievement_1003308_1",
      "",
      "1003",
      "308",
      "[5311001,5311002,5311003,5311004]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003308",
    "packaged_desc": "成就配置行 24，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003309",
    "table": "Achievement",
    "columns": [
      "1003309",
      "text_Achievement_1003309_1",
      "",
      "1003",
      "309",
      "[5313001,5313002]",
      "achievement_tipsname_1003"
    ],
    "packaged_name": "成就1003309",
    "packaged_desc": "成就配置行 25，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
