// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Activity: BidKingRawTableRow[] = [
  {
    "id": "10001",
    "table": "Activity",
    "columns": [
      "10001",
      "",
      "1",
      "1",
      "activity_name_10001",
      "activity_des_10001",
      "1",
      "1",
      "banner_10001",
      "",
      "",
      "86400",
      "[301,4]",
      ""
    ],
    "packaged_name": "活动10001",
    "packaged_desc": "活动配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "10002",
    "table": "Activity",
    "columns": [
      "10002",
      "",
      "2",
      "2",
      "activity_name_10002",
      "activity_des_10002",
      "2",
      "2",
      "banner_10002",
      "ActivityPanel_Rank",
      "background_10002",
      "",
      "",
      "page_10002"
    ],
    "packaged_name": "活动10002",
    "packaged_desc": "活动配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "10003",
    "table": "Activity",
    "columns": [
      "10003",
      "",
      "3",
      "99",
      "activity_name_10003",
      "activity_des_10003",
      "2",
      "2",
      "banner_10003",
      "ActivityPanel_Social",
      "background_10003",
      "",
      "",
      "page_10003"
    ],
    "packaged_name": "活动10003",
    "packaged_desc": "活动配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
