// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Area: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "Area",
    "columns": [
      "1",
      "text_Area_1_1",
      "",
      "area_name_1"
    ],
    "packaged_name": "地区1",
    "packaged_desc": "地区配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "Area",
    "columns": [
      "2",
      "text_Area_2_1",
      "",
      "area_name_2"
    ],
    "packaged_name": "地区2",
    "packaged_desc": "地区配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "Area",
    "columns": [
      "3",
      "text_Area_3_1",
      "",
      "area_name_3"
    ],
    "packaged_name": "地区3",
    "packaged_desc": "地区配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "Area",
    "columns": [
      "4",
      "text_Area_4_1",
      "",
      "area_name_4"
    ],
    "packaged_name": "地区4",
    "packaged_desc": "地区配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "Area",
    "columns": [
      "5",
      "text_Area_5_1",
      "",
      "area_name_5"
    ],
    "packaged_name": "地区5",
    "packaged_desc": "地区配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "Area",
    "columns": [
      "6",
      "text_Area_6_1",
      "",
      "area_name_6"
    ],
    "packaged_name": "地区6",
    "packaged_desc": "地区配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "7",
    "table": "Area",
    "columns": [
      "7",
      "text_Area_7_1",
      "",
      "area_name_7"
    ],
    "packaged_name": "地区7",
    "packaged_desc": "地区配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "8",
    "table": "Area",
    "columns": [
      "8",
      "text_Area_8_1",
      "",
      "area_name_8"
    ],
    "packaged_name": "地区8",
    "packaged_desc": "地区配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "101",
    "table": "Area",
    "columns": [
      "101",
      "text_Area_101_1",
      "1",
      "area_name_101"
    ],
    "packaged_name": "地区101",
    "packaged_desc": "地区配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "102",
    "table": "Area",
    "columns": [
      "102",
      "text_Area_102_1",
      "1",
      "area_name_102"
    ],
    "packaged_name": "地区102",
    "packaged_desc": "地区配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "103",
    "table": "Area",
    "columns": [
      "103",
      "text_Area_103_1",
      "1",
      "area_name_103"
    ],
    "packaged_name": "地区103",
    "packaged_desc": "地区配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "104",
    "table": "Area",
    "columns": [
      "104",
      "text_Area_104_1",
      "1",
      "area_name_104"
    ],
    "packaged_name": "地区104",
    "packaged_desc": "地区配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "105",
    "table": "Area",
    "columns": [
      "105",
      "text_Area_105_1",
      "1",
      "area_name_105"
    ],
    "packaged_name": "地区105",
    "packaged_desc": "地区配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "106",
    "table": "Area",
    "columns": [
      "106",
      "text_Area_106_1",
      "1",
      "area_name_106"
    ],
    "packaged_name": "地区106",
    "packaged_desc": "地区配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "107",
    "table": "Area",
    "columns": [
      "107",
      "text_Area_107_1",
      "1",
      "area_name_107"
    ],
    "packaged_name": "地区107",
    "packaged_desc": "地区配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "108",
    "table": "Area",
    "columns": [
      "108",
      "text_Area_108_1",
      "1",
      "area_name_108"
    ],
    "packaged_name": "地区108",
    "packaged_desc": "地区配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "109",
    "table": "Area",
    "columns": [
      "109",
      "text_Area_109_1",
      "1",
      "area_name_109"
    ],
    "packaged_name": "地区109",
    "packaged_desc": "地区配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "110",
    "table": "Area",
    "columns": [
      "110",
      "text_Area_110_1",
      "1",
      "area_name_110"
    ],
    "packaged_name": "地区110",
    "packaged_desc": "地区配置行 18，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "111",
    "table": "Area",
    "columns": [
      "111",
      "text_Area_111_1",
      "1",
      "area_name_111"
    ],
    "packaged_name": "地区111",
    "packaged_desc": "地区配置行 19，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "112",
    "table": "Area",
    "columns": [
      "112",
      "text_Area_112_1",
      "1",
      "area_name_112"
    ],
    "packaged_name": "地区112",
    "packaged_desc": "地区配置行 20，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "113",
    "table": "Area",
    "columns": [
      "113",
      "text_Area_113_1",
      "1",
      "area_name_113"
    ],
    "packaged_name": "地区113",
    "packaged_desc": "地区配置行 21，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "114",
    "table": "Area",
    "columns": [
      "114",
      "text_Area_114_1",
      "1",
      "area_name_114"
    ],
    "packaged_name": "地区114",
    "packaged_desc": "地区配置行 22，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "115",
    "table": "Area",
    "columns": [
      "115",
      "text_Area_115_1",
      "1",
      "area_name_115"
    ],
    "packaged_name": "地区115",
    "packaged_desc": "地区配置行 23，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "116",
    "table": "Area",
    "columns": [
      "116",
      "text_Area_116_1",
      "1",
      "area_name_116"
    ],
    "packaged_name": "地区116",
    "packaged_desc": "地区配置行 24，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "201",
    "table": "Area",
    "columns": [
      "201",
      "text_Area_201_1",
      "2",
      "area_name_201"
    ],
    "packaged_name": "地区201",
    "packaged_desc": "地区配置行 25，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "202",
    "table": "Area",
    "columns": [
      "202",
      "text_Area_202_1",
      "2",
      "area_name_202"
    ],
    "packaged_name": "地区202",
    "packaged_desc": "地区配置行 26，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "203",
    "table": "Area",
    "columns": [
      "203",
      "text_Area_203_1",
      "2",
      "area_name_203"
    ],
    "packaged_name": "地区203",
    "packaged_desc": "地区配置行 27，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "204",
    "table": "Area",
    "columns": [
      "204",
      "text_Area_204_1",
      "2",
      "area_name_204"
    ],
    "packaged_name": "地区204",
    "packaged_desc": "地区配置行 28，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "205",
    "table": "Area",
    "columns": [
      "205",
      "text_Area_205_1",
      "2",
      "area_name_205"
    ],
    "packaged_name": "地区205",
    "packaged_desc": "地区配置行 29，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "206",
    "table": "Area",
    "columns": [
      "206",
      "text_Area_206_1",
      "2",
      "area_name_206"
    ],
    "packaged_name": "地区206",
    "packaged_desc": "地区配置行 30，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "207",
    "table": "Area",
    "columns": [
      "207",
      "text_Area_207_1",
      "2",
      "area_name_207"
    ],
    "packaged_name": "地区207",
    "packaged_desc": "地区配置行 31，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "208",
    "table": "Area",
    "columns": [
      "208",
      "text_Area_208_1",
      "2",
      "area_name_208"
    ],
    "packaged_name": "地区208",
    "packaged_desc": "地区配置行 32，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "209",
    "table": "Area",
    "columns": [
      "209",
      "text_Area_209_1",
      "2",
      "area_name_209"
    ],
    "packaged_name": "地区209",
    "packaged_desc": "地区配置行 33，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "210",
    "table": "Area",
    "columns": [
      "210",
      "text_Area_210_1",
      "2",
      "area_name_210"
    ],
    "packaged_name": "地区210",
    "packaged_desc": "地区配置行 34，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "211",
    "table": "Area",
    "columns": [
      "211",
      "text_Area_211_1",
      "2",
      "area_name_211"
    ],
    "packaged_name": "地区211",
    "packaged_desc": "地区配置行 35，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "212",
    "table": "Area",
    "columns": [
      "212",
      "text_Area_212_1",
      "2",
      "area_name_212"
    ],
    "packaged_name": "地区212",
    "packaged_desc": "地区配置行 36，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "213",
    "table": "Area",
    "columns": [
      "213",
      "text_Area_213_1",
      "2",
      "area_name_213"
    ],
    "packaged_name": "地区213",
    "packaged_desc": "地区配置行 37，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "214",
    "table": "Area",
    "columns": [
      "214",
      "text_Area_214_1",
      "2",
      "area_name_214"
    ],
    "packaged_name": "地区214",
    "packaged_desc": "地区配置行 38，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "215",
    "table": "Area",
    "columns": [
      "215",
      "text_Area_215_1",
      "2",
      "area_name_215"
    ],
    "packaged_name": "地区215",
    "packaged_desc": "地区配置行 39，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "216",
    "table": "Area",
    "columns": [
      "216",
      "text_Area_216_1",
      "2",
      "area_name_216"
    ],
    "packaged_name": "地区216",
    "packaged_desc": "地区配置行 40，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "217",
    "table": "Area",
    "columns": [
      "217",
      "text_Area_217_1",
      "2",
      "area_name_217"
    ],
    "packaged_name": "地区217",
    "packaged_desc": "地区配置行 41，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "301",
    "table": "Area",
    "columns": [
      "301",
      "text_Area_301_1",
      "3",
      "area_name_301"
    ],
    "packaged_name": "地区301",
    "packaged_desc": "地区配置行 42，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "302",
    "table": "Area",
    "columns": [
      "302",
      "text_Area_302_1",
      "3",
      "area_name_302"
    ],
    "packaged_name": "地区302",
    "packaged_desc": "地区配置行 43，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "303",
    "table": "Area",
    "columns": [
      "303",
      "text_Area_303_1",
      "3",
      "area_name_303"
    ],
    "packaged_name": "地区303",
    "packaged_desc": "地区配置行 44，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "304",
    "table": "Area",
    "columns": [
      "304",
      "text_Area_304_1",
      "3",
      "area_name_304"
    ],
    "packaged_name": "地区304",
    "packaged_desc": "地区配置行 45，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "305",
    "table": "Area",
    "columns": [
      "305",
      "text_Area_305_1",
      "3",
      "area_name_305"
    ],
    "packaged_name": "地区305",
    "packaged_desc": "地区配置行 46，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "306",
    "table": "Area",
    "columns": [
      "306",
      "text_Area_306_1",
      "3",
      "area_name_306"
    ],
    "packaged_name": "地区306",
    "packaged_desc": "地区配置行 47，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "307",
    "table": "Area",
    "columns": [
      "307",
      "text_Area_307_1",
      "3",
      "area_name_307"
    ],
    "packaged_name": "地区307",
    "packaged_desc": "地区配置行 48，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "308",
    "table": "Area",
    "columns": [
      "308",
      "text_Area_308_1",
      "3",
      "area_name_308"
    ],
    "packaged_name": "地区308",
    "packaged_desc": "地区配置行 49，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "309",
    "table": "Area",
    "columns": [
      "309",
      "text_Area_309_1",
      "3",
      "area_name_309"
    ],
    "packaged_name": "地区309",
    "packaged_desc": "地区配置行 50，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "310",
    "table": "Area",
    "columns": [
      "310",
      "text_Area_310_1",
      "3",
      "area_name_310"
    ],
    "packaged_name": "地区310",
    "packaged_desc": "地区配置行 51，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "311",
    "table": "Area",
    "columns": [
      "311",
      "text_Area_311_1",
      "3",
      "area_name_311"
    ],
    "packaged_name": "地区311",
    "packaged_desc": "地区配置行 52，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "312",
    "table": "Area",
    "columns": [
      "312",
      "text_Area_312_1",
      "3",
      "area_name_312"
    ],
    "packaged_name": "地区312",
    "packaged_desc": "地区配置行 53，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "313",
    "table": "Area",
    "columns": [
      "313",
      "text_Area_313_1",
      "3",
      "area_name_313"
    ],
    "packaged_name": "地区313",
    "packaged_desc": "地区配置行 54，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "314",
    "table": "Area",
    "columns": [
      "314",
      "text_Area_314_1",
      "3",
      "area_name_314"
    ],
    "packaged_name": "地区314",
    "packaged_desc": "地区配置行 55，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "315",
    "table": "Area",
    "columns": [
      "315",
      "text_Area_315_1",
      "3",
      "area_name_315"
    ],
    "packaged_name": "地区315",
    "packaged_desc": "地区配置行 56，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "316",
    "table": "Area",
    "columns": [
      "316",
      "text_Area_316_1",
      "3",
      "area_name_316"
    ],
    "packaged_name": "地区316",
    "packaged_desc": "地区配置行 57，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "317",
    "table": "Area",
    "columns": [
      "317",
      "text_Area_317_1",
      "3",
      "area_name_317"
    ],
    "packaged_name": "地区317",
    "packaged_desc": "地区配置行 58，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "401",
    "table": "Area",
    "columns": [
      "401",
      "text_Area_401_1",
      "4",
      "area_name_401"
    ],
    "packaged_name": "地区401",
    "packaged_desc": "地区配置行 59，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "402",
    "table": "Area",
    "columns": [
      "402",
      "text_Area_402_1",
      "4",
      "area_name_402"
    ],
    "packaged_name": "地区402",
    "packaged_desc": "地区配置行 60，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "403",
    "table": "Area",
    "columns": [
      "403",
      "text_Area_403_1",
      "4",
      "area_name_403"
    ],
    "packaged_name": "地区403",
    "packaged_desc": "地区配置行 61，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "404",
    "table": "Area",
    "columns": [
      "404",
      "text_Area_404_1",
      "4",
      "area_name_404"
    ],
    "packaged_name": "地区404",
    "packaged_desc": "地区配置行 62，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "405",
    "table": "Area",
    "columns": [
      "405",
      "text_Area_405_1",
      "4",
      "area_name_405"
    ],
    "packaged_name": "地区405",
    "packaged_desc": "地区配置行 63，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "406",
    "table": "Area",
    "columns": [
      "406",
      "text_Area_406_1",
      "4",
      "area_name_406"
    ],
    "packaged_name": "地区406",
    "packaged_desc": "地区配置行 64，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "407",
    "table": "Area",
    "columns": [
      "407",
      "text_Area_407_1",
      "4",
      "area_name_407"
    ],
    "packaged_name": "地区407",
    "packaged_desc": "地区配置行 65，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "408",
    "table": "Area",
    "columns": [
      "408",
      "text_Area_408_1",
      "4",
      "area_name_408"
    ],
    "packaged_name": "地区408",
    "packaged_desc": "地区配置行 66，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "409",
    "table": "Area",
    "columns": [
      "409",
      "text_Area_409_1",
      "4",
      "area_name_409"
    ],
    "packaged_name": "地区409",
    "packaged_desc": "地区配置行 67，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "410",
    "table": "Area",
    "columns": [
      "410",
      "text_Area_410_1",
      "4",
      "area_name_410"
    ],
    "packaged_name": "地区410",
    "packaged_desc": "地区配置行 68，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "411",
    "table": "Area",
    "columns": [
      "411",
      "text_Area_411_1",
      "4",
      "area_name_411"
    ],
    "packaged_name": "地区411",
    "packaged_desc": "地区配置行 69，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "412",
    "table": "Area",
    "columns": [
      "412",
      "text_Area_412_1",
      "4",
      "area_name_412"
    ],
    "packaged_name": "地区412",
    "packaged_desc": "地区配置行 70，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "413",
    "table": "Area",
    "columns": [
      "413",
      "text_Area_413_1",
      "4",
      "area_name_413"
    ],
    "packaged_name": "地区413",
    "packaged_desc": "地区配置行 71，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "414",
    "table": "Area",
    "columns": [
      "414",
      "text_Area_414_1",
      "4",
      "area_name_414"
    ],
    "packaged_name": "地区414",
    "packaged_desc": "地区配置行 72，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "415",
    "table": "Area",
    "columns": [
      "415",
      "text_Area_415_1",
      "4",
      "area_name_415"
    ],
    "packaged_name": "地区415",
    "packaged_desc": "地区配置行 73，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "416",
    "table": "Area",
    "columns": [
      "416",
      "text_Area_416_1",
      "4",
      "area_name_416"
    ],
    "packaged_name": "地区416",
    "packaged_desc": "地区配置行 74，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "417",
    "table": "Area",
    "columns": [
      "417",
      "text_Area_417_1",
      "4",
      "area_name_417"
    ],
    "packaged_name": "地区417",
    "packaged_desc": "地区配置行 75，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "501",
    "table": "Area",
    "columns": [
      "501",
      "text_Area_501_1",
      "5",
      "area_name_501"
    ],
    "packaged_name": "地区501",
    "packaged_desc": "地区配置行 76，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "502",
    "table": "Area",
    "columns": [
      "502",
      "text_Area_502_1",
      "5",
      "area_name_502"
    ],
    "packaged_name": "地区502",
    "packaged_desc": "地区配置行 77，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "503",
    "table": "Area",
    "columns": [
      "503",
      "text_Area_503_1",
      "5",
      "area_name_503"
    ],
    "packaged_name": "地区503",
    "packaged_desc": "地区配置行 78，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "504",
    "table": "Area",
    "columns": [
      "504",
      "text_Area_504_1",
      "5",
      "area_name_504"
    ],
    "packaged_name": "地区504",
    "packaged_desc": "地区配置行 79，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "505",
    "table": "Area",
    "columns": [
      "505",
      "text_Area_505_1",
      "5",
      "area_name_505"
    ],
    "packaged_name": "地区505",
    "packaged_desc": "地区配置行 80，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "506",
    "table": "Area",
    "columns": [
      "506",
      "text_Area_506_1",
      "5",
      "area_name_506"
    ],
    "packaged_name": "地区506",
    "packaged_desc": "地区配置行 81，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "507",
    "table": "Area",
    "columns": [
      "507",
      "text_Area_507_1",
      "5",
      "area_name_507"
    ],
    "packaged_name": "地区507",
    "packaged_desc": "地区配置行 82，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "508",
    "table": "Area",
    "columns": [
      "508",
      "text_Area_508_1",
      "5",
      "area_name_508"
    ],
    "packaged_name": "地区508",
    "packaged_desc": "地区配置行 83，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "509",
    "table": "Area",
    "columns": [
      "509",
      "text_Area_509_1",
      "5",
      "area_name_509"
    ],
    "packaged_name": "地区509",
    "packaged_desc": "地区配置行 84，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "510",
    "table": "Area",
    "columns": [
      "510",
      "text_Area_510_1",
      "5",
      "area_name_510"
    ],
    "packaged_name": "地区510",
    "packaged_desc": "地区配置行 85，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "511",
    "table": "Area",
    "columns": [
      "511",
      "text_Area_511_1",
      "5",
      "area_name_511"
    ],
    "packaged_name": "地区511",
    "packaged_desc": "地区配置行 86，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "512",
    "table": "Area",
    "columns": [
      "512",
      "text_Area_512_1",
      "5",
      "area_name_512"
    ],
    "packaged_name": "地区512",
    "packaged_desc": "地区配置行 87，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "513",
    "table": "Area",
    "columns": [
      "513",
      "text_Area_513_1",
      "5",
      "area_name_513"
    ],
    "packaged_name": "地区513",
    "packaged_desc": "地区配置行 88，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "514",
    "table": "Area",
    "columns": [
      "514",
      "text_Area_514_1",
      "5",
      "area_name_514"
    ],
    "packaged_name": "地区514",
    "packaged_desc": "地区配置行 89，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "515",
    "table": "Area",
    "columns": [
      "515",
      "text_Area_515_1",
      "5",
      "area_name_515"
    ],
    "packaged_name": "地区515",
    "packaged_desc": "地区配置行 90，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "601",
    "table": "Area",
    "columns": [
      "601",
      "text_Area_601_1",
      "6",
      "area_name_601"
    ],
    "packaged_name": "地区601",
    "packaged_desc": "地区配置行 91，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "602",
    "table": "Area",
    "columns": [
      "602",
      "text_Area_602_1",
      "6",
      "area_name_602"
    ],
    "packaged_name": "地区602",
    "packaged_desc": "地区配置行 92，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "603",
    "table": "Area",
    "columns": [
      "603",
      "text_Area_603_1",
      "6",
      "area_name_603"
    ],
    "packaged_name": "地区603",
    "packaged_desc": "地区配置行 93，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "604",
    "table": "Area",
    "columns": [
      "604",
      "text_Area_604_1",
      "6",
      "area_name_604"
    ],
    "packaged_name": "地区604",
    "packaged_desc": "地区配置行 94，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "605",
    "table": "Area",
    "columns": [
      "605",
      "text_Area_605_1",
      "6",
      "area_name_605"
    ],
    "packaged_name": "地区605",
    "packaged_desc": "地区配置行 95，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "701",
    "table": "Area",
    "columns": [
      "701",
      "text_Area_701_1",
      "7",
      "area_name_701"
    ],
    "packaged_name": "地区701",
    "packaged_desc": "地区配置行 96，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "702",
    "table": "Area",
    "columns": [
      "702",
      "text_Area_702_1",
      "7",
      "area_name_702"
    ],
    "packaged_name": "地区702",
    "packaged_desc": "地区配置行 97，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "703",
    "table": "Area",
    "columns": [
      "703",
      "text_Area_703_1",
      "7",
      "area_name_703"
    ],
    "packaged_name": "地区703",
    "packaged_desc": "地区配置行 98，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "704",
    "table": "Area",
    "columns": [
      "704",
      "text_Area_704_1",
      "7",
      "area_name_704"
    ],
    "packaged_name": "地区704",
    "packaged_desc": "地区配置行 99，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "705",
    "table": "Area",
    "columns": [
      "705",
      "text_Area_705_1",
      "7",
      "area_name_705"
    ],
    "packaged_name": "地区705",
    "packaged_desc": "地区配置行 100，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "801",
    "table": "Area",
    "columns": [
      "801",
      "text_Area_801_1",
      "8",
      "area_name_801"
    ],
    "packaged_name": "地区801",
    "packaged_desc": "地区配置行 101，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "802",
    "table": "Area",
    "columns": [
      "802",
      "text_Area_802_1",
      "8",
      "area_name_802"
    ],
    "packaged_name": "地区802",
    "packaged_desc": "地区配置行 102，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "803",
    "table": "Area",
    "columns": [
      "803",
      "text_Area_803_1",
      "8",
      "area_name_803"
    ],
    "packaged_name": "地区803",
    "packaged_desc": "地区配置行 103，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "804",
    "table": "Area",
    "columns": [
      "804",
      "text_Area_804_1",
      "8",
      "area_name_804"
    ],
    "packaged_name": "地区804",
    "packaged_desc": "地区配置行 104，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "805",
    "table": "Area",
    "columns": [
      "805",
      "",
      "8",
      "area_name_805"
    ],
    "packaged_name": "地区805",
    "packaged_desc": "地区配置行 105，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
