// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingBattleItemRow } from '../schema';

export const BattleItem: BidKingBattleItemRow[] = [
  {
    "id": 100100,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100100",
    "item_desc": "battle_item_desc_100100",
    "skill_group": 2,
    "packaged_name": "掌眼令100100",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 5，类型 2。"
  },
  {
    "id": 100101,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100101",
    "item_desc": "battle_item_desc_100101",
    "skill_group": 2,
    "packaged_name": "观局灯100101",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 2，类型 2。"
  },
  {
    "id": 100102,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100102",
    "item_desc": "battle_item_desc_100102",
    "skill_group": 2,
    "packaged_name": "铁算盘100102",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100103,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100103",
    "item_desc": "battle_item_desc_100103",
    "skill_group": 3,
    "packaged_name": "封箱签100103",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 5，类型 3。"
  },
  {
    "id": 100104,
    "item_type_id": [
      11
    ],
    "item_quality": 1,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100104",
    "item_desc": "battle_item_desc_100104",
    "skill_group": 3,
    "packaged_name": "试探牌100104",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 1，类型 3。"
  },
  {
    "id": 100105,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100105",
    "item_desc": "battle_item_desc_100105",
    "skill_group": 3,
    "packaged_name": "观局札100105",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 2，类型 3。"
  },
  {
    "id": 100106,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100106",
    "item_desc": "battle_item_desc_100106",
    "skill_group": 3,
    "packaged_name": "稳盘券100106",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 3，类型 3。"
  },
  {
    "id": 100107,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100107",
    "item_desc": "battle_item_desc_100107",
    "skill_group": 3,
    "packaged_name": "稳盘符100107",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 4，类型 3。"
  },
  {
    "id": 100108,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100108",
    "item_desc": "battle_item_desc_100108",
    "skill_group": 3,
    "packaged_name": "掌眼令100108",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 5，类型 3。"
  },
  {
    "id": 100110,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 4,
    "item_name": "battle_item_name_100110",
    "item_desc": "battle_item_desc_100110",
    "skill_group": 4,
    "packaged_name": "观局灯100110",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 2，类型 4。"
  },
  {
    "id": 100111,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 4,
    "item_name": "battle_item_name_100111",
    "item_desc": "battle_item_desc_100111",
    "skill_group": 4,
    "packaged_name": "铁算盘100111",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 2，类型 4。"
  },
  {
    "id": 100112,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 4,
    "item_name": "battle_item_name_100112",
    "item_desc": "battle_item_desc_100112",
    "skill_group": 4,
    "packaged_name": "封箱签100112",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 2，类型 4。"
  },
  {
    "id": 100113,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 4,
    "item_name": "battle_item_name_100113",
    "item_desc": "battle_item_desc_100113",
    "skill_group": 4,
    "packaged_name": "试探牌100113",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 3，类型 4。"
  },
  {
    "id": 100114,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 4,
    "item_name": "battle_item_name_100114",
    "item_desc": "battle_item_desc_100114",
    "skill_group": 4,
    "packaged_name": "观局札100114",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 5，类型 4。"
  },
  {
    "id": 100115,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100115",
    "item_desc": "battle_item_desc_100115",
    "skill_group": 5,
    "packaged_name": "稳盘券100115",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 4，类型 5。"
  },
  {
    "id": 100116,
    "item_type_id": [
      11
    ],
    "item_quality": 1,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100116",
    "item_desc": "battle_item_desc_100116",
    "skill_group": 5,
    "packaged_name": "稳盘符100116",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 1，类型 5。"
  },
  {
    "id": 100117,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100117",
    "item_desc": "battle_item_desc_100117",
    "skill_group": 5,
    "packaged_name": "掌眼令100117",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 2，类型 5。"
  },
  {
    "id": 100118,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100118",
    "item_desc": "battle_item_desc_100118",
    "skill_group": 5,
    "packaged_name": "观局灯100118",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 3，类型 5。"
  },
  {
    "id": 100119,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100119",
    "item_desc": "battle_item_desc_100119",
    "skill_group": 5,
    "packaged_name": "铁算盘100119",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 4，类型 5。"
  },
  {
    "id": 100120,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 5,
    "item_name": "battle_item_name_100120",
    "item_desc": "battle_item_desc_100120",
    "skill_group": 5,
    "packaged_name": "封箱签100120",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 5，类型 5。"
  },
  {
    "id": 100121,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100121",
    "item_desc": "battle_item_desc_100121",
    "skill_group": 6,
    "packaged_name": "试探牌100121",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 6，类型 6。"
  },
  {
    "id": 100122,
    "item_type_id": [
      11
    ],
    "item_quality": 1,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100122",
    "item_desc": "battle_item_desc_100122",
    "skill_group": 6,
    "packaged_name": "观局札100122",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 1，类型 6。"
  },
  {
    "id": 100123,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100123",
    "item_desc": "battle_item_desc_100123",
    "skill_group": 6,
    "packaged_name": "稳盘券100123",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 2，类型 6。"
  },
  {
    "id": 100124,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100124",
    "item_desc": "battle_item_desc_100124",
    "skill_group": 6,
    "packaged_name": "稳盘符100124",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 3，类型 6。"
  },
  {
    "id": 100125,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100125",
    "item_desc": "battle_item_desc_100125",
    "skill_group": 6,
    "packaged_name": "掌眼令100125",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 4，类型 6。"
  },
  {
    "id": 100126,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100126",
    "item_desc": "battle_item_desc_100126",
    "skill_group": 6,
    "packaged_name": "观局灯100126",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 6，类型 6。"
  },
  {
    "id": 100127,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100127",
    "item_desc": "battle_item_desc_100127",
    "skill_group": 1,
    "packaged_name": "铁算盘100127",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 6，类型 1。"
  },
  {
    "id": 100128,
    "item_type_id": [
      11
    ],
    "item_quality": 1,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100128",
    "item_desc": "battle_item_desc_100128",
    "skill_group": 1,
    "packaged_name": "封箱签100128",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 1，类型 1。"
  },
  {
    "id": 100129,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100129",
    "item_desc": "battle_item_desc_100129",
    "skill_group": 1,
    "packaged_name": "试探牌100129",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 2，类型 1。"
  },
  {
    "id": 100130,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100130",
    "item_desc": "battle_item_desc_100130",
    "skill_group": 1,
    "packaged_name": "观局札100130",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 4，类型 1。"
  },
  {
    "id": 100131,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100131",
    "item_desc": "battle_item_desc_100131",
    "skill_group": 1,
    "packaged_name": "稳盘券100131",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 5，类型 1。"
  },
  {
    "id": 100132,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100132",
    "item_desc": "battle_item_desc_100132",
    "skill_group": 1,
    "packaged_name": "稳盘符100132",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 6，类型 1。"
  },
  {
    "id": 100133,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100133",
    "item_desc": "battle_item_desc_100133",
    "skill_group": 1,
    "packaged_name": "掌眼令100133",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 6，类型 1。"
  },
  {
    "id": 100134,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100134",
    "item_desc": "battle_item_desc_100134",
    "skill_group": 7,
    "packaged_name": "观局灯100134",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 6，类型 7。"
  },
  {
    "id": 100135,
    "item_type_id": [
      11
    ],
    "item_quality": 1,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100135",
    "item_desc": "battle_item_desc_100135",
    "skill_group": 7,
    "packaged_name": "铁算盘100135",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 1，类型 7。"
  },
  {
    "id": 100136,
    "item_type_id": [
      11
    ],
    "item_quality": 2,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100136",
    "item_desc": "battle_item_desc_100136",
    "skill_group": 7,
    "packaged_name": "封箱签100136",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 2，类型 7。"
  },
  {
    "id": 100137,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100137",
    "item_desc": "battle_item_desc_100137",
    "skill_group": 7,
    "packaged_name": "试探牌100137",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 3，类型 7。"
  },
  {
    "id": 100138,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100138",
    "item_desc": "battle_item_desc_100138",
    "skill_group": 7,
    "packaged_name": "观局札100138",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 4，类型 7。"
  },
  {
    "id": 100139,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100139",
    "item_desc": "battle_item_desc_100139",
    "skill_group": 7,
    "packaged_name": "稳盘券100139",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 4，类型 7。"
  },
  {
    "id": 100140,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100140",
    "item_desc": "battle_item_desc_100140",
    "skill_group": 7,
    "packaged_name": "稳盘符100140",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 5，类型 7。"
  },
  {
    "id": 100151,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100151",
    "item_desc": "battle_item_desc_100151",
    "skill_group": 2,
    "packaged_name": "掌眼令100151",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100152,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100152",
    "item_desc": "battle_item_desc_100152",
    "skill_group": 2,
    "packaged_name": "观局灯100152",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100153,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100153",
    "item_desc": "battle_item_desc_100153",
    "skill_group": 2,
    "packaged_name": "铁算盘100153",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100154,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100154",
    "item_desc": "battle_item_desc_100154",
    "skill_group": 2,
    "packaged_name": "封箱签100154",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100155,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100155",
    "item_desc": "battle_item_desc_100155",
    "skill_group": 2,
    "packaged_name": "试探牌100155",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100156,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100156",
    "item_desc": "battle_item_desc_100156",
    "skill_group": 2,
    "packaged_name": "观局札100156",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100157,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100157",
    "item_desc": "battle_item_desc_100157",
    "skill_group": 2,
    "packaged_name": "稳盘券100157",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100158,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100158",
    "item_desc": "battle_item_desc_100158",
    "skill_group": 2,
    "packaged_name": "稳盘符100158",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100159,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100159",
    "item_desc": "battle_item_desc_100159",
    "skill_group": 2,
    "packaged_name": "掌眼令100159",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100160,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100160",
    "item_desc": "battle_item_desc_100160",
    "skill_group": 2,
    "packaged_name": "观局灯100160",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100174,
    "item_type_id": [
      11
    ],
    "item_quality": 6,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100174",
    "item_desc": "battle_item_desc_100174",
    "skill_group": 7,
    "packaged_name": "铁算盘100174",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 6，类型 7。"
  },
  {
    "id": 100161,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 2,
    "item_name": "battle_item_name_100161",
    "item_desc": "battle_item_desc_100161",
    "skill_group": 2,
    "packaged_name": "封箱签100161",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 3，类型 2。"
  },
  {
    "id": 100162,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 3,
    "item_name": "battle_item_name_100162",
    "item_desc": "battle_item_desc_100162",
    "skill_group": 3,
    "packaged_name": "试探牌100162",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 3，类型 3。"
  },
  {
    "id": 100163,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100163",
    "item_desc": "battle_item_desc_100163",
    "skill_group": 6,
    "packaged_name": "观局札100163",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 4，类型 6。"
  },
  {
    "id": 100164,
    "item_type_id": [
      11
    ],
    "item_quality": 5,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100164",
    "item_desc": "battle_item_desc_100164",
    "skill_group": 1,
    "packaged_name": "稳盘券100164",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 5，类型 1。"
  },
  {
    "id": 100165,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100165",
    "item_desc": "battle_item_desc_100165",
    "skill_group": 1,
    "packaged_name": "稳盘符100165",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 3，类型 1。"
  },
  {
    "id": 100166,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 7,
    "item_name": "battle_item_name_100166",
    "item_desc": "battle_item_desc_100166",
    "skill_group": 7,
    "packaged_name": "掌眼令100166",
    "packaged_desc": "掌眼令：原局内拍卖辅助道具，品质 3，类型 7。"
  },
  {
    "id": 100167,
    "item_type_id": [
      11
    ],
    "item_quality": 3,
    "battle_item_type": 6,
    "item_name": "battle_item_name_100167",
    "item_desc": "battle_item_desc_100167",
    "skill_group": 6,
    "packaged_name": "观局灯100167",
    "packaged_desc": "观局灯：原局内拍卖辅助道具，品质 3，类型 6。"
  },
  {
    "id": 100168,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 1,
    "item_name": "battle_item_name_100168",
    "item_desc": "battle_item_desc_100168",
    "skill_group": 1,
    "packaged_name": "铁算盘100168",
    "packaged_desc": "铁算盘：原局内拍卖辅助道具，品质 4，类型 1。"
  },
  {
    "id": 100169,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 8,
    "item_name": "battle_item_name_100169",
    "item_desc": "battle_item_desc_100169",
    "skill_group": 8,
    "packaged_name": "封箱签100169",
    "packaged_desc": "封箱签：原局内拍卖辅助道具，品质 4，类型 8。"
  },
  {
    "id": 100170,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 8,
    "item_name": "battle_item_name_100170",
    "item_desc": "battle_item_desc_100170",
    "skill_group": 8,
    "packaged_name": "试探牌100170",
    "packaged_desc": "试探牌：原局内拍卖辅助道具，品质 4，类型 8。"
  },
  {
    "id": 100171,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 8,
    "item_name": "battle_item_name_100171",
    "item_desc": "battle_item_desc_100171",
    "skill_group": 8,
    "packaged_name": "观局札100171",
    "packaged_desc": "观局札：原局内拍卖辅助道具，品质 4，类型 8。"
  },
  {
    "id": 100172,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 8,
    "item_name": "battle_item_name_100172",
    "item_desc": "battle_item_desc_100172",
    "skill_group": 8,
    "packaged_name": "稳盘券100172",
    "packaged_desc": "稳盘券：原局内拍卖辅助道具，品质 4，类型 8。"
  },
  {
    "id": 100173,
    "item_type_id": [
      11
    ],
    "item_quality": 4,
    "battle_item_type": 8,
    "item_name": "battle_item_name_100173",
    "item_desc": "battle_item_desc_100173",
    "skill_group": 8,
    "packaged_name": "稳盘符100173",
    "packaged_desc": "稳盘符：原局内拍卖辅助道具，品质 4，类型 8。"
  }
];
