// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingCabinetRow } from '../schema';

export const Cabinet: BidKingCabinetRow[] = [
  {
    "id": 6001,
    "resource_name": "Cabinet_6001",
    "location_type": [
      100,
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_00",
    "resource2": "ui_storage_shelf_00",
    "packaged_name": "秘藏总柜1",
    "packaged_desc": "可陈列 多类，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6101,
    "resource_name": "Cabinet_6101",
    "location_type": [
      101
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_01",
    "resource2": "ui_storage_shelf_01",
    "packaged_name": "府邸日用2",
    "packaged_desc": "可陈列 府邸日用，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6102,
    "resource_name": "Cabinet_6102",
    "location_type": [
      102
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_02",
    "resource2": "ui_storage_shelf_02",
    "packaged_name": "医药军需3",
    "packaged_desc": "可陈列 医药军需，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6103,
    "resource_name": "Cabinet_6103",
    "location_type": [
      103
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_03",
    "resource2": "ui_storage_shelf_03",
    "packaged_name": "锦衣冠服4",
    "packaged_desc": "可陈列 锦衣冠服，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6104,
    "resource_name": "Cabinet_6104",
    "location_type": [
      104
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_04",
    "resource2": "ui_storage_shelf_04",
    "packaged_name": "军械兵装5",
    "packaged_desc": "可陈列 军械兵装，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6105,
    "resource_name": "Cabinet_6105",
    "location_type": [
      105
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_05",
    "resource2": "ui_storage_shelf_05",
    "packaged_name": "矿玉珠宝6",
    "packaged_desc": "可陈列 矿玉珠宝，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6106,
    "resource_name": "Cabinet_6106",
    "location_type": [
      106
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_06",
    "resource2": "ui_storage_shelf_06",
    "packaged_name": "文玩古器7",
    "packaged_desc": "可陈列 文玩古器，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6107,
    "resource_name": "Cabinet_6107",
    "location_type": [
      107
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_07",
    "resource2": "ui_storage_shelf_07",
    "packaged_name": "机巧器具8",
    "packaged_desc": "可陈列 机巧器具，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6108,
    "resource_name": "Cabinet_6108",
    "location_type": [
      108
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_08",
    "resource2": "ui_storage_shelf_08",
    "packaged_name": "车马舟楫9",
    "packaged_desc": "可陈列 车马舟楫，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6109,
    "resource_name": "Cabinet_6109",
    "location_type": [
      109
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_09",
    "resource2": "ui_storage_shelf_09",
    "packaged_name": "酒食香料10",
    "packaged_desc": "可陈列 酒食香料，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6110,
    "resource_name": "Cabinet_6110",
    "location_type": [
      110
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 0,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_10",
    "resource2": "ui_storage_shelf_10",
    "packaged_name": "书画典籍11",
    "packaged_desc": "可陈列 书画典籍，上限 25 件，展示槽 21x11。"
  },
  {
    "id": 6002,
    "resource_name": "Cabinet_7001",
    "location_type": [
      100,
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      110
    ],
    "max_slot_limit": 25,
    "quality_requirement": [
      6,
      7
    ],
    "slot_count": [
      21,
      11
    ],
    "place_max": 15,
    "coinbonus": 500,
    "timemax": 36000,
    "bg_offset": [
      321,
      37
    ],
    "resource": "ui_storage_bg_05",
    "resource2": "ui_storage_shelf_05",
    "packaged_name": "秘藏总柜12",
    "packaged_desc": "可陈列 多类，上限 25 件，展示槽 21x11。"
  }
];
