// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingConditionRow } from '../schema';

export const Condition: BidKingConditionRow[] = [
  {
    "id": 1,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 1,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_1",
    "packaged_desc": "条件 1，参数 0。"
  },
  {
    "id": 2,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 2,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_2",
    "packaged_desc": "条件 2，参数 0。"
  },
  {
    "id": 3,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 3,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_3",
    "packaged_desc": "条件 3，参数 0。"
  },
  {
    "id": 4,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 4,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_4",
    "packaged_desc": "条件 4，参数 0。"
  },
  {
    "id": 5,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 5,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_5",
    "packaged_desc": "条件 5，参数 0。"
  },
  {
    "id": 6,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_6",
    "packaged_desc": "条件 6，参数 0。"
  },
  {
    "id": 7,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_7",
    "packaged_desc": "条件 7，参数 0。"
  },
  {
    "id": 8,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 8,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_8",
    "packaged_desc": "条件 8，参数 0。"
  },
  {
    "id": 9,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 9,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_9",
    "packaged_desc": "条件 9，参数 0。"
  },
  {
    "id": 10,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 10,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10",
    "packaged_desc": "条件 10，参数 0。"
  },
  {
    "id": 11,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 11,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_11",
    "packaged_desc": "条件 11，参数 0。"
  },
  {
    "id": 12,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_12",
    "packaged_desc": "条件 12，参数 0。"
  },
  {
    "id": 13,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 13,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_13",
    "packaged_desc": "条件 13，参数 0。"
  },
  {
    "id": 14,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_14",
    "packaged_desc": "条件 14，参数 0。"
  },
  {
    "id": 15,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_15",
    "packaged_desc": "条件 15，参数 0。"
  },
  {
    "id": 16,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_16",
    "packaged_desc": "条件 16，参数 0。"
  },
  {
    "id": 17,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 17,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_17",
    "packaged_desc": "条件 17，参数 0。"
  },
  {
    "id": 18,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_18",
    "packaged_desc": "条件 18，参数 0。"
  },
  {
    "id": 19,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_19",
    "packaged_desc": "条件 19，参数 0。"
  },
  {
    "id": 20,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 20,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20",
    "packaged_desc": "条件 20，参数 0。"
  },
  {
    "id": 21,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 21,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21",
    "packaged_desc": "条件 21，参数 0。"
  },
  {
    "id": 22,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 22,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_22",
    "packaged_desc": "条件 22，参数 0。"
  },
  {
    "id": 23,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 8,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_23",
    "packaged_desc": "条件 8，参数 0。"
  },
  {
    "id": 24,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_24",
    "packaged_desc": "条件 24，参数 0。"
  },
  {
    "id": 25,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 25,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_25",
    "packaged_desc": "条件 25，参数 0。"
  },
  {
    "id": 10001,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 20,
    "conditionparams": [
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10001",
    "packaged_desc": "条件 20，参数 0。"
  },
  {
    "id": 10002,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10002",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 10003,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      11,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10003",
    "packaged_desc": "条件 6，参数 11/0/0/0/0/1。"
  },
  {
    "id": 10004,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10004",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 10005,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10005",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 10006,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 17,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10006",
    "packaged_desc": "条件 17，参数 1。"
  },
  {
    "id": 100071,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      10000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100071",
    "packaged_desc": "条件 19，参数 10000/0。"
  },
  {
    "id": 100072,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      50000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100072",
    "packaged_desc": "条件 19，参数 50000/0。"
  },
  {
    "id": 100073,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      100000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100073",
    "packaged_desc": "条件 19，参数 100000/0。"
  },
  {
    "id": 100074,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      500000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100074",
    "packaged_desc": "条件 19，参数 500000/0。"
  },
  {
    "id": 100075,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      1000000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100075",
    "packaged_desc": "条件 19，参数 1000000/0。"
  },
  {
    "id": 100076,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      3000000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100076",
    "packaged_desc": "条件 19，参数 3000000/0。"
  },
  {
    "id": 100077,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      6000000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100077",
    "packaged_desc": "条件 19，参数 6000000/0。"
  },
  {
    "id": 10008,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      1,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10008",
    "packaged_desc": "条件 19，参数 1/0。"
  },
  {
    "id": 100091,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      10000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100091",
    "packaged_desc": "条件 18，参数 10000。"
  },
  {
    "id": 100092,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      50000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100092",
    "packaged_desc": "条件 18，参数 50000。"
  },
  {
    "id": 100093,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      100000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100093",
    "packaged_desc": "条件 18，参数 100000。"
  },
  {
    "id": 100094,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      200000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100094",
    "packaged_desc": "条件 18，参数 200000。"
  },
  {
    "id": 100095,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      500000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100095",
    "packaged_desc": "条件 18，参数 500000。"
  },
  {
    "id": 100096,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      2000000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100096",
    "packaged_desc": "条件 18，参数 2000000。"
  },
  {
    "id": 100097,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      5000000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100097",
    "packaged_desc": "条件 18，参数 5000000。"
  },
  {
    "id": 10010,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10010",
    "packaged_desc": "条件 7，参数 0/0/0/0/0/1。"
  },
  {
    "id": 10011,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 10,
    "conditionparams": [
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10011",
    "packaged_desc": "条件 10，参数 0/0/0/0/0/1。"
  },
  {
    "id": 10012,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 9,
    "conditionparams": [
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10012",
    "packaged_desc": "条件 9，参数 0/0/0/0/0/1。"
  },
  {
    "id": 100131,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      10000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100131",
    "packaged_desc": "条件 14，参数 10000/0。"
  },
  {
    "id": 100132,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      50000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100132",
    "packaged_desc": "条件 14，参数 50000/0。"
  },
  {
    "id": 100133,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      100000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100133",
    "packaged_desc": "条件 14，参数 100000/0。"
  },
  {
    "id": 100134,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      200000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100134",
    "packaged_desc": "条件 14，参数 200000/0。"
  },
  {
    "id": 100135,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      500000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100135",
    "packaged_desc": "条件 14，参数 500000/0。"
  },
  {
    "id": 100136,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      2000000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100136",
    "packaged_desc": "条件 14，参数 2000000/0。"
  },
  {
    "id": 100137,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 14,
    "conditionparams": [
      5000000,
      0
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_100137",
    "packaged_desc": "条件 14，参数 5000000/0。"
  },
  {
    "id": 10014,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 13,
    "conditionparams": [
      1,
      2
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10014",
    "packaged_desc": "条件 13，参数 1/2。"
  },
  {
    "id": 10015,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      5,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10015",
    "packaged_desc": "条件 7，参数 0/5/0/0/0/1。"
  },
  {
    "id": 10016,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      6,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10016",
    "packaged_desc": "条件 7，参数 0/6/0/0/0/1。"
  },
  {
    "id": 10017,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 8,
    "conditionparams": [
      6,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10017",
    "packaged_desc": "条件 8，参数 6/0/0/0/0/0/0/1。"
  },
  {
    "id": 10018,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 8,
    "conditionparams": [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_10018",
    "packaged_desc": "条件 8，参数 1/0/0/0/0/0/0/1。"
  },
  {
    "id": 20001,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150101,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20001",
    "packaged_desc": "条件 12，参数 0/0/150101/0/0/1。"
  },
  {
    "id": 20002,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410101,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20002",
    "packaged_desc": "条件 12，参数 0/0/1410101/0/0/1。"
  },
  {
    "id": 20003,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150102,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20003",
    "packaged_desc": "条件 12，参数 0/0/150102/0/0/1。"
  },
  {
    "id": 20004,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410201,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20004",
    "packaged_desc": "条件 12，参数 0/0/1410201/0/0/1。"
  },
  {
    "id": 20005,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150103,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20005",
    "packaged_desc": "条件 12，参数 0/0/150103/0/0/1。"
  },
  {
    "id": 20006,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410301,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20006",
    "packaged_desc": "条件 12，参数 0/0/1410301/0/0/1。"
  },
  {
    "id": 20007,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150104,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20007",
    "packaged_desc": "条件 12，参数 0/0/150104/0/0/1。"
  },
  {
    "id": 20008,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410401,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20008",
    "packaged_desc": "条件 12，参数 0/0/1410401/0/0/1。"
  },
  {
    "id": 20009,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150105,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20009",
    "packaged_desc": "条件 12，参数 0/0/150105/0/0/1。"
  },
  {
    "id": 20010,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410501,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20010",
    "packaged_desc": "条件 12，参数 0/0/1410501/0/0/1。"
  },
  {
    "id": 20011,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150106,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20011",
    "packaged_desc": "条件 12，参数 0/0/150106/0/0/1。"
  },
  {
    "id": 20012,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410601,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20012",
    "packaged_desc": "条件 12，参数 0/0/1410601/0/0/1。"
  },
  {
    "id": 20013,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150107,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20013",
    "packaged_desc": "条件 12，参数 0/0/150107/0/0/1。"
  },
  {
    "id": 20014,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410701,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20014",
    "packaged_desc": "条件 12，参数 0/0/1410701/0/0/1。"
  },
  {
    "id": 20015,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150108,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20015",
    "packaged_desc": "条件 12，参数 0/0/150108/0/0/1。"
  },
  {
    "id": 20016,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410801,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20016",
    "packaged_desc": "条件 12，参数 0/0/1410801/0/0/1。"
  },
  {
    "id": 20017,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150109,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20017",
    "packaged_desc": "条件 12，参数 0/0/150109/0/0/1。"
  },
  {
    "id": 20018,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1410901,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20018",
    "packaged_desc": "条件 12，参数 0/0/1410901/0/0/1。"
  },
  {
    "id": 20019,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150110,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20019",
    "packaged_desc": "条件 12，参数 0/0/150110/0/0/1。"
  },
  {
    "id": 20020,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1411001,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20020",
    "packaged_desc": "条件 12，参数 0/0/1411001/0/0/1。"
  },
  {
    "id": 20021,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150201,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20021",
    "packaged_desc": "条件 12，参数 0/0/150201/0/0/1。"
  },
  {
    "id": 20022,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420101,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20022",
    "packaged_desc": "条件 12，参数 0/0/1420101/0/0/1。"
  },
  {
    "id": 20023,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150202,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20023",
    "packaged_desc": "条件 12，参数 0/0/150202/0/0/1。"
  },
  {
    "id": 20024,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420201,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20024",
    "packaged_desc": "条件 12，参数 0/0/1420201/0/0/1。"
  },
  {
    "id": 20025,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150203,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20025",
    "packaged_desc": "条件 12，参数 0/0/150203/0/0/1。"
  },
  {
    "id": 20026,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420301,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20026",
    "packaged_desc": "条件 12，参数 0/0/1420301/0/0/1。"
  },
  {
    "id": 20027,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150204,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20027",
    "packaged_desc": "条件 12，参数 0/0/150204/0/0/1。"
  },
  {
    "id": 20028,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420401,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20028",
    "packaged_desc": "条件 12，参数 0/0/1420401/0/0/1。"
  },
  {
    "id": 20029,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150205,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20029",
    "packaged_desc": "条件 12，参数 0/0/150205/0/0/1。"
  },
  {
    "id": 20030,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420501,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20030",
    "packaged_desc": "条件 12，参数 0/0/1420501/0/0/1。"
  },
  {
    "id": 20031,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150206,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20031",
    "packaged_desc": "条件 12，参数 0/0/150206/0/0/1。"
  },
  {
    "id": 20032,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420601,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20032",
    "packaged_desc": "条件 12，参数 0/0/1420601/0/0/1。"
  },
  {
    "id": 20033,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150207,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20033",
    "packaged_desc": "条件 12，参数 0/0/150207/0/0/1。"
  },
  {
    "id": 20034,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420701,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20034",
    "packaged_desc": "条件 12，参数 0/0/1420701/0/0/1。"
  },
  {
    "id": 20035,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150208,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20035",
    "packaged_desc": "条件 12，参数 0/0/150208/0/0/1。"
  },
  {
    "id": 20036,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420801,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20036",
    "packaged_desc": "条件 12，参数 0/0/1420801/0/0/1。"
  },
  {
    "id": 20037,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150209,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20037",
    "packaged_desc": "条件 12，参数 0/0/150209/0/0/1。"
  },
  {
    "id": 20038,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420901,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20038",
    "packaged_desc": "条件 12，参数 0/0/1420901/0/0/1。"
  },
  {
    "id": 20039,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      150301,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20039",
    "packaged_desc": "条件 12，参数 0/0/150301/0/0/1。"
  },
  {
    "id": 20040,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1430101,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20040",
    "packaged_desc": "条件 12，参数 0/0/1430101/0/0/1。"
  },
  {
    "id": 20041,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1420802,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20041",
    "packaged_desc": "条件 12，参数 0/0/1420802/0/0/1。"
  },
  {
    "id": 20101,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        101
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20101",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20102,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        102
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20102",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20103,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        103
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20103",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20104,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        104
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20104",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20105,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        105
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20105",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20106,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        106
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20106",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20107,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        107
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20107",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20108,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        108
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20108",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20109,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        109
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20109",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20110,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        110
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20110",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20111,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        201
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20111",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20112,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        202
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20112",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20113,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        203
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20113",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20114,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        204
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20114",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20115,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        205
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20115",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20116,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        206
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20116",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20117,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        207
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20117",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20118,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        208
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20118",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20119,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        209
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20119",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 20120,
    "type": 0,
    "preorconditions": [
      3
    ],
    "preorconditionsparam": [
      [
        301
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_20120",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 21001,
    "type": 0,
    "preorconditions": [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5
    ],
    "preorconditionsparam": [
      [
        2101
      ],
      [
        2102
      ],
      [
        2103
      ],
      [
        2104
      ],
      [
        2105
      ],
      [
        2106
      ],
      [
        2107
      ],
      [
        2202
      ],
      [
        2203
      ],
      [
        2204
      ],
      [
        2205
      ],
      [
        2302
      ],
      [
        2303
      ],
      [
        2304
      ],
      [
        2305
      ],
      [
        2306
      ],
      [
        2307
      ],
      [
        2308
      ],
      [
        2309
      ],
      [
        2310
      ],
      [
        2402
      ],
      [
        2403
      ],
      [
        2404
      ],
      [
        2405
      ],
      [
        2406
      ],
      [
        2407
      ],
      [
        2408
      ],
      [
        2409
      ],
      [
        2410
      ],
      [
        2502
      ],
      [
        2503
      ],
      [
        2504
      ],
      [
        2505
      ],
      [
        2506
      ],
      [
        2507
      ],
      [
        2508
      ],
      [
        2509
      ],
      [
        2510
      ],
      [
        4402
      ],
      [
        4403
      ],
      [
        4404
      ],
      [
        4405
      ],
      [
        4406
      ],
      [
        4407
      ],
      [
        4408
      ],
      [
        4409
      ],
      [
        4410
      ],
      [
        4502
      ],
      [
        4503
      ],
      [
        4504
      ],
      [
        4505
      ],
      [
        4506
      ],
      [
        4507
      ],
      [
        4508
      ],
      [
        4509
      ],
      [
        4510
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21001",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 21002,
    "type": 0,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        102
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21002",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 21003,
    "type": 0,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        103
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21003",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 21004,
    "type": 0,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        104
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21004",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 21005,
    "type": 0,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        105
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21005",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 21006,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 9,
    "conditionparams": [
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21006",
    "packaged_desc": "条件 9，参数 0/0/0/0/0/1。"
  },
  {
    "id": 21007,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      5,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21007",
    "packaged_desc": "条件 7，参数 0/5/0/0/0/1。"
  },
  {
    "id": 21008,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      6,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_21008",
    "packaged_desc": "条件 7，参数 0/6/0/0/0/1。"
  },
  {
    "id": 30001,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 20,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30001",
    "packaged_desc": "条件 20，参数 1。"
  },
  {
    "id": 30002,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30002",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 30003,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      11,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30003",
    "packaged_desc": "条件 6，参数 11/0/0/0/0/1。"
  },
  {
    "id": 30004,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 15,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30004",
    "packaged_desc": "条件 15，参数 1。"
  },
  {
    "id": 30005,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30005",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 30006,
    "type": 0,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 25,
    "conditionparams": [
      2,
      100000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_30006",
    "packaged_desc": "条件 25，参数 2/100000。"
  },
  {
    "id": 50001,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 20,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50001",
    "packaged_desc": "条件 20，参数 1。"
  },
  {
    "id": 50002,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1001,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50002",
    "packaged_desc": "条件 12，参数 0/0/1001/0/0/1。"
  },
  {
    "id": 50003,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1002,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50003",
    "packaged_desc": "条件 12，参数 0/0/1002/0/0/1。"
  },
  {
    "id": 50004,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1003,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50004",
    "packaged_desc": "条件 12，参数 0/0/1003/0/0/1。"
  },
  {
    "id": 50005,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50005",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50006,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1011,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50006",
    "packaged_desc": "条件 12，参数 0/0/1011/0/0/1。"
  },
  {
    "id": 50007,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1012,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50007",
    "packaged_desc": "条件 12，参数 0/0/1012/0/0/1。"
  },
  {
    "id": 50008,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1013,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50008",
    "packaged_desc": "条件 12，参数 0/0/1013/0/0/1。"
  },
  {
    "id": 50009,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50009",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50010,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1021,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50010",
    "packaged_desc": "条件 12，参数 0/0/1021/0/0/1。"
  },
  {
    "id": 50011,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1022,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50011",
    "packaged_desc": "条件 12，参数 0/0/1022/0/0/1。"
  },
  {
    "id": 50012,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1023,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50012",
    "packaged_desc": "条件 12，参数 0/0/1023/0/0/1。"
  },
  {
    "id": 50013,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50013",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50014,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1031,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50014",
    "packaged_desc": "条件 12，参数 0/0/1031/0/0/1。"
  },
  {
    "id": 50015,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1032,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50015",
    "packaged_desc": "条件 12，参数 0/0/1032/0/0/1。"
  },
  {
    "id": 50016,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1033,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50016",
    "packaged_desc": "条件 12，参数 0/0/1033/0/0/1。"
  },
  {
    "id": 50017,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50017",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50018,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1041,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50018",
    "packaged_desc": "条件 12，参数 0/0/1041/0/0/1。"
  },
  {
    "id": 50019,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1042,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50019",
    "packaged_desc": "条件 12，参数 0/0/1042/0/0/1。"
  },
  {
    "id": 50020,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1043,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50020",
    "packaged_desc": "条件 12，参数 0/0/1043/0/0/1。"
  },
  {
    "id": 50021,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50021",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50022,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1051,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50022",
    "packaged_desc": "条件 12，参数 0/0/1051/0/0/1。"
  },
  {
    "id": 50023,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1052,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50023",
    "packaged_desc": "条件 12，参数 0/0/1052/0/0/1。"
  },
  {
    "id": 50024,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1053,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50024",
    "packaged_desc": "条件 12，参数 0/0/1053/0/0/1。"
  },
  {
    "id": 50025,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50025",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50026,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1061,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50026",
    "packaged_desc": "条件 12，参数 0/0/1061/0/0/1。"
  },
  {
    "id": 50027,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1062,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50027",
    "packaged_desc": "条件 12，参数 0/0/1062/0/0/1。"
  },
  {
    "id": 50028,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1063,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50028",
    "packaged_desc": "条件 12，参数 0/0/1063/0/0/1。"
  },
  {
    "id": 50029,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50029",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50030,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1071,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50030",
    "packaged_desc": "条件 12，参数 0/0/1071/0/0/1。"
  },
  {
    "id": 50031,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1072,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50031",
    "packaged_desc": "条件 12，参数 0/0/1072/0/0/1。"
  },
  {
    "id": 50032,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1073,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50032",
    "packaged_desc": "条件 12，参数 0/0/1073/0/0/1。"
  },
  {
    "id": 50033,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50033",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50034,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1081,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50034",
    "packaged_desc": "条件 12，参数 0/0/1081/0/0/1。"
  },
  {
    "id": 50035,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1082,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50035",
    "packaged_desc": "条件 12，参数 0/0/1082/0/0/1。"
  },
  {
    "id": 50036,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1083,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50036",
    "packaged_desc": "条件 12，参数 0/0/1083/0/0/1。"
  },
  {
    "id": 50037,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50037",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50038,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1091,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50038",
    "packaged_desc": "条件 12，参数 0/0/1091/0/0/1。"
  },
  {
    "id": 50039,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1092,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50039",
    "packaged_desc": "条件 12，参数 0/0/1092/0/0/1。"
  },
  {
    "id": 50040,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1093,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50040",
    "packaged_desc": "条件 12，参数 0/0/1093/0/0/1。"
  },
  {
    "id": 50041,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50041",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50042,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1101,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50042",
    "packaged_desc": "条件 12，参数 0/0/1101/0/0/1。"
  },
  {
    "id": 50043,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1102,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50043",
    "packaged_desc": "条件 12，参数 0/0/1102/0/0/1。"
  },
  {
    "id": 50044,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1103,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50044",
    "packaged_desc": "条件 12，参数 0/0/1103/0/0/1。"
  },
  {
    "id": 50045,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 12,
    "conditionparams": [
      0,
      0,
      1,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50045",
    "packaged_desc": "条件 12，参数 0/0/1/0/0/1。"
  },
  {
    "id": 50046,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 11,
    "conditionparams": [
      0,
      7,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50046",
    "packaged_desc": "条件 11，参数 0/7/0/0/0/1。"
  },
  {
    "id": 50047,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 11,
    "conditionparams": [
      0,
      5,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50047",
    "packaged_desc": "条件 11，参数 0/5/0/0/0/1。"
  },
  {
    "id": 50048,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 11,
    "conditionparams": [
      0,
      6,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50048",
    "packaged_desc": "条件 11，参数 0/6/0/0/0/1。"
  },
  {
    "id": 50049,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 7,
    "conditionparams": [
      0,
      0,
      1056013,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50049",
    "packaged_desc": "条件 7，参数 0/0/1056013/0/0/1。"
  },
  {
    "id": 50050,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50050",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 50051,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50051",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 50052,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50052",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 50053,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50053",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 50054,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 24,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50054",
    "packaged_desc": "条件 24，参数 1。"
  },
  {
    "id": 50055,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      10000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50055",
    "packaged_desc": "条件 18，参数 10000。"
  },
  {
    "id": 50056,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      100000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50056",
    "packaged_desc": "条件 18，参数 100000。"
  },
  {
    "id": 50057,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      700000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50057",
    "packaged_desc": "条件 18，参数 700000。"
  },
  {
    "id": 50058,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 18,
    "conditionparams": [
      1200000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50058",
    "packaged_desc": "条件 18，参数 1200000。"
  },
  {
    "id": 50059,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50059",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50060,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        101
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50060",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50061,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        102
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50061",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50062,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        103
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50062",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50063,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        104
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50063",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50064,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        105
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 16,
    "conditionparams": [
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50064",
    "packaged_desc": "条件 16，参数 1。"
  },
  {
    "id": 50065,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      11,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50065",
    "packaged_desc": "条件 6，参数 11/0/0/0/0/1。"
  },
  {
    "id": 50066,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      0,
      0,
      100121,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50066",
    "packaged_desc": "条件 6，参数 0/0/100121/0/0/1。"
  },
  {
    "id": 50067,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 6,
    "conditionparams": [
      0,
      0,
      100127,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50067",
    "packaged_desc": "条件 6，参数 0/0/100127/0/0/1。"
  },
  {
    "id": 50068,
    "type": 1,
    "preorconditions": [],
    "preorconditionsparam": [
      []
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 9,
    "conditionparams": [
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50068",
    "packaged_desc": "条件 9，参数 0/0/0/0/0/1。"
  },
  {
    "id": 50069,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        105
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      0,
      100000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50069",
    "packaged_desc": "条件 19，参数 0/100000。"
  },
  {
    "id": 50070,
    "type": 1,
    "preorconditions": [
      4
    ],
    "preorconditionsparam": [
      [
        105
      ]
    ],
    "preconditions": [],
    "preconditionsparam": [
      []
    ],
    "condition": 19,
    "conditionparams": [
      0,
      60000
    ],
    "divided": 1,
    "maxvalue": 0,
    "desc": "condition_desc_50070",
    "packaged_desc": "条件 19，参数 0/60000。"
  }
];
