// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Dlc: BidKingRawTableRow[] = [
  {
    "id": "4464600",
    "table": "Dlc",
    "columns": [
      "4464600",
      "",
      "text_Dlc_4464600_2",
      "2",
      "[[5,7101,2],[1,2,200],[1,1,2000000]]",
      "110"
    ],
    "packaged_name": "扩展包4464600",
    "packaged_desc": "扩展包配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
