// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const ErrorCode: BidKingRawTableRow[] = [
  {
    "id": "0",
    "table": "ErrorCode",
    "columns": [
      "0",
      "text_ErrorCode_0_1",
      "",
      "CODE_0"
    ],
    "packaged_name": "错误码0",
    "packaged_desc": "错误码配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1",
    "table": "ErrorCode",
    "columns": [
      "1",
      "text_ErrorCode_1_1",
      "",
      "CODE_1"
    ],
    "packaged_name": "错误码1",
    "packaged_desc": "错误码配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "ErrorCode",
    "columns": [
      "2",
      "text_ErrorCode_2_1",
      "",
      "CODE_2"
    ],
    "packaged_name": "错误码2",
    "packaged_desc": "错误码配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "ErrorCode",
    "columns": [
      "3",
      "text_ErrorCode_3_1",
      "",
      "CODE_3"
    ],
    "packaged_name": "错误码3",
    "packaged_desc": "错误码配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "ErrorCode",
    "columns": [
      "4",
      "text_ErrorCode_4_1",
      "",
      "CODE_4"
    ],
    "packaged_name": "错误码4",
    "packaged_desc": "错误码配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "ErrorCode",
    "columns": [
      "5",
      "text_ErrorCode_5_1",
      "",
      "CODE_5"
    ],
    "packaged_name": "错误码5",
    "packaged_desc": "错误码配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "ErrorCode",
    "columns": [
      "6",
      "text_ErrorCode_6_1",
      "",
      "CODE_6"
    ],
    "packaged_name": "错误码6",
    "packaged_desc": "错误码配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "7",
    "table": "ErrorCode",
    "columns": [
      "7",
      "text_ErrorCode_7_1",
      "",
      "CODE_7"
    ],
    "packaged_name": "错误码7",
    "packaged_desc": "错误码配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "8",
    "table": "ErrorCode",
    "columns": [
      "8",
      "text_ErrorCode_8_1",
      "",
      "CODE_8"
    ],
    "packaged_name": "错误码8",
    "packaged_desc": "错误码配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "9",
    "table": "ErrorCode",
    "columns": [
      "9",
      "text_ErrorCode_9_1",
      "",
      "CODE_9"
    ],
    "packaged_name": "错误码9",
    "packaged_desc": "错误码配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "10",
    "table": "ErrorCode",
    "columns": [
      "10",
      "text_ErrorCode_10_1",
      "",
      "CODE_10"
    ],
    "packaged_name": "错误码10",
    "packaged_desc": "错误码配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "11",
    "table": "ErrorCode",
    "columns": [
      "11",
      "text_ErrorCode_11_1",
      "",
      "CODE_11"
    ],
    "packaged_name": "错误码11",
    "packaged_desc": "错误码配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "12",
    "table": "ErrorCode",
    "columns": [
      "12",
      "text_ErrorCode_12_1",
      "",
      "CODE_12"
    ],
    "packaged_name": "错误码12",
    "packaged_desc": "错误码配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "13",
    "table": "ErrorCode",
    "columns": [
      "13",
      "text_ErrorCode_13_1",
      "",
      "CODE_13"
    ],
    "packaged_name": "错误码13",
    "packaged_desc": "错误码配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "14",
    "table": "ErrorCode",
    "columns": [
      "14",
      "text_ErrorCode_14_1",
      "",
      "CODE_14"
    ],
    "packaged_name": "错误码14",
    "packaged_desc": "错误码配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "15",
    "table": "ErrorCode",
    "columns": [
      "15",
      "text_ErrorCode_15_1",
      "",
      "CODE_15"
    ],
    "packaged_name": "错误码15",
    "packaged_desc": "错误码配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "16",
    "table": "ErrorCode",
    "columns": [
      "16",
      "text_ErrorCode_16_1",
      "",
      "CODE_16"
    ],
    "packaged_name": "错误码16",
    "packaged_desc": "错误码配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "17",
    "table": "ErrorCode",
    "columns": [
      "17",
      "text_ErrorCode_17_1",
      "",
      "CODE_17"
    ],
    "packaged_name": "错误码17",
    "packaged_desc": "错误码配置行 18，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "18",
    "table": "ErrorCode",
    "columns": [
      "18",
      "text_ErrorCode_18_1",
      "",
      "CODE_18"
    ],
    "packaged_name": "错误码18",
    "packaged_desc": "错误码配置行 19，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "19",
    "table": "ErrorCode",
    "columns": [
      "19",
      "text_ErrorCode_19_1",
      "",
      "CODE_19"
    ],
    "packaged_name": "错误码19",
    "packaged_desc": "错误码配置行 20，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "20",
    "table": "ErrorCode",
    "columns": [
      "20",
      "text_ErrorCode_20_1",
      "",
      "CODE_20"
    ],
    "packaged_name": "错误码20",
    "packaged_desc": "错误码配置行 21，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "21",
    "table": "ErrorCode",
    "columns": [
      "21",
      "text_ErrorCode_21_1",
      "",
      "CODE_21"
    ],
    "packaged_name": "错误码21",
    "packaged_desc": "错误码配置行 22，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "22",
    "table": "ErrorCode",
    "columns": [
      "22",
      "text_ErrorCode_22_1",
      "",
      "CODE_22"
    ],
    "packaged_name": "错误码22",
    "packaged_desc": "错误码配置行 23，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "23",
    "table": "ErrorCode",
    "columns": [
      "23",
      "text_ErrorCode_23_1",
      "",
      "CODE_23"
    ],
    "packaged_name": "错误码23",
    "packaged_desc": "错误码配置行 24，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "24",
    "table": "ErrorCode",
    "columns": [
      "24",
      "text_ErrorCode_24_1",
      "",
      "CODE_24"
    ],
    "packaged_name": "错误码24",
    "packaged_desc": "错误码配置行 25，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "25",
    "table": "ErrorCode",
    "columns": [
      "25",
      "text_ErrorCode_25_1",
      "",
      "CODE_25"
    ],
    "packaged_name": "错误码25",
    "packaged_desc": "错误码配置行 26，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "26",
    "table": "ErrorCode",
    "columns": [
      "26",
      "text_ErrorCode_26_1",
      "",
      "CODE_26"
    ],
    "packaged_name": "错误码26",
    "packaged_desc": "错误码配置行 27，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "27",
    "table": "ErrorCode",
    "columns": [
      "27",
      "text_ErrorCode_27_1",
      "",
      "CODE_27"
    ],
    "packaged_name": "错误码27",
    "packaged_desc": "错误码配置行 28，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "28",
    "table": "ErrorCode",
    "columns": [
      "28",
      "text_ErrorCode_28_1",
      "",
      "CODE_28"
    ],
    "packaged_name": "错误码28",
    "packaged_desc": "错误码配置行 29，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "29",
    "table": "ErrorCode",
    "columns": [
      "29",
      "text_ErrorCode_29_1",
      "",
      "CODE_29"
    ],
    "packaged_name": "错误码29",
    "packaged_desc": "错误码配置行 30，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "30",
    "table": "ErrorCode",
    "columns": [
      "30",
      "text_ErrorCode_30_1",
      "",
      "CODE_30"
    ],
    "packaged_name": "错误码30",
    "packaged_desc": "错误码配置行 31，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "31",
    "table": "ErrorCode",
    "columns": [
      "31",
      "text_ErrorCode_31_1",
      "",
      "CODE_31"
    ],
    "packaged_name": "错误码31",
    "packaged_desc": "错误码配置行 32，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "32",
    "table": "ErrorCode",
    "columns": [
      "32",
      "text_ErrorCode_32_1",
      "",
      "CODE_32"
    ],
    "packaged_name": "错误码32",
    "packaged_desc": "错误码配置行 33，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "33",
    "table": "ErrorCode",
    "columns": [
      "33",
      "text_ErrorCode_33_1",
      "",
      "CODE_33"
    ],
    "packaged_name": "错误码33",
    "packaged_desc": "错误码配置行 34，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "34",
    "table": "ErrorCode",
    "columns": [
      "34",
      "text_ErrorCode_34_1",
      "",
      "CODE_34"
    ],
    "packaged_name": "错误码34",
    "packaged_desc": "错误码配置行 35，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "35",
    "table": "ErrorCode",
    "columns": [
      "35",
      "text_ErrorCode_35_1",
      "",
      "CODE_35"
    ],
    "packaged_name": "错误码35",
    "packaged_desc": "错误码配置行 36，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "36",
    "table": "ErrorCode",
    "columns": [
      "36",
      "text_ErrorCode_36_1",
      "",
      "CODE_36"
    ],
    "packaged_name": "错误码36",
    "packaged_desc": "错误码配置行 37，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "37",
    "table": "ErrorCode",
    "columns": [
      "37",
      "text_ErrorCode_37_1",
      "",
      "CODE_37"
    ],
    "packaged_name": "错误码37",
    "packaged_desc": "错误码配置行 38，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "38",
    "table": "ErrorCode",
    "columns": [
      "38",
      "text_ErrorCode_38_1",
      "",
      "CODE_38"
    ],
    "packaged_name": "错误码38",
    "packaged_desc": "错误码配置行 39，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "39",
    "table": "ErrorCode",
    "columns": [
      "39",
      "text_ErrorCode_39_1",
      "",
      "CODE_39"
    ],
    "packaged_name": "错误码39",
    "packaged_desc": "错误码配置行 40，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "40",
    "table": "ErrorCode",
    "columns": [
      "40",
      "text_ErrorCode_40_1",
      "",
      "CODE_40"
    ],
    "packaged_name": "错误码40",
    "packaged_desc": "错误码配置行 41，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "41",
    "table": "ErrorCode",
    "columns": [
      "41",
      "text_ErrorCode_41_1",
      "",
      "CODE_41"
    ],
    "packaged_name": "错误码41",
    "packaged_desc": "错误码配置行 42，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "42",
    "table": "ErrorCode",
    "columns": [
      "42",
      "text_ErrorCode_42_1",
      "",
      "CODE_42"
    ],
    "packaged_name": "错误码42",
    "packaged_desc": "错误码配置行 43，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "43",
    "table": "ErrorCode",
    "columns": [
      "43",
      "text_ErrorCode_43_1",
      "",
      "CODE_43"
    ],
    "packaged_name": "错误码43",
    "packaged_desc": "错误码配置行 44，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "44",
    "table": "ErrorCode",
    "columns": [
      "44",
      "text_ErrorCode_44_1",
      "",
      "CODE_44"
    ],
    "packaged_name": "错误码44",
    "packaged_desc": "错误码配置行 45，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "45",
    "table": "ErrorCode",
    "columns": [
      "45",
      "text_ErrorCode_45_1",
      "",
      "CODE_45"
    ],
    "packaged_name": "错误码45",
    "packaged_desc": "错误码配置行 46，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "46",
    "table": "ErrorCode",
    "columns": [
      "46",
      "text_ErrorCode_46_1",
      "",
      "CODE_46"
    ],
    "packaged_name": "错误码46",
    "packaged_desc": "错误码配置行 47，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "47",
    "table": "ErrorCode",
    "columns": [
      "47",
      "text_ErrorCode_47_1",
      "",
      "CODE_47"
    ],
    "packaged_name": "错误码47",
    "packaged_desc": "错误码配置行 48，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "48",
    "table": "ErrorCode",
    "columns": [
      "48",
      "text_ErrorCode_48_1",
      "",
      "CODE_48"
    ],
    "packaged_name": "错误码48",
    "packaged_desc": "错误码配置行 49，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "49",
    "table": "ErrorCode",
    "columns": [
      "49",
      "text_ErrorCode_49_1",
      "",
      "CODE_49"
    ],
    "packaged_name": "错误码49",
    "packaged_desc": "错误码配置行 50，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "50",
    "table": "ErrorCode",
    "columns": [
      "50",
      "text_ErrorCode_50_1",
      "",
      "CODE_50"
    ],
    "packaged_name": "错误码50",
    "packaged_desc": "错误码配置行 51，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "51",
    "table": "ErrorCode",
    "columns": [
      "51",
      "text_ErrorCode_51_1",
      "",
      "CODE_51"
    ],
    "packaged_name": "错误码51",
    "packaged_desc": "错误码配置行 52，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "52",
    "table": "ErrorCode",
    "columns": [
      "52",
      "text_ErrorCode_52_1",
      "",
      "CODE_52"
    ],
    "packaged_name": "错误码52",
    "packaged_desc": "错误码配置行 53，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "53",
    "table": "ErrorCode",
    "columns": [
      "53",
      "text_ErrorCode_53_1",
      "",
      "CODE_53"
    ],
    "packaged_name": "错误码53",
    "packaged_desc": "错误码配置行 54，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "54",
    "table": "ErrorCode",
    "columns": [
      "54",
      "text_ErrorCode_54_1",
      "",
      "CODE_54"
    ],
    "packaged_name": "错误码54",
    "packaged_desc": "错误码配置行 55，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "55",
    "table": "ErrorCode",
    "columns": [
      "55",
      "text_ErrorCode_55_1",
      "",
      "CODE_55"
    ],
    "packaged_name": "错误码55",
    "packaged_desc": "错误码配置行 56，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "56",
    "table": "ErrorCode",
    "columns": [
      "56",
      "text_ErrorCode_56_1",
      "",
      "CODE_56"
    ],
    "packaged_name": "错误码56",
    "packaged_desc": "错误码配置行 57，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "57",
    "table": "ErrorCode",
    "columns": [
      "57",
      "text_ErrorCode_57_1",
      "",
      "CODE_57"
    ],
    "packaged_name": "错误码57",
    "packaged_desc": "错误码配置行 58，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "58",
    "table": "ErrorCode",
    "columns": [
      "58",
      "text_ErrorCode_58_1",
      "",
      "CODE_58"
    ],
    "packaged_name": "错误码58",
    "packaged_desc": "错误码配置行 59，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "59",
    "table": "ErrorCode",
    "columns": [
      "59",
      "text_ErrorCode_59_1",
      "",
      "CODE_59"
    ],
    "packaged_name": "错误码59",
    "packaged_desc": "错误码配置行 60，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "60",
    "table": "ErrorCode",
    "columns": [
      "60",
      "text_ErrorCode_60_1",
      "",
      "CODE_60"
    ],
    "packaged_name": "错误码60",
    "packaged_desc": "错误码配置行 61，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "61",
    "table": "ErrorCode",
    "columns": [
      "61",
      "text_ErrorCode_61_1",
      "",
      "CODE_61"
    ],
    "packaged_name": "错误码61",
    "packaged_desc": "错误码配置行 62，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "62",
    "table": "ErrorCode",
    "columns": [
      "62",
      "text_ErrorCode_62_1",
      "",
      "CODE_62"
    ],
    "packaged_name": "错误码62",
    "packaged_desc": "错误码配置行 63，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "63",
    "table": "ErrorCode",
    "columns": [
      "63",
      "text_ErrorCode_63_1",
      "",
      "CODE_63"
    ],
    "packaged_name": "错误码63",
    "packaged_desc": "错误码配置行 64，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "64",
    "table": "ErrorCode",
    "columns": [
      "64",
      "text_ErrorCode_64_1",
      "",
      "CODE_64"
    ],
    "packaged_name": "错误码64",
    "packaged_desc": "错误码配置行 65，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "65",
    "table": "ErrorCode",
    "columns": [
      "65",
      "text_ErrorCode_65_1",
      "",
      "CODE_65"
    ],
    "packaged_name": "错误码65",
    "packaged_desc": "错误码配置行 66，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "66",
    "table": "ErrorCode",
    "columns": [
      "66",
      "text_ErrorCode_66_1",
      "",
      "CODE_66"
    ],
    "packaged_name": "错误码66",
    "packaged_desc": "错误码配置行 67，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "67",
    "table": "ErrorCode",
    "columns": [
      "67",
      "text_ErrorCode_67_1",
      "",
      "CODE_67"
    ],
    "packaged_name": "错误码67",
    "packaged_desc": "错误码配置行 68，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "68",
    "table": "ErrorCode",
    "columns": [
      "68",
      "text_ErrorCode_68_1",
      "",
      "CODE_68"
    ],
    "packaged_name": "错误码68",
    "packaged_desc": "错误码配置行 69，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "70",
    "table": "ErrorCode",
    "columns": [
      "70",
      "text_ErrorCode_70_1",
      "",
      "CODE_70"
    ],
    "packaged_name": "错误码70",
    "packaged_desc": "错误码配置行 70，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "71",
    "table": "ErrorCode",
    "columns": [
      "71",
      "text_ErrorCode_71_1",
      "",
      "CODE_71"
    ],
    "packaged_name": "错误码71",
    "packaged_desc": "错误码配置行 71，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "72",
    "table": "ErrorCode",
    "columns": [
      "72",
      "text_ErrorCode_72_1",
      "",
      "CODE_72"
    ],
    "packaged_name": "错误码72",
    "packaged_desc": "错误码配置行 72，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "73",
    "table": "ErrorCode",
    "columns": [
      "73",
      "text_ErrorCode_73_1",
      "",
      "CODE_73"
    ],
    "packaged_name": "错误码73",
    "packaged_desc": "错误码配置行 73，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "74",
    "table": "ErrorCode",
    "columns": [
      "74",
      "text_ErrorCode_74_1",
      "",
      "CODE_74"
    ],
    "packaged_name": "错误码74",
    "packaged_desc": "错误码配置行 74，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "79",
    "table": "ErrorCode",
    "columns": [
      "79",
      "text_ErrorCode_79_1",
      "",
      "CODE_79"
    ],
    "packaged_name": "错误码79",
    "packaged_desc": "错误码配置行 75，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "80",
    "table": "ErrorCode",
    "columns": [
      "80",
      "text_ErrorCode_80_1",
      "",
      "CODE_80"
    ],
    "packaged_name": "错误码80",
    "packaged_desc": "错误码配置行 76，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "102",
    "table": "ErrorCode",
    "columns": [
      "102",
      "text_ErrorCode_102_1",
      "",
      "CODE_102"
    ],
    "packaged_name": "错误码102",
    "packaged_desc": "错误码配置行 77，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "103",
    "table": "ErrorCode",
    "columns": [
      "103",
      "text_ErrorCode_103_1",
      "",
      "CODE_103"
    ],
    "packaged_name": "错误码103",
    "packaged_desc": "错误码配置行 78，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "104",
    "table": "ErrorCode",
    "columns": [
      "104",
      "text_ErrorCode_104_1",
      "",
      "CODE_104"
    ],
    "packaged_name": "错误码104",
    "packaged_desc": "错误码配置行 79，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "105",
    "table": "ErrorCode",
    "columns": [
      "105",
      "text_ErrorCode_105_1",
      "",
      "CODE_105"
    ],
    "packaged_name": "错误码105",
    "packaged_desc": "错误码配置行 80，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "106",
    "table": "ErrorCode",
    "columns": [
      "106",
      "text_ErrorCode_106_1",
      "",
      "CODE_106"
    ],
    "packaged_name": "错误码106",
    "packaged_desc": "错误码配置行 81，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "107",
    "table": "ErrorCode",
    "columns": [
      "107",
      "text_ErrorCode_107_1",
      "",
      "CODE_107"
    ],
    "packaged_name": "错误码107",
    "packaged_desc": "错误码配置行 82，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "108",
    "table": "ErrorCode",
    "columns": [
      "108",
      "text_ErrorCode_108_1",
      "",
      "CODE_108"
    ],
    "packaged_name": "错误码108",
    "packaged_desc": "错误码配置行 83，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "109",
    "table": "ErrorCode",
    "columns": [
      "109",
      "text_ErrorCode_109_1",
      "",
      "CODE_109"
    ],
    "packaged_name": "错误码109",
    "packaged_desc": "错误码配置行 84，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
