// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const ExchangeRestock: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "Exchange_Restock",
    "columns": [
      "1",
      "",
      "",
      ""
    ],
    "packaged_name": "兑换刷新1",
    "packaged_desc": "兑换刷新配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "Exchange_Restock",
    "columns": [
      "2",
      "",
      "",
      ""
    ],
    "packaged_name": "兑换刷新2",
    "packaged_desc": "兑换刷新配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "Exchange_Restock",
    "columns": [
      "4",
      "",
      "",
      ""
    ],
    "packaged_name": "兑换刷新4",
    "packaged_desc": "兑换刷新配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "Exchange_Restock",
    "columns": [
      "5",
      "",
      "",
      ""
    ],
    "packaged_name": "兑换刷新5",
    "packaged_desc": "兑换刷新配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
