// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const GiftPackage: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "GiftPackage",
    "columns": [
      "1",
      "",
      "text_GiftPackage_1_2",
      "1",
      "text_GiftPackage_1_4",
      "",
      "1",
      "[[1,2,60]]"
    ],
    "packaged_name": "礼包1",
    "packaged_desc": "礼包配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "GiftPackage",
    "columns": [
      "2",
      "",
      "text_GiftPackage_2_2",
      "1",
      "text_GiftPackage_2_4",
      "text_GiftPackage_2_5",
      "2",
      "[[1,2,320]]"
    ],
    "packaged_name": "礼包2",
    "packaged_desc": "礼包配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "GiftPackage",
    "columns": [
      "3",
      "",
      "text_GiftPackage_3_2",
      "1",
      "text_GiftPackage_3_4",
      "text_GiftPackage_3_5",
      "3",
      "[[1,2,750]]"
    ],
    "packaged_name": "礼包3",
    "packaged_desc": "礼包配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "GiftPackage",
    "columns": [
      "4",
      "",
      "text_GiftPackage_4_2",
      "1",
      "text_GiftPackage_4_4",
      "text_GiftPackage_4_5",
      "4",
      "[[1,2,1480]]"
    ],
    "packaged_name": "礼包4",
    "packaged_desc": "礼包配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "GiftPackage",
    "columns": [
      "5",
      "",
      "text_GiftPackage_5_2",
      "1",
      "text_GiftPackage_5_4",
      "text_GiftPackage_5_5",
      "5",
      "[[1,2,3950]]"
    ],
    "packaged_name": "礼包5",
    "packaged_desc": "礼包配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "GiftPackage",
    "columns": [
      "6",
      "",
      "text_GiftPackage_6_2",
      "1",
      "text_GiftPackage_6_4",
      "text_GiftPackage_6_5",
      "6",
      "[[1,2,8100]]"
    ],
    "packaged_name": "礼包6",
    "packaged_desc": "礼包配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
