// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const GuildResources: BidKingRawTableRow[] = [
  {
    "id": "1001",
    "table": "GuildResources",
    "columns": [
      "1001",
      "text_GuildResources_1001_1",
      "1",
      "",
      "huizhang01"
    ],
    "packaged_name": "协会资源1001",
    "packaged_desc": "协会资源配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002",
    "table": "GuildResources",
    "columns": [
      "1002",
      "text_GuildResources_1002_1",
      "1",
      "",
      "huizhang02"
    ],
    "packaged_name": "协会资源1002",
    "packaged_desc": "协会资源配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003",
    "table": "GuildResources",
    "columns": [
      "1003",
      "text_GuildResources_1003_1",
      "1",
      "",
      "huizhang03"
    ],
    "packaged_name": "协会资源1003",
    "packaged_desc": "协会资源配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1004",
    "table": "GuildResources",
    "columns": [
      "1004",
      "text_GuildResources_1004_1",
      "1",
      "",
      "huizhang04"
    ],
    "packaged_name": "协会资源1004",
    "packaged_desc": "协会资源配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1005",
    "table": "GuildResources",
    "columns": [
      "1005",
      "text_GuildResources_1005_1",
      "1",
      "",
      "huizhang05"
    ],
    "packaged_name": "协会资源1005",
    "packaged_desc": "协会资源配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1006",
    "table": "GuildResources",
    "columns": [
      "1006",
      "text_GuildResources_1006_1",
      "1",
      "",
      "huizhang06"
    ],
    "packaged_name": "协会资源1006",
    "packaged_desc": "协会资源配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1007",
    "table": "GuildResources",
    "columns": [
      "1007",
      "text_GuildResources_1007_1",
      "1",
      "",
      "huizhang07"
    ],
    "packaged_name": "协会资源1007",
    "packaged_desc": "协会资源配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1008",
    "table": "GuildResources",
    "columns": [
      "1008",
      "text_GuildResources_1008_1",
      "1",
      "",
      "huizhang08"
    ],
    "packaged_name": "协会资源1008",
    "packaged_desc": "协会资源配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2001",
    "table": "GuildResources",
    "columns": [
      "2001",
      "text_GuildResources_2001_1",
      "2",
      "guild_member_title_01",
      ""
    ],
    "packaged_name": "协会资源2001",
    "packaged_desc": "协会资源配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2002",
    "table": "GuildResources",
    "columns": [
      "2002",
      "text_GuildResources_2002_1",
      "2",
      "guild_member_title_02",
      ""
    ],
    "packaged_name": "协会资源2002",
    "packaged_desc": "协会资源配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2003",
    "table": "GuildResources",
    "columns": [
      "2003",
      "text_GuildResources_2003_1",
      "2",
      "guild_member_title_03",
      ""
    ],
    "packaged_name": "协会资源2003",
    "packaged_desc": "协会资源配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2004",
    "table": "GuildResources",
    "columns": [
      "2004",
      "text_GuildResources_2004_1",
      "2",
      "guild_member_title_04",
      ""
    ],
    "packaged_name": "协会资源2004",
    "packaged_desc": "协会资源配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2005",
    "table": "GuildResources",
    "columns": [
      "2005",
      "text_GuildResources_2005_1",
      "2",
      "guild_member_title_05",
      ""
    ],
    "packaged_name": "协会资源2005",
    "packaged_desc": "协会资源配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2006",
    "table": "GuildResources",
    "columns": [
      "2006",
      "text_GuildResources_2006_1",
      "2",
      "guild_member_title_06",
      ""
    ],
    "packaged_name": "协会资源2006",
    "packaged_desc": "协会资源配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2007",
    "table": "GuildResources",
    "columns": [
      "2007",
      "text_GuildResources_2007_1",
      "2",
      "guild_member_title_07",
      ""
    ],
    "packaged_name": "协会资源2007",
    "packaged_desc": "协会资源配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2008",
    "table": "GuildResources",
    "columns": [
      "2008",
      "text_GuildResources_2008_1",
      "2",
      "guild_member_title_08",
      ""
    ],
    "packaged_name": "协会资源2008",
    "packaged_desc": "协会资源配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2009",
    "table": "GuildResources",
    "columns": [
      "2009",
      "text_GuildResources_2009_1",
      "2",
      "guild_member_title_09",
      ""
    ],
    "packaged_name": "协会资源2009",
    "packaged_desc": "协会资源配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
