// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const GuildArea: BidKingRawTableRow[] = [
  {
    "id": "101",
    "table": "GuildArea",
    "columns": [
      "101",
      "text_GuildArea_101_1",
      "area_name_101",
      "1001"
    ],
    "packaged_name": "协会地区101",
    "packaged_desc": "协会地区配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "102",
    "table": "GuildArea",
    "columns": [
      "102",
      "text_GuildArea_102_1",
      "area_name_102",
      "1004"
    ],
    "packaged_name": "协会地区102",
    "packaged_desc": "协会地区配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "103",
    "table": "GuildArea",
    "columns": [
      "103",
      "text_GuildArea_103_1",
      "area_name_103",
      "1005"
    ],
    "packaged_name": "协会地区103",
    "packaged_desc": "协会地区配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "104",
    "table": "GuildArea",
    "columns": [
      "104",
      "text_GuildArea_104_1",
      "area_name_104",
      "1005"
    ],
    "packaged_name": "协会地区104",
    "packaged_desc": "协会地区配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "105",
    "table": "GuildArea",
    "columns": [
      "105",
      "text_GuildArea_105_1",
      "area_name_105",
      "1002"
    ],
    "packaged_name": "协会地区105",
    "packaged_desc": "协会地区配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "106",
    "table": "GuildArea",
    "columns": [
      "106",
      "text_GuildArea_106_1",
      "area_name_106",
      "1006"
    ],
    "packaged_name": "协会地区106",
    "packaged_desc": "协会地区配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "107",
    "table": "GuildArea",
    "columns": [
      "107",
      "text_GuildArea_107_1",
      "area_name_107",
      "1005"
    ],
    "packaged_name": "协会地区107",
    "packaged_desc": "协会地区配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "108",
    "table": "GuildArea",
    "columns": [
      "108",
      "text_GuildArea_108_1",
      "area_name_108",
      "1005"
    ],
    "packaged_name": "协会地区108",
    "packaged_desc": "协会地区配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "109",
    "table": "GuildArea",
    "columns": [
      "109",
      "text_GuildArea_109_1",
      "area_name_109",
      "1007"
    ],
    "packaged_name": "协会地区109",
    "packaged_desc": "协会地区配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "110",
    "table": "GuildArea",
    "columns": [
      "110",
      "text_GuildArea_110_1",
      "area_name_110",
      "1002"
    ],
    "packaged_name": "协会地区110",
    "packaged_desc": "协会地区配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "111",
    "table": "GuildArea",
    "columns": [
      "111",
      "text_GuildArea_111_1",
      "area_name_111",
      "1007"
    ],
    "packaged_name": "协会地区111",
    "packaged_desc": "协会地区配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "112",
    "table": "GuildArea",
    "columns": [
      "112",
      "text_GuildArea_112_1",
      "area_name_112",
      "1007"
    ],
    "packaged_name": "协会地区112",
    "packaged_desc": "协会地区配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "113",
    "table": "GuildArea",
    "columns": [
      "113",
      "text_GuildArea_113_1",
      "area_name_113",
      "1008"
    ],
    "packaged_name": "协会地区113",
    "packaged_desc": "协会地区配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "114",
    "table": "GuildArea",
    "columns": [
      "114",
      "text_GuildArea_114_1",
      "area_name_114",
      "1006"
    ],
    "packaged_name": "协会地区114",
    "packaged_desc": "协会地区配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "115",
    "table": "GuildArea",
    "columns": [
      "115",
      "text_GuildArea_115_1",
      "area_name_115",
      "1006"
    ],
    "packaged_name": "协会地区115",
    "packaged_desc": "协会地区配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "116",
    "table": "GuildArea",
    "columns": [
      "116",
      "text_GuildArea_116_1",
      "area_name_116",
      "1003"
    ],
    "packaged_name": "协会地区116",
    "packaged_desc": "协会地区配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "201",
    "table": "GuildArea",
    "columns": [
      "201",
      "text_GuildArea_201_1",
      "area_name_201",
      "1003"
    ],
    "packaged_name": "协会地区201",
    "packaged_desc": "协会地区配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "202",
    "table": "GuildArea",
    "columns": [
      "202",
      "text_GuildArea_202_1",
      "area_name_202",
      "1004"
    ],
    "packaged_name": "协会地区202",
    "packaged_desc": "协会地区配置行 18，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "203",
    "table": "GuildArea",
    "columns": [
      "203",
      "text_GuildArea_203_1",
      "area_name_203",
      "1004"
    ],
    "packaged_name": "协会地区203",
    "packaged_desc": "协会地区配置行 19，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "204",
    "table": "GuildArea",
    "columns": [
      "204",
      "text_GuildArea_204_1",
      "area_name_204",
      "1004"
    ],
    "packaged_name": "协会地区204",
    "packaged_desc": "协会地区配置行 20，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "205",
    "table": "GuildArea",
    "columns": [
      "205",
      "text_GuildArea_205_1",
      "area_name_205",
      "1004"
    ],
    "packaged_name": "协会地区205",
    "packaged_desc": "协会地区配置行 21，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "206",
    "table": "GuildArea",
    "columns": [
      "206",
      "text_GuildArea_206_1",
      "area_name_206",
      "1005"
    ],
    "packaged_name": "协会地区206",
    "packaged_desc": "协会地区配置行 22，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "207",
    "table": "GuildArea",
    "columns": [
      "207",
      "text_GuildArea_207_1",
      "area_name_207",
      "1008"
    ],
    "packaged_name": "协会地区207",
    "packaged_desc": "协会地区配置行 23，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "208",
    "table": "GuildArea",
    "columns": [
      "208",
      "text_GuildArea_208_1",
      "area_name_208",
      "1002"
    ],
    "packaged_name": "协会地区208",
    "packaged_desc": "协会地区配置行 24，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "209",
    "table": "GuildArea",
    "columns": [
      "209",
      "text_GuildArea_209_1",
      "area_name_209",
      "1008"
    ],
    "packaged_name": "协会地区209",
    "packaged_desc": "协会地区配置行 25，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "210",
    "table": "GuildArea",
    "columns": [
      "210",
      "text_GuildArea_210_1",
      "area_name_210",
      "1002"
    ],
    "packaged_name": "协会地区210",
    "packaged_desc": "协会地区配置行 26，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "211",
    "table": "GuildArea",
    "columns": [
      "211",
      "text_GuildArea_211_1",
      "area_name_211",
      "1006"
    ],
    "packaged_name": "协会地区211",
    "packaged_desc": "协会地区配置行 27，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "212",
    "table": "GuildArea",
    "columns": [
      "212",
      "text_GuildArea_212_1",
      "area_name_212",
      "1002"
    ],
    "packaged_name": "协会地区212",
    "packaged_desc": "协会地区配置行 28，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "213",
    "table": "GuildArea",
    "columns": [
      "213",
      "text_GuildArea_213_1",
      "area_name_213",
      "1004"
    ],
    "packaged_name": "协会地区213",
    "packaged_desc": "协会地区配置行 29，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "214",
    "table": "GuildArea",
    "columns": [
      "214",
      "text_GuildArea_214_1",
      "area_name_214",
      "1008"
    ],
    "packaged_name": "协会地区214",
    "packaged_desc": "协会地区配置行 30，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "215",
    "table": "GuildArea",
    "columns": [
      "215",
      "text_GuildArea_215_1",
      "area_name_215",
      "1008"
    ],
    "packaged_name": "协会地区215",
    "packaged_desc": "协会地区配置行 31，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "216",
    "table": "GuildArea",
    "columns": [
      "216",
      "text_GuildArea_216_1",
      "area_name_216",
      "1007"
    ],
    "packaged_name": "协会地区216",
    "packaged_desc": "协会地区配置行 32，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "217",
    "table": "GuildArea",
    "columns": [
      "217",
      "text_GuildArea_217_1",
      "area_name_217",
      "1008"
    ],
    "packaged_name": "协会地区217",
    "packaged_desc": "协会地区配置行 33，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "301",
    "table": "GuildArea",
    "columns": [
      "301",
      "text_GuildArea_301_1",
      "area_name_301",
      "1007"
    ],
    "packaged_name": "协会地区301",
    "packaged_desc": "协会地区配置行 34，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "302",
    "table": "GuildArea",
    "columns": [
      "302",
      "text_GuildArea_302_1",
      "area_name_302",
      "1005"
    ],
    "packaged_name": "协会地区302",
    "packaged_desc": "协会地区配置行 35，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "303",
    "table": "GuildArea",
    "columns": [
      "303",
      "text_GuildArea_303_1",
      "area_name_303",
      "1002"
    ],
    "packaged_name": "协会地区303",
    "packaged_desc": "协会地区配置行 36，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "304",
    "table": "GuildArea",
    "columns": [
      "304",
      "text_GuildArea_304_1",
      "area_name_304",
      "1002"
    ],
    "packaged_name": "协会地区304",
    "packaged_desc": "协会地区配置行 37，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "305",
    "table": "GuildArea",
    "columns": [
      "305",
      "text_GuildArea_305_1",
      "area_name_305",
      "1007"
    ],
    "packaged_name": "协会地区305",
    "packaged_desc": "协会地区配置行 38，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "306",
    "table": "GuildArea",
    "columns": [
      "306",
      "text_GuildArea_306_1",
      "area_name_306",
      "1003"
    ],
    "packaged_name": "协会地区306",
    "packaged_desc": "协会地区配置行 39，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "307",
    "table": "GuildArea",
    "columns": [
      "307",
      "text_GuildArea_307_1",
      "area_name_307",
      "1003"
    ],
    "packaged_name": "协会地区307",
    "packaged_desc": "协会地区配置行 40，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "308",
    "table": "GuildArea",
    "columns": [
      "308",
      "text_GuildArea_308_1",
      "area_name_308",
      "1001"
    ],
    "packaged_name": "协会地区308",
    "packaged_desc": "协会地区配置行 41，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "309",
    "table": "GuildArea",
    "columns": [
      "309",
      "text_GuildArea_309_1",
      "area_name_309",
      "1002"
    ],
    "packaged_name": "协会地区309",
    "packaged_desc": "协会地区配置行 42，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "310",
    "table": "GuildArea",
    "columns": [
      "310",
      "text_GuildArea_310_1",
      "area_name_310",
      "1003"
    ],
    "packaged_name": "协会地区310",
    "packaged_desc": "协会地区配置行 43，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "311",
    "table": "GuildArea",
    "columns": [
      "311",
      "text_GuildArea_311_1",
      "area_name_311",
      "1002"
    ],
    "packaged_name": "协会地区311",
    "packaged_desc": "协会地区配置行 44，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "312",
    "table": "GuildArea",
    "columns": [
      "312",
      "text_GuildArea_312_1",
      "area_name_312",
      "1002"
    ],
    "packaged_name": "协会地区312",
    "packaged_desc": "协会地区配置行 45，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "313",
    "table": "GuildArea",
    "columns": [
      "313",
      "text_GuildArea_313_1",
      "area_name_313",
      "1005"
    ],
    "packaged_name": "协会地区313",
    "packaged_desc": "协会地区配置行 46，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "314",
    "table": "GuildArea",
    "columns": [
      "314",
      "text_GuildArea_314_1",
      "area_name_314",
      "1007"
    ],
    "packaged_name": "协会地区314",
    "packaged_desc": "协会地区配置行 47，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "315",
    "table": "GuildArea",
    "columns": [
      "315",
      "text_GuildArea_315_1",
      "area_name_315",
      "1004"
    ],
    "packaged_name": "协会地区315",
    "packaged_desc": "协会地区配置行 48，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "316",
    "table": "GuildArea",
    "columns": [
      "316",
      "text_GuildArea_316_1",
      "area_name_316",
      "1008"
    ],
    "packaged_name": "协会地区316",
    "packaged_desc": "协会地区配置行 49，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "317",
    "table": "GuildArea",
    "columns": [
      "317",
      "text_GuildArea_317_1",
      "area_name_317",
      "1002"
    ],
    "packaged_name": "协会地区317",
    "packaged_desc": "协会地区配置行 50，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "401",
    "table": "GuildArea",
    "columns": [
      "401",
      "text_GuildArea_401_1",
      "area_name_401",
      "1005"
    ],
    "packaged_name": "协会地区401",
    "packaged_desc": "协会地区配置行 51，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "402",
    "table": "GuildArea",
    "columns": [
      "402",
      "text_GuildArea_402_1",
      "area_name_402",
      "1006"
    ],
    "packaged_name": "协会地区402",
    "packaged_desc": "协会地区配置行 52，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "403",
    "table": "GuildArea",
    "columns": [
      "403",
      "text_GuildArea_403_1",
      "area_name_403",
      "1004"
    ],
    "packaged_name": "协会地区403",
    "packaged_desc": "协会地区配置行 53，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "404",
    "table": "GuildArea",
    "columns": [
      "404",
      "text_GuildArea_404_1",
      "area_name_404",
      "1004"
    ],
    "packaged_name": "协会地区404",
    "packaged_desc": "协会地区配置行 54，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "405",
    "table": "GuildArea",
    "columns": [
      "405",
      "text_GuildArea_405_1",
      "area_name_405",
      "1008"
    ],
    "packaged_name": "协会地区405",
    "packaged_desc": "协会地区配置行 55，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "406",
    "table": "GuildArea",
    "columns": [
      "406",
      "text_GuildArea_406_1",
      "area_name_406",
      "1006"
    ],
    "packaged_name": "协会地区406",
    "packaged_desc": "协会地区配置行 56，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "407",
    "table": "GuildArea",
    "columns": [
      "407",
      "text_GuildArea_407_1",
      "area_name_407",
      "1005"
    ],
    "packaged_name": "协会地区407",
    "packaged_desc": "协会地区配置行 57，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "408",
    "table": "GuildArea",
    "columns": [
      "408",
      "text_GuildArea_408_1",
      "area_name_408",
      "1002"
    ],
    "packaged_name": "协会地区408",
    "packaged_desc": "协会地区配置行 58，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "409",
    "table": "GuildArea",
    "columns": [
      "409",
      "text_GuildArea_409_1",
      "area_name_409",
      "1004"
    ],
    "packaged_name": "协会地区409",
    "packaged_desc": "协会地区配置行 59，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "410",
    "table": "GuildArea",
    "columns": [
      "410",
      "text_GuildArea_410_1",
      "area_name_410",
      "1005"
    ],
    "packaged_name": "协会地区410",
    "packaged_desc": "协会地区配置行 60，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "411",
    "table": "GuildArea",
    "columns": [
      "411",
      "text_GuildArea_411_1",
      "area_name_411",
      "1005"
    ],
    "packaged_name": "协会地区411",
    "packaged_desc": "协会地区配置行 61，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "412",
    "table": "GuildArea",
    "columns": [
      "412",
      "text_GuildArea_412_1",
      "area_name_412",
      "1002"
    ],
    "packaged_name": "协会地区412",
    "packaged_desc": "协会地区配置行 62，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "413",
    "table": "GuildArea",
    "columns": [
      "413",
      "text_GuildArea_413_1",
      "area_name_413",
      "1003"
    ],
    "packaged_name": "协会地区413",
    "packaged_desc": "协会地区配置行 63，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "414",
    "table": "GuildArea",
    "columns": [
      "414",
      "text_GuildArea_414_1",
      "area_name_414",
      "1003"
    ],
    "packaged_name": "协会地区414",
    "packaged_desc": "协会地区配置行 64，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "415",
    "table": "GuildArea",
    "columns": [
      "415",
      "text_GuildArea_415_1",
      "area_name_415",
      "1008"
    ],
    "packaged_name": "协会地区415",
    "packaged_desc": "协会地区配置行 65，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "416",
    "table": "GuildArea",
    "columns": [
      "416",
      "text_GuildArea_416_1",
      "area_name_416",
      "1008"
    ],
    "packaged_name": "协会地区416",
    "packaged_desc": "协会地区配置行 66，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "417",
    "table": "GuildArea",
    "columns": [
      "417",
      "text_GuildArea_417_1",
      "area_name_417",
      "1004"
    ],
    "packaged_name": "协会地区417",
    "packaged_desc": "协会地区配置行 67，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "501",
    "table": "GuildArea",
    "columns": [
      "501",
      "text_GuildArea_501_1",
      "area_name_501",
      "1006"
    ],
    "packaged_name": "协会地区501",
    "packaged_desc": "协会地区配置行 68，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "502",
    "table": "GuildArea",
    "columns": [
      "502",
      "text_GuildArea_502_1",
      "area_name_502",
      "1002"
    ],
    "packaged_name": "协会地区502",
    "packaged_desc": "协会地区配置行 69，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "503",
    "table": "GuildArea",
    "columns": [
      "503",
      "text_GuildArea_503_1",
      "area_name_503",
      "1007"
    ],
    "packaged_name": "协会地区503",
    "packaged_desc": "协会地区配置行 70，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "504",
    "table": "GuildArea",
    "columns": [
      "504",
      "text_GuildArea_504_1",
      "area_name_504",
      "1002"
    ],
    "packaged_name": "协会地区504",
    "packaged_desc": "协会地区配置行 71，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "505",
    "table": "GuildArea",
    "columns": [
      "505",
      "text_GuildArea_505_1",
      "area_name_505",
      "1005"
    ],
    "packaged_name": "协会地区505",
    "packaged_desc": "协会地区配置行 72，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "506",
    "table": "GuildArea",
    "columns": [
      "506",
      "text_GuildArea_506_1",
      "area_name_506",
      "1005"
    ],
    "packaged_name": "协会地区506",
    "packaged_desc": "协会地区配置行 73，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "507",
    "table": "GuildArea",
    "columns": [
      "507",
      "text_GuildArea_507_1",
      "area_name_507",
      "1002"
    ],
    "packaged_name": "协会地区507",
    "packaged_desc": "协会地区配置行 74，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "508",
    "table": "GuildArea",
    "columns": [
      "508",
      "text_GuildArea_508_1",
      "area_name_508",
      "1006"
    ],
    "packaged_name": "协会地区508",
    "packaged_desc": "协会地区配置行 75，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "509",
    "table": "GuildArea",
    "columns": [
      "509",
      "text_GuildArea_509_1",
      "area_name_509",
      "1004"
    ],
    "packaged_name": "协会地区509",
    "packaged_desc": "协会地区配置行 76，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "510",
    "table": "GuildArea",
    "columns": [
      "510",
      "text_GuildArea_510_1",
      "area_name_510",
      "1002"
    ],
    "packaged_name": "协会地区510",
    "packaged_desc": "协会地区配置行 77，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "511",
    "table": "GuildArea",
    "columns": [
      "511",
      "text_GuildArea_511_1",
      "area_name_511",
      "1005"
    ],
    "packaged_name": "协会地区511",
    "packaged_desc": "协会地区配置行 78，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "512",
    "table": "GuildArea",
    "columns": [
      "512",
      "text_GuildArea_512_1",
      "area_name_512",
      "1007"
    ],
    "packaged_name": "协会地区512",
    "packaged_desc": "协会地区配置行 79，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "513",
    "table": "GuildArea",
    "columns": [
      "513",
      "text_GuildArea_513_1",
      "area_name_513",
      "1007"
    ],
    "packaged_name": "协会地区513",
    "packaged_desc": "协会地区配置行 80，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "514",
    "table": "GuildArea",
    "columns": [
      "514",
      "text_GuildArea_514_1",
      "area_name_514",
      "1006"
    ],
    "packaged_name": "协会地区514",
    "packaged_desc": "协会地区配置行 81，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "515",
    "table": "GuildArea",
    "columns": [
      "515",
      "text_GuildArea_515_1",
      "area_name_515",
      "1005"
    ],
    "packaged_name": "协会地区515",
    "packaged_desc": "协会地区配置行 82，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "601",
    "table": "GuildArea",
    "columns": [
      "601",
      "text_GuildArea_601_1",
      "area_name_601",
      "1008"
    ],
    "packaged_name": "协会地区601",
    "packaged_desc": "协会地区配置行 83，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "602",
    "table": "GuildArea",
    "columns": [
      "602",
      "text_GuildArea_602_1",
      "area_name_602",
      "1005"
    ],
    "packaged_name": "协会地区602",
    "packaged_desc": "协会地区配置行 84，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "603",
    "table": "GuildArea",
    "columns": [
      "603",
      "text_GuildArea_603_1",
      "area_name_603",
      "1007"
    ],
    "packaged_name": "协会地区603",
    "packaged_desc": "协会地区配置行 85，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "604",
    "table": "GuildArea",
    "columns": [
      "604",
      "text_GuildArea_604_1",
      "area_name_604",
      "1008"
    ],
    "packaged_name": "协会地区604",
    "packaged_desc": "协会地区配置行 86，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "605",
    "table": "GuildArea",
    "columns": [
      "605",
      "text_GuildArea_605_1",
      "area_name_605",
      "1007"
    ],
    "packaged_name": "协会地区605",
    "packaged_desc": "协会地区配置行 87，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "701",
    "table": "GuildArea",
    "columns": [
      "701",
      "text_GuildArea_701_1",
      "area_name_701",
      "1002"
    ],
    "packaged_name": "协会地区701",
    "packaged_desc": "协会地区配置行 88，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "702",
    "table": "GuildArea",
    "columns": [
      "702",
      "text_GuildArea_702_1",
      "area_name_702",
      "1005"
    ],
    "packaged_name": "协会地区702",
    "packaged_desc": "协会地区配置行 89，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "703",
    "table": "GuildArea",
    "columns": [
      "703",
      "text_GuildArea_703_1",
      "area_name_703",
      "1005"
    ],
    "packaged_name": "协会地区703",
    "packaged_desc": "协会地区配置行 90，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "704",
    "table": "GuildArea",
    "columns": [
      "704",
      "text_GuildArea_704_1",
      "area_name_704",
      "1005"
    ],
    "packaged_name": "协会地区704",
    "packaged_desc": "协会地区配置行 91，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "705",
    "table": "GuildArea",
    "columns": [
      "705",
      "text_GuildArea_705_1",
      "area_name_705",
      "1008"
    ],
    "packaged_name": "协会地区705",
    "packaged_desc": "协会地区配置行 92，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "801",
    "table": "GuildArea",
    "columns": [
      "801",
      "text_GuildArea_801_1",
      "area_name_801",
      "1003"
    ],
    "packaged_name": "协会地区801",
    "packaged_desc": "协会地区配置行 93，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "802",
    "table": "GuildArea",
    "columns": [
      "802",
      "text_GuildArea_802_1",
      "area_name_802",
      "1007"
    ],
    "packaged_name": "协会地区802",
    "packaged_desc": "协会地区配置行 94，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "803",
    "table": "GuildArea",
    "columns": [
      "803",
      "text_GuildArea_803_1",
      "area_name_803",
      "1006"
    ],
    "packaged_name": "协会地区803",
    "packaged_desc": "协会地区配置行 95，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "804",
    "table": "GuildArea",
    "columns": [
      "804",
      "text_GuildArea_804_1",
      "area_name_804",
      "1002"
    ],
    "packaged_name": "协会地区804",
    "packaged_desc": "协会地区配置行 96，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "805",
    "table": "GuildArea",
    "columns": [
      "805",
      "text_GuildArea_805_1",
      "area_name_805",
      "1008"
    ],
    "packaged_name": "协会地区805",
    "packaged_desc": "协会地区配置行 97，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
