// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const GuildPermissions: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "GuildPermissions",
    "columns": [
      "1",
      "text_GuildPermissions_1_1",
      "guild_membe_name_01",
      "1",
      "1",
      "1",
      "1",
      "1",
      "1",
      "1",
      "1"
    ],
    "packaged_name": "协会权限1",
    "packaged_desc": "协会权限配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "GuildPermissions",
    "columns": [
      "2",
      "text_GuildPermissions_2_1",
      "guild_membe_name_02",
      "1",
      "1",
      "0",
      "0",
      "1",
      "1",
      "1",
      "0"
    ],
    "packaged_name": "协会权限2",
    "packaged_desc": "协会权限配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "GuildPermissions",
    "columns": [
      "3",
      "text_GuildPermissions_3_1",
      "guild_membe_name_03",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0"
    ],
    "packaged_name": "协会权限3",
    "packaged_desc": "协会权限配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
