// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const GuildPoints: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "GuildPoints",
    "columns": [
      "1",
      "",
      "1",
      "[50000,200000]",
      "1"
    ],
    "packaged_name": "协会积分1",
    "packaged_desc": "协会积分配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "GuildPoints",
    "columns": [
      "2",
      "",
      "1",
      "[200001,500000]",
      "2"
    ],
    "packaged_name": "协会积分2",
    "packaged_desc": "协会积分配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "GuildPoints",
    "columns": [
      "3",
      "",
      "1",
      "[500001,1000000]",
      "3"
    ],
    "packaged_name": "协会积分3",
    "packaged_desc": "协会积分配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "GuildPoints",
    "columns": [
      "4",
      "",
      "1",
      "[1000001,5000000]",
      "5"
    ],
    "packaged_name": "协会积分4",
    "packaged_desc": "协会积分配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "GuildPoints",
    "columns": [
      "5",
      "",
      "1",
      "[5000001,10000000]",
      "20"
    ],
    "packaged_name": "协会积分5",
    "packaged_desc": "协会积分配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "GuildPoints",
    "columns": [
      "6",
      "",
      "1",
      "[10000001,0]",
      "50"
    ],
    "packaged_name": "协会积分6",
    "packaged_desc": "协会积分配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
