// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Head: BidKingRawTableRow[] = [
  {
    "id": "120000",
    "table": "head",
    "columns": [
      "120000",
      "text_head_120000_1",
      "text_head_120000_2",
      "1",
      "itemName_120000",
      "itemDesc_120000",
      "0",
      "tx_00",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120000",
    "packaged_desc": "头像称号配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120001",
    "table": "head",
    "columns": [
      "120001",
      "text_head_120001_1",
      "text_head_120001_2",
      "1",
      "itemName_120001",
      "itemDesc_120001",
      "0",
      "tx_120001",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120001",
    "packaged_desc": "头像称号配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120002",
    "table": "head",
    "columns": [
      "120002",
      "text_head_120002_1",
      "text_head_120002_2",
      "1",
      "itemName_120002",
      "itemDesc_120002",
      "0",
      "tx_120002",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120002",
    "packaged_desc": "头像称号配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120003",
    "table": "head",
    "columns": [
      "120003",
      "text_head_120003_1",
      "text_head_120003_2",
      "1",
      "itemName_120003",
      "itemDesc_120003",
      "0",
      "tx_120003",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120003",
    "packaged_desc": "头像称号配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120004",
    "table": "head",
    "columns": [
      "120004",
      "text_head_120004_1",
      "text_head_120004_2",
      "1",
      "itemName_120004",
      "itemDesc_120004",
      "0",
      "tx_120004",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120004",
    "packaged_desc": "头像称号配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120005",
    "table": "head",
    "columns": [
      "120005",
      "text_head_120005_1",
      "text_head_120005_2",
      "1",
      "itemName_120005",
      "itemDesc_120005",
      "0",
      "tx_120005",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120005",
    "packaged_desc": "头像称号配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120101",
    "table": "head",
    "columns": [
      "120101",
      "text_head_120101_1",
      "text_head_120101_2",
      "1",
      "itemName_120101",
      "itemDesc_120101",
      "0",
      "hero_xq_101",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120101",
    "packaged_desc": "头像称号配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120102",
    "table": "head",
    "columns": [
      "120102",
      "text_head_120102_1",
      "text_head_120102_2",
      "1",
      "itemName_120102",
      "itemDesc_120102",
      "0",
      "hero_jmr_101",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120102",
    "packaged_desc": "头像称号配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120103",
    "table": "head",
    "columns": [
      "120103",
      "text_head_120103_1",
      "text_head_120103_2",
      "1",
      "itemName_120103",
      "itemDesc_120103",
      "0",
      "hero_xq_101_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120103",
    "packaged_desc": "头像称号配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120201",
    "table": "head",
    "columns": [
      "120201",
      "text_head_120201_1",
      "text_head_120201_2",
      "1",
      "itemName_120201",
      "itemDesc_120201",
      "0",
      "hero_xq_102",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120201",
    "packaged_desc": "头像称号配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120202",
    "table": "head",
    "columns": [
      "120202",
      "text_head_120202_1",
      "text_head_120202_2",
      "1",
      "itemName_120202",
      "itemDesc_120202",
      "0",
      "hero_jmr_102",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120202",
    "packaged_desc": "头像称号配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120203",
    "table": "head",
    "columns": [
      "120203",
      "text_head_120203_1",
      "text_head_120203_2",
      "1",
      "itemName_120203",
      "itemDesc_120203",
      "0",
      "hero_xq_102_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120203",
    "packaged_desc": "头像称号配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120301",
    "table": "head",
    "columns": [
      "120301",
      "text_head_120301_1",
      "text_head_120301_2",
      "1",
      "itemName_120301",
      "itemDesc_120301",
      "0",
      "hero_xq_103",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120301",
    "packaged_desc": "头像称号配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120302",
    "table": "head",
    "columns": [
      "120302",
      "text_head_120302_1",
      "text_head_120302_2",
      "1",
      "itemName_120302",
      "itemDesc_120302",
      "0",
      "hero_jmr_103",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120302",
    "packaged_desc": "头像称号配置行 14，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120303",
    "table": "head",
    "columns": [
      "120303",
      "text_head_120303_1",
      "text_head_120303_2",
      "1",
      "itemName_120303",
      "itemDesc_120303",
      "0",
      "hero_xq_103_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120303",
    "packaged_desc": "头像称号配置行 15，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120401",
    "table": "head",
    "columns": [
      "120401",
      "text_head_120401_1",
      "text_head_120401_2",
      "1",
      "itemName_120401",
      "itemDesc_120401",
      "0",
      "hero_xq_104",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120401",
    "packaged_desc": "头像称号配置行 16，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120402",
    "table": "head",
    "columns": [
      "120402",
      "text_head_120402_1",
      "text_head_120402_2",
      "1",
      "itemName_120402",
      "itemDesc_120402",
      "0",
      "hero_jmr_104",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120402",
    "packaged_desc": "头像称号配置行 17，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120403",
    "table": "head",
    "columns": [
      "120403",
      "text_head_120403_1",
      "text_head_120403_2",
      "1",
      "itemName_120403",
      "itemDesc_120403",
      "0",
      "hero_xq_104_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120403",
    "packaged_desc": "头像称号配置行 18，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120501",
    "table": "head",
    "columns": [
      "120501",
      "text_head_120501_1",
      "text_head_120501_2",
      "1",
      "itemName_120501",
      "itemDesc_120501",
      "0",
      "hero_xq_105",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120501",
    "packaged_desc": "头像称号配置行 19，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120502",
    "table": "head",
    "columns": [
      "120502",
      "text_head_120502_1",
      "text_head_120502_2",
      "1",
      "itemName_120502",
      "itemDesc_120502",
      "0",
      "hero_jmr_105",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120502",
    "packaged_desc": "头像称号配置行 20，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120503",
    "table": "head",
    "columns": [
      "120503",
      "text_head_120503_1",
      "text_head_120503_2",
      "1",
      "itemName_120503",
      "itemDesc_120503",
      "0",
      "hero_xq_105_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120503",
    "packaged_desc": "头像称号配置行 21，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120601",
    "table": "head",
    "columns": [
      "120601",
      "text_head_120601_1",
      "text_head_120601_2",
      "1",
      "itemName_120601",
      "itemDesc_120601",
      "0",
      "hero_xq_106",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120601",
    "packaged_desc": "头像称号配置行 22，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120602",
    "table": "head",
    "columns": [
      "120602",
      "text_head_120602_1",
      "text_head_120602_2",
      "1",
      "itemName_120602",
      "itemDesc_120602",
      "0",
      "hero_jmr_106",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120602",
    "packaged_desc": "头像称号配置行 23，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120603",
    "table": "head",
    "columns": [
      "120603",
      "text_head_120603_1",
      "text_head_120603_2",
      "1",
      "itemName_120603",
      "itemDesc_120603",
      "0",
      "hero_xq_106_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120603",
    "packaged_desc": "头像称号配置行 24，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120701",
    "table": "head",
    "columns": [
      "120701",
      "text_head_120701_1",
      "text_head_120701_2",
      "1",
      "itemName_120701",
      "itemDesc_120701",
      "0",
      "hero_xq_107",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120701",
    "packaged_desc": "头像称号配置行 25，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120702",
    "table": "head",
    "columns": [
      "120702",
      "text_head_120702_1",
      "text_head_120702_2",
      "1",
      "itemName_120702",
      "itemDesc_120702",
      "0",
      "hero_jmr_107",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120702",
    "packaged_desc": "头像称号配置行 26，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120703",
    "table": "head",
    "columns": [
      "120703",
      "text_head_120703_1",
      "text_head_120703_2",
      "1",
      "itemName_120703",
      "itemDesc_120703",
      "0",
      "hero_xq_107_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120703",
    "packaged_desc": "头像称号配置行 27，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120704",
    "table": "head",
    "columns": [
      "120704",
      "text_head_120704_1",
      "text_head_120704_2",
      "1",
      "itemName_120704",
      "itemDesc_120704",
      "0",
      "hero_xq_107_3",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120704",
    "packaged_desc": "头像称号配置行 28，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120801",
    "table": "head",
    "columns": [
      "120801",
      "text_head_120801_1",
      "text_head_120801_2",
      "1",
      "itemName_120801",
      "itemDesc_120801",
      "0",
      "hero_xq_108",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120801",
    "packaged_desc": "头像称号配置行 29，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120802",
    "table": "head",
    "columns": [
      "120802",
      "text_head_120802_1",
      "text_head_120802_2",
      "1",
      "itemName_120802",
      "itemDesc_120802",
      "0",
      "hero_jmr_108",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120802",
    "packaged_desc": "头像称号配置行 30，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120803",
    "table": "head",
    "columns": [
      "120803",
      "text_head_120803_1",
      "text_head_120803_2",
      "1",
      "itemName_120803",
      "itemDesc_120803",
      "0",
      "hero_xq_108_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120803",
    "packaged_desc": "头像称号配置行 31，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120901",
    "table": "head",
    "columns": [
      "120901",
      "text_head_120901_1",
      "text_head_120901_2",
      "1",
      "itemName_120901",
      "itemDesc_120901",
      "0",
      "hero_xq_109",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120901",
    "packaged_desc": "头像称号配置行 32，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120902",
    "table": "head",
    "columns": [
      "120902",
      "text_head_120902_1",
      "text_head_120902_2",
      "1",
      "itemName_120902",
      "itemDesc_120902",
      "0",
      "hero_jmr_109",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120902",
    "packaged_desc": "头像称号配置行 33，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "120903",
    "table": "head",
    "columns": [
      "120903",
      "text_head_120903_1",
      "text_head_120903_2",
      "1",
      "itemName_120903",
      "itemDesc_120903",
      "0",
      "hero_xq_109_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号120903",
    "packaged_desc": "头像称号配置行 34，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121001",
    "table": "head",
    "columns": [
      "121001",
      "text_head_121001_1",
      "text_head_121001_2",
      "1",
      "itemName_121001",
      "itemDesc_121001",
      "0",
      "hero_xq_110",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121001",
    "packaged_desc": "头像称号配置行 35，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121002",
    "table": "head",
    "columns": [
      "121002",
      "text_head_121002_1",
      "text_head_121002_2",
      "1",
      "itemName_121002",
      "itemDesc_121002",
      "0",
      "hero_jmr_110",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121002",
    "packaged_desc": "头像称号配置行 36，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121003",
    "table": "head",
    "columns": [
      "121003",
      "text_head_121003_1",
      "text_head_121003_2",
      "1",
      "itemName_121003",
      "itemDesc_121003",
      "0",
      "hero_xq_110_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121003",
    "packaged_desc": "头像称号配置行 37，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121101",
    "table": "head",
    "columns": [
      "121101",
      "text_head_121101_1",
      "text_head_121101_2",
      "1",
      "itemName_121101",
      "itemDesc_121101",
      "0",
      "hero_xq_201",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121101",
    "packaged_desc": "头像称号配置行 38，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121102",
    "table": "head",
    "columns": [
      "121102",
      "text_head_121102_1",
      "text_head_121102_2",
      "1",
      "itemName_121102",
      "itemDesc_121102",
      "0",
      "hero_jmr_201",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121102",
    "packaged_desc": "头像称号配置行 39，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121103",
    "table": "head",
    "columns": [
      "121103",
      "text_head_121103_1",
      "text_head_121103_2",
      "1",
      "itemName_121103",
      "itemDesc_121103",
      "0",
      "hero_xq_201_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121103",
    "packaged_desc": "头像称号配置行 40，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121201",
    "table": "head",
    "columns": [
      "121201",
      "text_head_121201_1",
      "text_head_121201_2",
      "1",
      "itemName_121201",
      "itemDesc_121201",
      "0",
      "hero_xq_202",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121201",
    "packaged_desc": "头像称号配置行 41，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121202",
    "table": "head",
    "columns": [
      "121202",
      "text_head_121202_1",
      "text_head_121202_2",
      "1",
      "itemName_121202",
      "itemDesc_121202",
      "0",
      "hero_jmr_202",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121202",
    "packaged_desc": "头像称号配置行 42，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121203",
    "table": "head",
    "columns": [
      "121203",
      "text_head_121203_1",
      "text_head_121203_2",
      "1",
      "itemName_121203",
      "itemDesc_121203",
      "0",
      "hero_xq_202_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121203",
    "packaged_desc": "头像称号配置行 43，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121301",
    "table": "head",
    "columns": [
      "121301",
      "text_head_121301_1",
      "text_head_121301_2",
      "1",
      "itemName_121301",
      "itemDesc_121301",
      "0",
      "hero_xq_203",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121301",
    "packaged_desc": "头像称号配置行 44，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121302",
    "table": "head",
    "columns": [
      "121302",
      "text_head_121302_1",
      "text_head_121302_2",
      "1",
      "itemName_121302",
      "itemDesc_121302",
      "0",
      "hero_jmr_203",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121302",
    "packaged_desc": "头像称号配置行 45，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121303",
    "table": "head",
    "columns": [
      "121303",
      "text_head_121303_1",
      "text_head_121303_2",
      "1",
      "itemName_121303",
      "itemDesc_121303",
      "0",
      "hero_xq_203_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121303",
    "packaged_desc": "头像称号配置行 46，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121401",
    "table": "head",
    "columns": [
      "121401",
      "text_head_121401_1",
      "text_head_121401_2",
      "1",
      "itemName_121401",
      "itemDesc_121401",
      "0",
      "hero_xq_204",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121401",
    "packaged_desc": "头像称号配置行 47，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121402",
    "table": "head",
    "columns": [
      "121402",
      "text_head_121402_1",
      "text_head_121402_2",
      "1",
      "itemName_121402",
      "itemDesc_121402",
      "0",
      "hero_jmr_204",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121402",
    "packaged_desc": "头像称号配置行 48，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121403",
    "table": "head",
    "columns": [
      "121403",
      "text_head_121403_1",
      "text_head_121403_2",
      "1",
      "itemName_121403",
      "itemDesc_121403",
      "0",
      "hero_xq_204_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121403",
    "packaged_desc": "头像称号配置行 49，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121501",
    "table": "head",
    "columns": [
      "121501",
      "text_head_121501_1",
      "text_head_121501_2",
      "1",
      "itemName_121501",
      "itemDesc_121501",
      "0",
      "hero_xq_205",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121501",
    "packaged_desc": "头像称号配置行 50，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121502",
    "table": "head",
    "columns": [
      "121502",
      "text_head_121502_1",
      "text_head_121502_2",
      "1",
      "itemName_121502",
      "itemDesc_121502",
      "0",
      "hero_jmr_205",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121502",
    "packaged_desc": "头像称号配置行 51，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121503",
    "table": "head",
    "columns": [
      "121503",
      "text_head_121503_1",
      "text_head_121503_2",
      "1",
      "itemName_121503",
      "itemDesc_121503",
      "0",
      "hero_xq_205_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121503",
    "packaged_desc": "头像称号配置行 52，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121601",
    "table": "head",
    "columns": [
      "121601",
      "text_head_121601_1",
      "text_head_121601_2",
      "1",
      "itemName_121601",
      "itemDesc_121601",
      "0",
      "hero_xq_206",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121601",
    "packaged_desc": "头像称号配置行 53，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121602",
    "table": "head",
    "columns": [
      "121602",
      "text_head_121602_1",
      "text_head_121602_2",
      "1",
      "itemName_121602",
      "itemDesc_121602",
      "0",
      "hero_jmr_206",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121602",
    "packaged_desc": "头像称号配置行 54，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121603",
    "table": "head",
    "columns": [
      "121603",
      "text_head_121603_1",
      "text_head_121603_2",
      "1",
      "itemName_121603",
      "itemDesc_121603",
      "0",
      "hero_xq_206_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121603",
    "packaged_desc": "头像称号配置行 55，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121701",
    "table": "head",
    "columns": [
      "121701",
      "text_head_121701_1",
      "text_head_121701_2",
      "1",
      "itemName_121701",
      "itemDesc_121701",
      "0",
      "hero_xq_207",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121701",
    "packaged_desc": "头像称号配置行 56，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121702",
    "table": "head",
    "columns": [
      "121702",
      "text_head_121702_1",
      "text_head_121702_2",
      "1",
      "itemName_121702",
      "itemDesc_121702",
      "0",
      "hero_jmr_207",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121702",
    "packaged_desc": "头像称号配置行 57，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121703",
    "table": "head",
    "columns": [
      "121703",
      "text_head_121703_1",
      "text_head_121703_2",
      "1",
      "itemName_121703",
      "itemDesc_121703",
      "0",
      "hero_xq_207_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121703",
    "packaged_desc": "头像称号配置行 58，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121801",
    "table": "head",
    "columns": [
      "121801",
      "text_head_121801_1",
      "text_head_121801_2",
      "1",
      "itemName_121801",
      "itemDesc_121801",
      "0",
      "hero_xq_208",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121801",
    "packaged_desc": "头像称号配置行 59，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121802",
    "table": "head",
    "columns": [
      "121802",
      "text_head_121802_1",
      "text_head_121802_2",
      "1",
      "itemName_121802",
      "itemDesc_121802",
      "0",
      "hero_jmr_208",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121802",
    "packaged_desc": "头像称号配置行 60，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121803",
    "table": "head",
    "columns": [
      "121803",
      "text_head_121803_1",
      "text_head_121803_2",
      "1",
      "itemName_121803",
      "itemDesc_121803",
      "0",
      "hero_xq_208_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121803",
    "packaged_desc": "头像称号配置行 61，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121804",
    "table": "head",
    "columns": [
      "121804",
      "text_head_121804_1",
      "text_head_121804_2",
      "1",
      "itemName_121804",
      "itemDesc_121804",
      "0",
      "hero_xq_208_3",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121804",
    "packaged_desc": "头像称号配置行 62，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121901",
    "table": "head",
    "columns": [
      "121901",
      "text_head_121901_1",
      "text_head_121901_2",
      "1",
      "itemName_121901",
      "itemDesc_121901",
      "0",
      "hero_xq_209",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121901",
    "packaged_desc": "头像称号配置行 63，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121902",
    "table": "head",
    "columns": [
      "121902",
      "text_head_121902_1",
      "text_head_121902_2",
      "1",
      "itemName_121902",
      "itemDesc_121902",
      "0",
      "hero_jmr_209",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121902",
    "packaged_desc": "头像称号配置行 64，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "121903",
    "table": "head",
    "columns": [
      "121903",
      "text_head_121903_1",
      "text_head_121903_2",
      "1",
      "itemName_121903",
      "itemDesc_121903",
      "0",
      "hero_xq_209_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号121903",
    "packaged_desc": "头像称号配置行 65，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "122001",
    "table": "head",
    "columns": [
      "122001",
      "text_head_122001_1",
      "text_head_122001_2",
      "1",
      "itemName_122001",
      "itemDesc_122001",
      "0",
      "hero_xq_301",
      "0",
      "1"
    ],
    "packaged_name": "头像称号122001",
    "packaged_desc": "头像称号配置行 66，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "122002",
    "table": "head",
    "columns": [
      "122002",
      "text_head_122002_1",
      "text_head_122002_2",
      "1",
      "itemName_122002",
      "itemDesc_122002",
      "0",
      "hero_jmr_301",
      "0",
      "1"
    ],
    "packaged_name": "头像称号122002",
    "packaged_desc": "头像称号配置行 67，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "122003",
    "table": "head",
    "columns": [
      "122003",
      "text_head_122003_1",
      "text_head_122003_2",
      "1",
      "itemName_122003",
      "itemDesc_122003",
      "0",
      "hero_xq_301_2",
      "0",
      "1"
    ],
    "packaged_name": "头像称号122003",
    "packaged_desc": "头像称号配置行 68，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140001",
    "table": "head",
    "columns": [
      "140001",
      "text_head_140001_1",
      "text_head_140001_2",
      "2",
      "itemName_140001",
      "itemDesc_140001",
      "0",
      "ui_avatarframe_01",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140001",
    "packaged_desc": "头像称号配置行 69，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140002",
    "table": "head",
    "columns": [
      "140002",
      "text_head_140002_1",
      "text_head_140002_2",
      "2",
      "itemName_140002",
      "itemDesc_140002",
      "0",
      "ui_avatarframe_02",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140002",
    "packaged_desc": "头像称号配置行 70，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140003",
    "table": "head",
    "columns": [
      "140003",
      "text_head_140003_1",
      "text_head_140003_2",
      "2",
      "itemName_140003",
      "itemDesc_140003",
      "0",
      "ui_avatarframe_03",
      "0",
      "0"
    ],
    "packaged_name": "头像称号140003",
    "packaged_desc": "头像称号配置行 71，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140004",
    "table": "head",
    "columns": [
      "140004",
      "text_head_140004_1",
      "text_head_140004_2",
      "2",
      "itemName_140004",
      "itemDesc_140004",
      "0",
      "ui_avatarframe_04",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140004",
    "packaged_desc": "头像称号配置行 72，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140005",
    "table": "head",
    "columns": [
      "140005",
      "text_head_140005_1",
      "text_head_140005_2",
      "2",
      "itemName_140005",
      "itemDesc_140005",
      "0",
      "ui_avatarframe_05",
      "0",
      "0"
    ],
    "packaged_name": "头像称号140005",
    "packaged_desc": "头像称号配置行 73，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140006",
    "table": "head",
    "columns": [
      "140006",
      "text_head_140006_1",
      "text_head_140006_2",
      "2",
      "itemName_140006",
      "itemDesc_140006",
      "0",
      "ui_avatarframe_06",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140006",
    "packaged_desc": "头像称号配置行 74，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140007",
    "table": "head",
    "columns": [
      "140007",
      "text_head_140007_1",
      "text_head_140007_2",
      "2",
      "itemName_140007",
      "itemDesc_140007",
      "0",
      "ui_avatarframe_07",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140007",
    "packaged_desc": "头像称号配置行 75，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140008",
    "table": "head",
    "columns": [
      "140008",
      "text_head_140008_1",
      "text_head_140008_2",
      "2",
      "itemName_140008",
      "itemDesc_140008",
      "0",
      "ui_avatarframe_08",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140008",
    "packaged_desc": "头像称号配置行 76，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140009",
    "table": "head",
    "columns": [
      "140009",
      "text_head_140009_1",
      "text_head_140009_2",
      "2",
      "itemName_140009",
      "itemDesc_140009",
      "0",
      "ui_avatarframe_09",
      "1",
      "1"
    ],
    "packaged_name": "头像称号140009",
    "packaged_desc": "头像称号配置行 77，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140010",
    "table": "head",
    "columns": [
      "140010",
      "text_head_140010_1",
      "text_head_140010_2",
      "2",
      "itemName_140010",
      "itemDesc_140010",
      "0",
      "ui_avatarframe_10",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140010",
    "packaged_desc": "头像称号配置行 78，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140011",
    "table": "head",
    "columns": [
      "140011",
      "text_head_140011_1",
      "text_head_140011_2",
      "2",
      "itemName_140011",
      "itemDesc_140011",
      "0",
      "ui_avatarframe_11",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140011",
    "packaged_desc": "头像称号配置行 79，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140701",
    "table": "head",
    "columns": [
      "140701",
      "text_head_140701_1",
      "text_head_140701_2",
      "2",
      "itemName_140701",
      "itemDesc_140701",
      "0",
      "ui_avatarframe_140701",
      "0",
      "1"
    ],
    "packaged_name": "头像称号140701",
    "packaged_desc": "头像称号配置行 80，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "140702",
    "table": "head",
    "columns": [
      "140702",
      "text_head_140702_1",
      "text_head_140702_2",
      "2",
      "itemName_140702",
      "itemDesc_140702",
      "0",
      "ui_avatarframe_140702",
      "1",
      "1"
    ],
    "packaged_name": "头像称号140702",
    "packaged_desc": "头像称号配置行 81，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150001",
    "table": "head",
    "columns": [
      "150001",
      "text_head_150001_1",
      "text_head_150001_2",
      "3",
      "itemName_150001",
      "itemDesc_150001",
      "itemName_150001",
      "ui_title_01",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150001",
    "packaged_desc": "头像称号配置行 82，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150002",
    "table": "head",
    "columns": [
      "150002",
      "text_head_150002_1",
      "text_head_150002_2",
      "3",
      "itemName_150002",
      "itemDesc_150002",
      "itemName_150002",
      "ui_title_02",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150002",
    "packaged_desc": "头像称号配置行 83，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150003",
    "table": "head",
    "columns": [
      "150003",
      "text_head_150003_1",
      "text_head_150003_2",
      "3",
      "itemName_150003",
      "itemDesc_150003",
      "itemName_150003",
      "ui_title_03",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150003",
    "packaged_desc": "头像称号配置行 84，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150004",
    "table": "head",
    "columns": [
      "150004",
      "text_head_150004_1",
      "text_head_150004_2",
      "3",
      "itemName_150004",
      "itemDesc_150004",
      "itemName_150004",
      "ui_title_04",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150004",
    "packaged_desc": "头像称号配置行 85，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150005",
    "table": "head",
    "columns": [
      "150005",
      "text_head_150005_1",
      "text_head_150005_2",
      "3",
      "itemName_150005",
      "itemDesc_150005",
      "itemName_150005",
      "ui_title_05",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150005",
    "packaged_desc": "头像称号配置行 86，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150006",
    "table": "head",
    "columns": [
      "150006",
      "text_head_150006_1",
      "text_head_150006_2",
      "3",
      "itemName_150006",
      "itemDesc_150006",
      "itemName_150006",
      "ui_title_06",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150006",
    "packaged_desc": "头像称号配置行 87，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150007",
    "table": "head",
    "columns": [
      "150007",
      "text_head_150007_1",
      "text_head_150007_2",
      "3",
      "itemName_150007",
      "itemDesc_150007",
      "itemName_150007",
      "ui_title_07",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150007",
    "packaged_desc": "头像称号配置行 88，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150008",
    "table": "head",
    "columns": [
      "150008",
      "text_head_150008_1",
      "text_head_150008_2",
      "3",
      "itemName_150008",
      "itemDesc_150008",
      "itemName_150008",
      "ui_title_08",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150008",
    "packaged_desc": "头像称号配置行 89，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150009",
    "table": "head",
    "columns": [
      "150009",
      "text_head_150009_1",
      "text_head_150009_2",
      "3",
      "itemName_150009",
      "itemDesc_150009",
      "itemName_150009",
      "ui_title_09",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150009",
    "packaged_desc": "头像称号配置行 90，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150010",
    "table": "head",
    "columns": [
      "150010",
      "text_head_150010_1",
      "text_head_150010_2",
      "3",
      "itemName_150010",
      "itemDesc_150010",
      "itemName_150010",
      "ui_title_10",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150010",
    "packaged_desc": "头像称号配置行 91，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150011",
    "table": "head",
    "columns": [
      "150011",
      "text_head_150011_1",
      "text_head_150011_2",
      "3",
      "itemName_150011",
      "itemDesc_150011",
      "itemName_150011",
      "ui_title_11",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150011",
    "packaged_desc": "头像称号配置行 92，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150012",
    "table": "head",
    "columns": [
      "150012",
      "text_head_150012_1",
      "text_head_150012_2",
      "3",
      "itemName_150012",
      "itemDesc_150012",
      "itemName_150012",
      "ui_title_12",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150012",
    "packaged_desc": "头像称号配置行 93，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150013",
    "table": "head",
    "columns": [
      "150013",
      "text_head_150013_1",
      "text_head_150013_2",
      "3",
      "itemName_150013",
      "itemDesc_150013",
      "itemName_150013",
      "ui_title_13",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150013",
    "packaged_desc": "头像称号配置行 94，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150014",
    "table": "head",
    "columns": [
      "150014",
      "text_head_150014_1",
      "text_head_150014_2",
      "3",
      "itemName_150014",
      "itemDesc_150014",
      "itemName_150014",
      "ui_title_14",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150014",
    "packaged_desc": "头像称号配置行 95，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150015",
    "table": "head",
    "columns": [
      "150015",
      "text_head_150015_1",
      "text_head_150015_2",
      "3",
      "itemName_150015",
      "itemDesc_150015",
      "itemName_150015",
      "ui_title_15",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150015",
    "packaged_desc": "头像称号配置行 96，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150016",
    "table": "head",
    "columns": [
      "150016",
      "text_head_150016_1",
      "text_head_150016_2",
      "3",
      "itemName_150016",
      "itemDesc_150016",
      "itemName_150016",
      "ui_title_16",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150016",
    "packaged_desc": "头像称号配置行 97，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150017",
    "table": "head",
    "columns": [
      "150017",
      "text_head_150017_1",
      "text_head_150017_2",
      "3",
      "itemName_150017",
      "itemDesc_150017",
      "itemName_150017",
      "ui_title_17",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150017",
    "packaged_desc": "头像称号配置行 98，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150018",
    "table": "head",
    "columns": [
      "150018",
      "text_head_150018_1",
      "text_head_150018_2",
      "3",
      "itemName_150018",
      "itemDesc_150018",
      "itemName_150018",
      "ui_title_18",
      "0",
      "0"
    ],
    "packaged_name": "头像称号150018",
    "packaged_desc": "头像称号配置行 99，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150019",
    "table": "head",
    "columns": [
      "150019",
      "text_head_150019_1",
      "text_head_150019_2",
      "3",
      "itemName_150019",
      "itemDesc_150019",
      "itemName_150019",
      "ui_title_19",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150019",
    "packaged_desc": "头像称号配置行 100，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150020",
    "table": "head",
    "columns": [
      "150020",
      "text_head_150020_1",
      "text_head_150020_2",
      "3",
      "itemName_150020",
      "itemDesc_150020",
      "itemName_150020",
      "ui_title_20",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150020",
    "packaged_desc": "头像称号配置行 101，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "150021",
    "table": "head",
    "columns": [
      "150021",
      "text_head_150021_1",
      "text_head_150021_2",
      "3",
      "itemName_150021",
      "itemDesc_150021",
      "itemName_150021",
      "ui_title_21",
      "0",
      "1"
    ],
    "packaged_name": "头像称号150021",
    "packaged_desc": "头像称号配置行 102，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
