// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingHeroSkinRow } from '../schema';

export const HeroSkin: BidKingHeroSkinRow[] = [
  {
    "id": 1410101,
    "skinhero": 101,
    "name": "hero_n_101",
    "skin_class": "hero_skin_d_101_1",
    "skinground": "hero_skin_c_101_1",
    "icon_path": "hero_xq_101_2",
    "icon_path2": "hero_xq_101_2",
    "icon_path3": "hero_bs_101_2",
    "illustration_path": "hero_xq_101_2",
    "bg_path": "hero_bg_101_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1101101,
      1101110,
      1101111,
      1101112,
      1101113,
      1101109
    ],
    "battleBgm": [
      101
    ],
    "hero_tag": 101,
    "packaged_name": "卧龙掌眼衣装",
    "packaged_desc": "绑定竞买人 101，语音 6 条，BGM 101。"
  },
  {
    "id": 1410201,
    "skinhero": 102,
    "name": "hero_n_102",
    "skin_class": "hero_skin_d_102_1",
    "skinground": "hero_skin_c_102_1",
    "icon_path": "hero_xq_102_2",
    "icon_path2": "hero_xq_102_2",
    "icon_path3": "hero_bs_102_2",
    "illustration_path": "hero_xq_102_2",
    "bg_path": "hero_bg_102_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1102101,
      1102110,
      1102111,
      1102112,
      1102113,
      1102109
    ],
    "battleBgm": [
      102
    ],
    "hero_tag": 102,
    "packaged_name": "江东雅鉴衣装",
    "packaged_desc": "绑定竞买人 102，语音 6 条，BGM 102。"
  },
  {
    "id": 1410301,
    "skinhero": 103,
    "name": "hero_n_103",
    "skin_class": "hero_skin_d_103_1",
    "skinground": "hero_skin_c_103_1",
    "icon_path": "hero_xq_103_2",
    "icon_path2": "hero_xq_103_2",
    "icon_path3": "hero_bs_103_2",
    "illustration_path": "hero_xq_103_2",
    "bg_path": "hero_bg_103_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1103101,
      1103110,
      1103111,
      1103112,
      1103113,
      1103109
    ],
    "battleBgm": [
      103
    ],
    "hero_tag": 103,
    "packaged_name": "冢虎账师衣装",
    "packaged_desc": "绑定竞买人 103，语音 6 条，BGM 103。"
  },
  {
    "id": 1410401,
    "skinhero": 104,
    "name": "hero_n_104",
    "skin_class": "hero_skin_d_104_1",
    "skinground": "hero_skin_c_104_1",
    "icon_path": "hero_xq_104_2",
    "icon_path2": "hero_xq_104_2",
    "icon_path3": "hero_bs_104_2",
    "illustration_path": "hero_xq_104_2",
    "bg_path": "hero_bg_104_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1104101,
      1104110,
      1104111,
      1104112,
      1104113,
      1104109
    ],
    "battleBgm": [
      104
    ],
    "hero_tag": 104,
    "packaged_name": "连环谋士衣装",
    "packaged_desc": "绑定竞买人 104，语音 6 条，BGM 104。"
  },
  {
    "id": 1410501,
    "skinhero": 105,
    "name": "hero_n_105",
    "skin_class": "hero_skin_d_105_1",
    "skinground": "hero_skin_c_105_1",
    "icon_path": "hero_xq_105_2",
    "icon_path2": "hero_xq_105_2",
    "icon_path3": "hero_bs_105_2",
    "illustration_path": "hero_xq_105_2",
    "bg_path": "hero_bg_105_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1105101,
      1105110,
      1105111,
      1105112,
      1105113,
      1105109
    ],
    "battleBgm": [
      105
    ],
    "hero_tag": 105,
    "packaged_name": "神医鉴客衣装",
    "packaged_desc": "绑定竞买人 105，语音 6 条，BGM 105。"
  },
  {
    "id": 1410601,
    "skinhero": 106,
    "name": "hero_n_106",
    "skin_class": "hero_skin_d_106_1",
    "skinground": "hero_skin_c_106_1",
    "icon_path": "hero_xq_106_2",
    "icon_path2": "hero_xq_106_2",
    "icon_path3": "hero_bs_106_2",
    "illustration_path": "hero_xq_106_2",
    "bg_path": "hero_bg_106_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1106101,
      1106110,
      1106111,
      1106112,
      1106113,
      1106109
    ],
    "battleBgm": [
      106
    ],
    "hero_tag": 106,
    "packaged_name": "东吴书佐衣装",
    "packaged_desc": "绑定竞买人 106，语音 6 条，BGM 106。"
  },
  {
    "id": 1410701,
    "skinhero": 107,
    "name": "hero_n_107",
    "skin_class": "hero_skin_d_107_1",
    "skinground": "hero_skin_c_107_1",
    "icon_path": "hero_xq_107_2",
    "icon_path2": "hero_xq_107_2",
    "icon_path3": "hero_bs_107_2",
    "illustration_path": "hero_xq_107_2",
    "bg_path": "hero_bg_107_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1107101,
      1107110,
      1107111,
      1107112,
      1107113,
      1107109
    ],
    "battleBgm": [
      107
    ],
    "hero_tag": 107,
    "packaged_name": "魏武藏家衣装",
    "packaged_desc": "绑定竞买人 107，语音 6 条，BGM 107。"
  },
  {
    "id": 1410801,
    "skinhero": 108,
    "name": "hero_n_108",
    "skin_class": "hero_skin_d_108_1",
    "skinground": "hero_skin_c_108_1",
    "icon_path": "hero_xq_108_2",
    "icon_path2": "hero_xq_108_2",
    "icon_path3": "hero_bs_108_2",
    "illustration_path": "hero_xq_108_2",
    "bg_path": "hero_bg_108_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1108101,
      1108110,
      1108111,
      1108112,
      1108113,
      1108109
    ],
    "battleBgm": [
      108
    ],
    "hero_tag": 108,
    "packaged_name": "弓腰鉴客衣装",
    "packaged_desc": "绑定竞买人 108，语音 6 条，BGM 108。"
  },
  {
    "id": 1410901,
    "skinhero": 109,
    "name": "hero_n_109",
    "skin_class": "hero_skin_d_109_1",
    "skinground": "hero_skin_c_109_1",
    "icon_path": "hero_xq_109_2",
    "icon_path2": "hero_xq_109_2",
    "icon_path3": "hero_bs_109_2",
    "illustration_path": "hero_xq_109_2",
    "bg_path": "hero_bg_109_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1109101,
      1109110,
      1109111,
      1109112,
      1109113,
      1109109
    ],
    "battleBgm": [
      109
    ],
    "hero_tag": 109,
    "packaged_name": "义绝武库衣装",
    "packaged_desc": "绑定竞买人 109，语音 6 条，BGM 109。"
  },
  {
    "id": 1411001,
    "skinhero": 110,
    "name": "hero_n_110",
    "skin_class": "hero_skin_d_110_1",
    "skinground": "hero_skin_c_110_1",
    "icon_path": "hero_xq_110_2",
    "icon_path2": "hero_xq_110_2",
    "icon_path3": "hero_bs_110_2",
    "illustration_path": "hero_xq_110_2",
    "bg_path": "hero_bg_110_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1110101,
      1110110,
      1110111,
      1110112,
      1110113,
      1110109
    ],
    "battleBgm": [
      110
    ],
    "hero_tag": 110,
    "packaged_name": "常胜护宝衣装",
    "packaged_desc": "绑定竞买人 110，语音 6 条，BGM 110。"
  },
  {
    "id": 1420101,
    "skinhero": 201,
    "name": "hero_n_201",
    "skin_class": "hero_skin_d_201_1",
    "skinground": "hero_skin_c_201_1",
    "icon_path": "hero_xq_201_2",
    "icon_path2": "hero_xq_201_2",
    "icon_path3": "hero_bs_201_2",
    "illustration_path": "hero_xq_201_2",
    "bg_path": "hero_bg_201_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1201101,
      1201110,
      1201111,
      1201112,
      1201113,
      1201109
    ],
    "battleBgm": [
      111
    ],
    "hero_tag": 201,
    "packaged_name": "玄德掌柜衣装",
    "packaged_desc": "绑定竞买人 201，语音 6 条，BGM 111。"
  },
  {
    "id": 1420201,
    "skinhero": 202,
    "name": "hero_n_202",
    "skin_class": "hero_skin_d_202_1",
    "skinground": "hero_skin_c_202_1",
    "icon_path": "hero_xq_202_2",
    "icon_path2": "hero_xq_202_2",
    "icon_path3": "hero_bs_202_2",
    "illustration_path": "hero_xq_202_2",
    "bg_path": "hero_bg_202_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1202101,
      1202110,
      1202111,
      1202112,
      1202113,
      1202109
    ],
    "battleBgm": [
      112
    ],
    "hero_tag": 202,
    "packaged_name": "王佐评估衣装",
    "packaged_desc": "绑定竞买人 202，语音 6 条，BGM 112。"
  },
  {
    "id": 1420301,
    "skinhero": 203,
    "name": "hero_n_203",
    "skin_class": "hero_skin_d_203_1",
    "skinground": "hero_skin_c_203_1",
    "icon_path": "hero_xq_203_2",
    "icon_path2": "hero_xq_203_2",
    "icon_path3": "hero_bs_203_2",
    "illustration_path": "hero_xq_203_2",
    "bg_path": "hero_bg_203_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1203101,
      1203110,
      1203111,
      1203112,
      1203113,
      1203109
    ],
    "battleBgm": [
      113
    ],
    "hero_tag": 203,
    "packaged_name": "锦绣掌眼衣装",
    "packaged_desc": "绑定竞买人 203，语音 6 条，BGM 113。"
  },
  {
    "id": 1420401,
    "skinhero": 204,
    "name": "hero_n_204",
    "skin_class": "hero_skin_d_204_1",
    "skinground": "hero_skin_c_204_1",
    "icon_path": "hero_xq_204_2",
    "icon_path2": "hero_xq_204_2",
    "icon_path3": "hero_bs_204_2",
    "illustration_path": "hero_xq_204_2",
    "bg_path": "hero_bg_204_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1204101,
      1204110,
      1204111,
      1204112,
      1204113,
      1204109
    ],
    "battleBgm": [
      114
    ],
    "hero_tag": 204,
    "packaged_name": "白衣行商衣装",
    "packaged_desc": "绑定竞买人 204，语音 6 条，BGM 114。"
  },
  {
    "id": 1420501,
    "skinhero": 205,
    "name": "hero_n_205",
    "skin_class": "hero_skin_d_205_1",
    "skinground": "hero_skin_c_205_1",
    "icon_path": "hero_xq_205_2",
    "icon_path2": "hero_xq_205_2",
    "icon_path3": "hero_bs_205_2",
    "illustration_path": "hero_xq_205_2",
    "bg_path": "hero_bg_205_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1205101,
      1205110,
      1205111,
      1205112,
      1205113,
      1205109
    ],
    "battleBgm": [
      115
    ],
    "hero_tag": 205,
    "packaged_name": "虎将竞客衣装",
    "packaged_desc": "绑定竞买人 205，语音 6 条，BGM 115。"
  },
  {
    "id": 1420601,
    "skinhero": 206,
    "name": "hero_n_206",
    "skin_class": "hero_skin_d_206_1",
    "skinground": "hero_skin_c_206_1",
    "icon_path": "hero_xq_206_2",
    "icon_path2": "hero_xq_206_2",
    "icon_path3": "hero_bs_206_2",
    "illustration_path": "hero_xq_206_2",
    "bg_path": "hero_bg_206_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1206101,
      1206110,
      1206111,
      1206112,
      1206113,
      1206109
    ],
    "battleBgm": [
      116
    ],
    "hero_tag": 206,
    "packaged_name": "凤雏书鉴衣装",
    "packaged_desc": "绑定竞买人 206，语音 6 条，BGM 116。"
  },
  {
    "id": 1420701,
    "skinhero": 207,
    "name": "hero_n_207",
    "skin_class": "hero_skin_d_207_1",
    "skinground": "hero_skin_c_207_1",
    "icon_path": "hero_xq_207_2",
    "icon_path2": "hero_xq_207_2",
    "icon_path3": "hero_bs_207_2",
    "illustration_path": "hero_xq_207_2",
    "bg_path": "hero_bg_207_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1207101,
      1207110,
      1207111,
      1207112,
      1207113,
      1207109
    ],
    "battleBgm": [
      117
    ],
    "hero_tag": 207,
    "packaged_name": "水镜文士衣装",
    "packaged_desc": "绑定竞买人 207，语音 6 条，BGM 117。"
  },
  {
    "id": 1420801,
    "skinhero": 208,
    "name": "hero_n_208",
    "skin_class": "hero_skin_d_208_1",
    "skinground": "hero_skin_c_208_1",
    "icon_path": "hero_xq_208_2",
    "icon_path2": "hero_xq_208_2",
    "icon_path3": "hero_bs_208_2",
    "illustration_path": "hero_xq_208_2",
    "bg_path": "hero_bg_208_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1208101,
      1208110,
      1208111,
      1208112,
      1208113,
      1208109
    ],
    "battleBgm": [
      118
    ],
    "hero_tag": 208,
    "packaged_name": "巧思工师衣装",
    "packaged_desc": "绑定竞买人 208，语音 6 条，BGM 118。"
  },
  {
    "id": 1420901,
    "skinhero": 209,
    "name": "hero_n_209",
    "skin_class": "hero_skin_d_209_1",
    "skinground": "hero_skin_c_209_1",
    "icon_path": "hero_xq_209_2",
    "icon_path2": "hero_xq_209_2",
    "icon_path3": "hero_bs_209_2",
    "illustration_path": "hero_xq_209_2",
    "bg_path": "hero_bg_209_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1209101,
      1209110,
      1209111,
      1209112,
      1209113,
      1209109
    ],
    "battleBgm": [
      119
    ],
    "hero_tag": 209,
    "packaged_name": "西凉骑鉴衣装",
    "packaged_desc": "绑定竞买人 209，语音 6 条，BGM 119。"
  },
  {
    "id": 1430101,
    "skinhero": 301,
    "name": "hero_n_301",
    "skin_class": "hero_skin_d_301_1",
    "skinground": "hero_skin_c_301_1",
    "icon_path": "hero_xq_301_2",
    "icon_path2": "hero_xq_301_2",
    "icon_path3": "hero_bs_301_2",
    "illustration_path": "hero_xq_301_2",
    "bg_path": "hero_bg_301_2",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1301101,
      1301110,
      1301111,
      1301112,
      1301113,
      1301109
    ],
    "battleBgm": [
      120
    ],
    "hero_tag": 301,
    "packaged_name": "洛阳名士衣装",
    "packaged_desc": "绑定竞买人 301，语音 6 条，BGM 120。"
  },
  {
    "id": 1410702,
    "skinhero": 107,
    "name": "hero_n_107",
    "skin_class": "hero_skin_d_107_2",
    "skinground": "hero_skin_c_107_2",
    "icon_path": "hero_xq_107_3",
    "icon_path2": "hero_xq_107_3",
    "icon_path3": "hero_bs_107_3",
    "illustration_path": "hero_xq_107_3",
    "bg_path": "hero_bg_107_3",
    "access": [],
    "voices": [
      1107101,
      1107110,
      1107111,
      1107112,
      1107113,
      1107109
    ],
    "battleBgm": [
      107
    ],
    "hero_tag": 107,
    "packaged_name": "魏武藏家衣装",
    "packaged_desc": "绑定竞买人 107，语音 6 条，BGM 107。"
  },
  {
    "id": 1420802,
    "skinhero": 208,
    "name": "hero_n_208",
    "skin_class": "hero_skin_d_208_2",
    "skinground": "hero_skin_c_208_2",
    "icon_path": "hero_xq_208_3",
    "icon_path2": "hero_xq_208_3",
    "icon_path3": "hero_bs_208_3",
    "illustration_path": "hero_xq_208_3",
    "bg_path": "hero_bg_208_3",
    "access": [
      1,
      2000000
    ],
    "voices": [
      1401101,
      1401110,
      1401111,
      1401112,
      1401113,
      1401109
    ],
    "battleBgm": [
      118
    ],
    "hero_tag": 401,
    "packaged_name": "巧思工师衣装",
    "packaged_desc": "绑定竞买人 208，语音 6 条，BGM 118。"
  }
];
