// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingHeroRow } from '../schema';

export const Hero: BidKingHeroRow[] = [
  {
    "id": 101,
    "name": "hero_n_101",
    "gender": 1,
    "hero_class": "hero_c_101",
    "background": "hero_b_101",
    "hero_skill_name": "hero_skill_101",
    "hero_skill_description": "hero_dec_101",
    "hero_effect_description": "hero_effect_101",
    "cast_type": [
      100101,
      1001011,
      1001012,
      1001013,
      1001014
    ],
    "icon_path": "hero_xq_101",
    "icon_path2": "hero_xq_101",
    "icon_path3": "hero_bs_101_1",
    "illustration_path": "hero_xq_101",
    "bg_path": "hero_bg_101",
    "access": [
      2,
      380
    ],
    "voices": [
      1101101,
      1101110,
      1101111,
      1101112,
      1101113,
      1101109
    ],
    "battleBgm": [
      101
    ],
    "hero_tag": 101,
    "hero_task_group": [
      1010101,
      1010102
    ],
    "packaged_name": "卧龙掌眼",
    "packaged_title": "多维线索",
    "packaged_role_id": "zhugeliang"
  },
  {
    "id": 102,
    "name": "hero_n_102",
    "gender": 1,
    "hero_class": "hero_c_102",
    "background": "hero_b_102",
    "hero_skill_name": "hero_skill_102",
    "hero_skill_description": "hero_dec_102",
    "hero_effect_description": "hero_effect_102",
    "cast_type": [
      100102
    ],
    "icon_path": "hero_xq_102",
    "icon_path2": "hero_xq_102",
    "icon_path3": "hero_bs_102_1",
    "illustration_path": "hero_xq_102",
    "bg_path": "hero_bg_102",
    "access": [
      2,
      380
    ],
    "voices": [
      1102101,
      1102110,
      1102111,
      1102112,
      1102113,
      1102109
    ],
    "battleBgm": [
      102
    ],
    "hero_tag": 102,
    "hero_task_group": [
      1010201,
      1010202
    ],
    "packaged_name": "江东雅鉴",
    "packaged_title": "品类识别",
    "packaged_role_id": "zhouyu"
  },
  {
    "id": 103,
    "name": "hero_n_103",
    "gender": 1,
    "hero_class": "hero_c_103",
    "background": "hero_b_103",
    "hero_skill_name": "hero_skill_103",
    "hero_skill_description": "hero_dec_103",
    "hero_effect_description": "hero_effect_103",
    "cast_type": [
      1001034,
      1001033,
      1001032,
      1001031
    ],
    "icon_path": "hero_xq_103",
    "icon_path2": "hero_xq_103",
    "icon_path3": "hero_bs_103_1",
    "illustration_path": "hero_xq_103",
    "bg_path": "hero_bg_103",
    "access": [
      2,
      380
    ],
    "voices": [
      1103101,
      1103110,
      1103111,
      1103112,
      1103113,
      1103109
    ],
    "battleBgm": [
      103
    ],
    "hero_tag": 103,
    "hero_task_group": [
      1010301,
      1010302
    ],
    "packaged_name": "冢虎账师",
    "packaged_title": "品质筛选",
    "packaged_role_id": "simayi"
  },
  {
    "id": 104,
    "name": "hero_n_104",
    "gender": 1,
    "hero_class": "hero_c_104",
    "background": "hero_b_104",
    "hero_skill_name": "hero_skill_104",
    "hero_skill_description": "hero_dec_104",
    "hero_effect_description": "hero_effect_104",
    "cast_type": [
      1001041,
      1001042,
      1001043,
      1001044,
      1001045
    ],
    "icon_path": "hero_xq_104",
    "icon_path2": "hero_xq_104",
    "icon_path3": "hero_bs_104_1",
    "illustration_path": "hero_xq_104",
    "bg_path": "hero_bg_104",
    "access": [
      2,
      380
    ],
    "voices": [
      1104101,
      1104110,
      1104111,
      1104112,
      1104113,
      1104109
    ],
    "battleBgm": [
      104
    ],
    "hero_tag": 104,
    "hero_task_group": [
      1010401,
      1010402
    ],
    "packaged_name": "连环谋士",
    "packaged_title": "轮廓揭示",
    "packaged_role_id": "diaochan"
  },
  {
    "id": 105,
    "name": "hero_n_105",
    "gender": 1,
    "hero_class": "hero_c_105",
    "background": "hero_b_105",
    "hero_skill_name": "hero_skill_105",
    "hero_skill_description": "hero_dec_105",
    "hero_effect_description": "hero_effect_105",
    "cast_type": [
      100105
    ],
    "icon_path": "hero_xq_105",
    "icon_path2": "hero_xq_105",
    "icon_path3": "hero_bs_105_1",
    "illustration_path": "hero_xq_105",
    "bg_path": "hero_bg_105",
    "access": [
      2,
      380
    ],
    "voices": [
      1105101,
      1105110,
      1105111,
      1105112,
      1105113,
      1105109
    ],
    "battleBgm": [
      105
    ],
    "hero_tag": 105,
    "hero_task_group": [
      1010501,
      1010502
    ],
    "packaged_name": "神医鉴客",
    "packaged_title": "器类识别",
    "packaged_role_id": "huatuo"
  },
  {
    "id": 106,
    "name": "hero_n_106",
    "gender": 1,
    "hero_class": "hero_c_106",
    "background": "hero_b_106",
    "hero_skill_name": "hero_skill_106",
    "hero_skill_description": "hero_dec_106",
    "hero_effect_description": "hero_effect_106",
    "cast_type": [
      100106
    ],
    "icon_path": "hero_xq_106",
    "icon_path2": "hero_xq_106",
    "icon_path3": "hero_bs_106_1",
    "illustration_path": "hero_xq_106",
    "bg_path": "hero_bg_106",
    "access": [
      2,
      380
    ],
    "voices": [
      1106101,
      1106110,
      1106111,
      1106112,
      1106113,
      1106109
    ],
    "battleBgm": [
      106
    ],
    "hero_tag": 106,
    "hero_task_group": [
      1010601,
      1010602
    ],
    "packaged_name": "东吴书佐",
    "packaged_title": "双类追踪",
    "packaged_role_id": "luxun"
  },
  {
    "id": 107,
    "name": "hero_n_107",
    "gender": 1,
    "hero_class": "hero_c_107",
    "background": "hero_b_107",
    "hero_skill_name": "hero_skill_107",
    "hero_skill_description": "hero_dec_107",
    "hero_effect_description": "hero_effect_107",
    "cast_type": [
      100107,
      1001071,
      1001072,
      1001073,
      1001074
    ],
    "icon_path": "hero_xq_107",
    "icon_path2": "hero_xq_107",
    "icon_path3": "hero_bs_107_1",
    "illustration_path": "hero_xq_107",
    "bg_path": "hero_bg_107",
    "access": [
      2,
      380
    ],
    "voices": [
      1107101,
      1107110,
      1107111,
      1107112,
      1107113,
      1107109
    ],
    "battleBgm": [
      107
    ],
    "hero_tag": 107,
    "hero_task_group": [
      1010701,
      1010702
    ],
    "packaged_name": "魏武藏家",
    "packaged_title": "随机开示",
    "packaged_role_id": "caocao"
  },
  {
    "id": 108,
    "name": "hero_n_108",
    "gender": 1,
    "hero_class": "hero_c_108",
    "background": "hero_b_108",
    "hero_skill_name": "hero_skill_108",
    "hero_skill_description": "hero_dec_108",
    "hero_effect_description": "hero_effect_108",
    "cast_type": [
      100108
    ],
    "icon_path": "hero_xq_108",
    "icon_path2": "hero_xq_108",
    "icon_path3": "hero_bs_108_1",
    "illustration_path": "hero_xq_108",
    "bg_path": "hero_bg_108",
    "access": [
      2,
      380
    ],
    "voices": [
      1108101,
      1108110,
      1108111,
      1108112,
      1108113,
      1108109
    ],
    "battleBgm": [
      108
    ],
    "hero_tag": 108,
    "hero_task_group": [
      1010801,
      1010802
    ],
    "packaged_name": "弓腰鉴客",
    "packaged_title": "品质通读",
    "packaged_role_id": "sunshangxiang"
  },
  {
    "id": 109,
    "name": "hero_n_109",
    "gender": 1,
    "hero_class": "hero_c_109",
    "background": "hero_b_109",
    "hero_skill_name": "hero_skill_109",
    "hero_skill_description": "hero_dec_109",
    "hero_effect_description": "hero_effect_109",
    "cast_type": [
      100109,
      1001091,
      1001092,
      1001093,
      1001094
    ],
    "icon_path": "hero_xq_109",
    "icon_path2": "hero_xq_109",
    "icon_path3": "hero_bs_109_1",
    "illustration_path": "hero_xq_109",
    "bg_path": "hero_bg_109",
    "access": [
      2,
      380
    ],
    "voices": [
      1109101,
      1109110,
      1109111,
      1109112,
      1109113,
      1109109
    ],
    "battleBgm": [
      109
    ],
    "hero_tag": 109,
    "hero_task_group": [
      1010901,
      1010902
    ],
    "packaged_name": "义绝武库",
    "packaged_title": "兵装识别",
    "packaged_role_id": "guanyu"
  },
  {
    "id": 110,
    "name": "hero_n_110",
    "gender": 1,
    "hero_class": "hero_c_110",
    "background": "hero_b_110",
    "hero_skill_name": "hero_skill_110",
    "hero_skill_description": "hero_dec_110",
    "hero_effect_description": "hero_effect_110",
    "cast_type": [
      100110
    ],
    "icon_path": "hero_xq_110",
    "icon_path2": "hero_xq_110",
    "icon_path3": "hero_bs_110_1",
    "illustration_path": "hero_xq_110",
    "bg_path": "hero_bg_110",
    "access": [
      2,
      380
    ],
    "voices": [
      1110101,
      1110110,
      1110111,
      1110112,
      1110113,
      1110109
    ],
    "battleBgm": [
      110
    ],
    "hero_tag": 110,
    "hero_task_group": [
      1011001,
      1011002
    ],
    "packaged_name": "常胜护宝",
    "packaged_title": "价值极值",
    "packaged_role_id": "zhaoyun"
  },
  {
    "id": 201,
    "name": "hero_n_201",
    "gender": 2,
    "hero_class": "hero_c_201",
    "background": "hero_b_201",
    "hero_skill_name": "hero_skill_201",
    "hero_skill_description": "hero_dec_201",
    "hero_effect_description": "hero_effect_201",
    "cast_type": [
      100201
    ],
    "icon_path": "hero_xq_201",
    "icon_path2": "hero_xq_201",
    "icon_path3": "hero_bs_201_1",
    "illustration_path": "hero_xq_201",
    "bg_path": "hero_bg_201",
    "access": [
      2,
      380
    ],
    "voices": [
      1201101,
      1201110,
      1201111,
      1201112,
      1201113,
      1201109
    ],
    "battleBgm": [
      111
    ],
    "hero_tag": 201,
    "hero_task_group": [
      1020101,
      1020102
    ],
    "packaged_name": "玄德掌柜",
    "packaged_title": "军械识别",
    "packaged_role_id": "huangyueying"
  },
  {
    "id": 202,
    "name": "hero_n_202",
    "gender": 2,
    "hero_class": "hero_c_202",
    "background": "hero_b_202",
    "hero_skill_name": "hero_skill_202",
    "hero_skill_description": "hero_dec_202",
    "hero_effect_description": "hero_effect_202",
    "cast_type": [
      100202,
      1002021,
      1002022,
      1002023,
      1002024
    ],
    "icon_path": "hero_xq_202",
    "icon_path2": "hero_xq_202",
    "icon_path3": "hero_bs_202_1",
    "illustration_path": "hero_xq_202",
    "bg_path": "hero_bg_202",
    "access": [
      2,
      380
    ],
    "voices": [
      1202101,
      1202110,
      1202111,
      1202112,
      1202113,
      1202109
    ],
    "battleBgm": [
      112
    ],
    "hero_tag": 202,
    "hero_task_group": [
      1020201,
      1020202
    ],
    "packaged_name": "王佐评估",
    "packaged_title": "玉画追踪",
    "packaged_role_id": "xunyu"
  },
  {
    "id": 203,
    "name": "hero_n_203",
    "gender": 2,
    "hero_class": "hero_c_203",
    "background": "hero_b_203",
    "hero_skill_name": "hero_skill_203",
    "hero_skill_description": "hero_dec_203",
    "hero_effect_description": "hero_effect_203",
    "cast_type": [
      100203
    ],
    "icon_path": "hero_xq_203",
    "icon_path2": "hero_xq_203",
    "icon_path3": "hero_bs_203_1",
    "illustration_path": "hero_xq_203",
    "bg_path": "hero_bg_203",
    "access": [
      2,
      380
    ],
    "voices": [
      1203101,
      1203110,
      1203111,
      1203112,
      1203113,
      1203109
    ],
    "battleBgm": [
      113
    ],
    "hero_tag": 203,
    "hero_task_group": [
      1020301,
      1020302
    ],
    "packaged_name": "锦绣掌眼",
    "packaged_title": "织物识别",
    "packaged_role_id": "jiaxu"
  },
  {
    "id": 204,
    "name": "hero_n_204",
    "gender": 2,
    "hero_class": "hero_c_204",
    "background": "hero_b_204",
    "hero_skill_name": "hero_skill_204",
    "hero_skill_description": "hero_dec_204",
    "hero_effect_description": "hero_effect_204",
    "cast_type": [
      100204,
      1002041,
      1002042,
      1002043,
      1002044
    ],
    "icon_path": "hero_xq_204",
    "icon_path2": "hero_xq_204",
    "icon_path3": "hero_bs_204_1",
    "illustration_path": "hero_xq_204",
    "bg_path": "hero_bg_204",
    "access": [
      2,
      380
    ],
    "voices": [
      1204101,
      1204110,
      1204111,
      1204112,
      1204113,
      1204109
    ],
    "battleBgm": [
      114
    ],
    "hero_tag": 204,
    "hero_task_group": [
      1020401,
      1020402
    ],
    "packaged_name": "白衣行商",
    "packaged_title": "品质递进",
    "packaged_role_id": "lvmeng"
  },
  {
    "id": 205,
    "name": "hero_n_205",
    "gender": 2,
    "hero_class": "hero_c_205",
    "background": "hero_b_205",
    "hero_skill_name": "hero_skill_205",
    "hero_skill_description": "hero_dec_205",
    "hero_effect_description": "hero_effect_205",
    "cast_type": [
      100205
    ],
    "icon_path": "hero_xq_205",
    "icon_path2": "hero_xq_205",
    "icon_path3": "hero_bs_205_1",
    "illustration_path": "hero_xq_205",
    "bg_path": "hero_bg_205",
    "access": [
      2,
      380
    ],
    "voices": [
      1205101,
      1205110,
      1205111,
      1205112,
      1205113,
      1205109
    ],
    "battleBgm": [
      115
    ],
    "hero_tag": 205,
    "hero_task_group": [
      1020501,
      1020502
    ],
    "packaged_name": "虎将竞客",
    "packaged_title": "车马兵装",
    "packaged_role_id": "zhangfei"
  },
  {
    "id": 206,
    "name": "hero_n_206",
    "gender": 2,
    "hero_class": "hero_c_206",
    "background": "hero_b_206",
    "hero_skill_name": "hero_skill_206",
    "hero_skill_description": "hero_dec_206",
    "hero_effect_description": "hero_effect_206",
    "cast_type": [
      100206,
      1002062,
      1002063,
      1002064,
      1002065
    ],
    "icon_path": "hero_xq_206",
    "icon_path2": "hero_xq_206",
    "icon_path3": "hero_bs_206_1",
    "illustration_path": "hero_xq_206",
    "bg_path": "hero_bg_206",
    "access": [
      2,
      380
    ],
    "voices": [
      1206101,
      1206110,
      1206111,
      1206112,
      1206113,
      1206109
    ],
    "battleBgm": [
      116
    ],
    "hero_tag": 206,
    "hero_task_group": [
      1020601,
      1020602
    ],
    "packaged_name": "凤雏书鉴",
    "packaged_title": "书画识别",
    "packaged_role_id": "daqiao"
  },
  {
    "id": 207,
    "name": "hero_n_207",
    "gender": 2,
    "hero_class": "hero_c_207",
    "background": "hero_b_207",
    "hero_skill_name": "hero_skill_207",
    "hero_skill_description": "hero_dec_207",
    "hero_effect_description": "hero_effect_207",
    "cast_type": [
      100207,
      10002071,
      10002072,
      10002073
    ],
    "icon_path": "hero_xq_207",
    "icon_path2": "hero_xq_207",
    "icon_path3": "hero_bs_207_1",
    "illustration_path": "hero_xq_207",
    "bg_path": "hero_bg_207",
    "access": [
      2,
      380
    ],
    "voices": [
      1207101,
      1207110,
      1207111,
      1207112,
      1207113,
      1207109
    ],
    "battleBgm": [
      117
    ],
    "hero_tag": 207,
    "hero_task_group": [
      1020701,
      1020702
    ],
    "packaged_name": "水镜文士",
    "packaged_title": "古器追踪",
    "packaged_role_id": "xiaoqiao"
  },
  {
    "id": 208,
    "name": "hero_n_208",
    "gender": 2,
    "hero_class": "hero_c_208",
    "background": "hero_b_208",
    "hero_skill_name": "hero_skill_208",
    "hero_skill_description": "hero_dec_208",
    "hero_effect_description": "hero_effect_208",
    "cast_type": [
      1002081,
      1002082,
      1002083,
      1002084,
      1002085
    ],
    "icon_path": "hero_xq_208",
    "icon_path2": "hero_xq_208",
    "icon_path3": "hero_bs_208_1",
    "illustration_path": "hero_xq_208",
    "bg_path": "hero_bg_208",
    "access": [
      2,
      380
    ],
    "voices": [
      1208101,
      1208110,
      1208111,
      1208112,
      1208113,
      1208109
    ],
    "battleBgm": [
      118
    ],
    "hero_tag": 208,
    "hero_task_group": [
      1020801,
      1020802,
      1020803
    ],
    "packaged_name": "巧思工师",
    "packaged_title": "全局估值",
    "packaged_role_id": "machao"
  },
  {
    "id": 209,
    "name": "hero_n_209",
    "gender": 2,
    "hero_class": "hero_c_209",
    "background": "hero_b_209",
    "hero_skill_name": "hero_skill_209",
    "hero_skill_description": "hero_dec_209",
    "hero_effect_description": "hero_effect_209",
    "cast_type": [
      100209
    ],
    "icon_path": "hero_xq_209",
    "icon_path2": "hero_xq_209",
    "icon_path3": "hero_bs_209_1",
    "illustration_path": "hero_xq_209",
    "bg_path": "hero_bg_209",
    "access": [
      2,
      380
    ],
    "voices": [
      1209101,
      1209110,
      1209111,
      1209112,
      1209113,
      1209109
    ],
    "battleBgm": [
      119
    ],
    "hero_tag": 209,
    "hero_task_group": [
      1020901,
      1020902
    ],
    "packaged_name": "西凉骑鉴",
    "packaged_title": "高阶品质",
    "packaged_role_id": "huangzhong"
  },
  {
    "id": 301,
    "name": "hero_n_301",
    "gender": 0,
    "hero_class": "hero_c_301",
    "background": "hero_b_301",
    "hero_skill_name": "hero_skill_301",
    "hero_skill_description": "hero_dec_301",
    "hero_effect_description": "hero_effect_301",
    "cast_type": [
      0,
      0,
      0,
      0,
      100301
    ],
    "icon_path": "hero_xq_301",
    "icon_path2": "hero_xq_301",
    "icon_path3": "hero_bs_301_1",
    "illustration_path": "hero_xq_301",
    "bg_path": "hero_bg_301",
    "access": [
      2,
      380
    ],
    "voices": [
      1301101,
      1301110,
      1301111,
      1301112,
      1301113,
      1301109
    ],
    "battleBgm": [
      120
    ],
    "hero_tag": 301,
    "hero_task_group": [
      1030101,
      1030102
    ],
    "packaged_name": "洛阳名士",
    "packaged_title": "随机洞察",
    "packaged_role_id": "pangtong"
  }
];
