// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingItemTypeRow } from '../schema';

export const ItemType: BidKingItemTypeRow[] = [
  {
    "id": 1,
    "configFileName": "Item",
    "type_name": "item_Type_1",
    "showin_tradingbuy": 0,
    "showin_auction": 1,
    "store_type": 0,
    "icon": "",
    "packaged_name": "杂项",
    "packaged_source_name": "基础道具"
  },
  {
    "id": 2,
    "configFileName": "Item",
    "type_name": "item_Type_2",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 1,
    "icon": "",
    "packaged_name": "券契",
    "packaged_source_name": "竞拍票券"
  },
  {
    "id": 3,
    "configFileName": "Item",
    "type_name": "item_Type_3",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 1,
    "icon": "",
    "packaged_name": "令牌",
    "packaged_source_name": "特殊道具"
  },
  {
    "id": 4,
    "configFileName": "Item",
    "type_name": "item_Type_4",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 0,
    "icon": "",
    "packaged_name": "宝匣",
    "packaged_source_name": "随机宝箱"
  },
  {
    "id": 5,
    "configFileName": "Item",
    "type_name": "item_Type_5",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "封匣",
    "packaged_source_name": "指定宝箱"
  },
  {
    "id": 6,
    "configFileName": "Item",
    "type_name": "item_Type_6",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "陈列柜",
    "packaged_source_name": "收藏柜"
  },
  {
    "id": 7,
    "configFileName": "Item",
    "type_name": "item_Type_7",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "库箱",
    "packaged_source_name": "仓库盒"
  },
  {
    "id": 8,
    "configFileName": "Item",
    "type_name": "item_Type_8",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 0,
    "icon": "",
    "packaged_name": "演武宝藏",
    "packaged_source_name": "模拟宝藏"
  },
  {
    "id": 11,
    "configFileName": "Item",
    "type_name": "item_Type_11",
    "showin_tradingbuy": 1,
    "showin_auction": 0,
    "store_type": 1,
    "icon": "box_11",
    "packaged_name": "军令消耗",
    "packaged_source_name": "消耗型道具"
  },
  {
    "id": 12,
    "configFileName": "Item",
    "type_name": "item_Type_12",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "名刺",
    "packaged_source_name": "头像"
  },
  {
    "id": 13,
    "configFileName": "Item",
    "type_name": "item_Type_13",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "功勋",
    "packaged_source_name": "成就勋章"
  },
  {
    "id": 14,
    "configFileName": "Item",
    "type_name": "item_Type_14",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "衣装",
    "packaged_source_name": "皮肤"
  },
  {
    "id": 15,
    "configFileName": "item",
    "type_name": "item_Type_15",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "竞买人",
    "packaged_source_name": "角色"
  },
  {
    "id": 16,
    "configFileName": "item",
    "type_name": "item_Type_16",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "更名牒",
    "packaged_source_name": "改名卡"
  },
  {
    "id": 17,
    "configFileName": "item",
    "type_name": "item_Type_17",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "表情",
    "packaged_source_name": "表情"
  },
  {
    "id": 18,
    "configFileName": "item",
    "type_name": "item_Type_18",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "称号",
    "packaged_source_name": "称号"
  },
  {
    "id": 19,
    "configFileName": "item",
    "type_name": "item_Type_19",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 2,
    "icon": "",
    "packaged_name": "体验牌",
    "packaged_source_name": "体验卡"
  },
  {
    "id": 101,
    "configFileName": "Item",
    "type_name": "item_Type_101",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_100",
    "packaged_name": "府邸日用",
    "packaged_source_name": "家居日用"
  },
  {
    "id": 102,
    "configFileName": "Item",
    "type_name": "item_Type_102",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_101",
    "packaged_name": "医药军需",
    "packaged_source_name": "医疗用品"
  },
  {
    "id": 103,
    "configFileName": "Item",
    "type_name": "item_Type_103",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_102",
    "packaged_name": "锦衣冠服",
    "packaged_source_name": "时尚潮流"
  },
  {
    "id": 104,
    "configFileName": "Item",
    "type_name": "item_Type_104",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_103",
    "packaged_name": "军械兵装",
    "packaged_source_name": "武器装备"
  },
  {
    "id": 105,
    "configFileName": "Item",
    "type_name": "item_Type_105",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_104",
    "packaged_name": "矿玉珠宝",
    "packaged_source_name": "矿物珠宝"
  },
  {
    "id": 106,
    "configFileName": "Item",
    "type_name": "item_Type_106",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_105",
    "packaged_name": "文玩古器",
    "packaged_source_name": "文玩古董"
  },
  {
    "id": 107,
    "configFileName": "Item",
    "type_name": "item_Type_107",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_106",
    "packaged_name": "机巧器具",
    "packaged_source_name": "数码电子"
  },
  {
    "id": 108,
    "configFileName": "Item",
    "type_name": "item_Type_108",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_107",
    "packaged_name": "车马舟楫",
    "packaged_source_name": "交通工具"
  },
  {
    "id": 109,
    "configFileName": "Item",
    "type_name": "item_Type_109",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_108",
    "packaged_name": "酒食香料",
    "packaged_source_name": "食品烹饪"
  },
  {
    "id": 110,
    "configFileName": "Item",
    "type_name": "item_Type_110",
    "showin_tradingbuy": 1,
    "showin_auction": 1,
    "store_type": 1,
    "icon": "box_109",
    "packaged_name": "书画典籍",
    "packaged_source_name": "书籍绘画"
  },
  {
    "id": 100,
    "configFileName": "item",
    "type_name": "item_Type_100",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 1,
    "icon": "box_110",
    "packaged_name": "秘藏",
    "packaged_source_name": "特殊藏品"
  },
  {
    "id": 9999,
    "configFileName": "Drop",
    "type_name": "item_Type_9999",
    "showin_tradingbuy": 0,
    "showin_auction": 0,
    "store_type": 0,
    "icon": "",
    "packaged_name": "分类9999",
    "packaged_source_name": "类型9999"
  }
];
