// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingLevelUpRow } from '../schema';

export const LevelUp: BidKingLevelUpRow[] = [
  {
    "id": 1,
    "collection_value": 100,
    "level_reward": [
      [
        1,
        10000
      ]
    ],
    "bass_value": 50,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1410702,
        1
      ],
      [
        120704,
        1
      ],
      [
        140701,
        1
      ]
    ],
    "packaged_name": "掌柜等级 1",
    "reward_summary": "无奖励"
  },
  {
    "id": 2,
    "collection_value": 400,
    "level_reward": [
      [
        100129,
        5
      ]
    ],
    "bass_value": 100,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 2",
    "reward_summary": "无奖励"
  },
  {
    "id": 3,
    "collection_value": 1000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 150,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 3",
    "reward_summary": "无奖励"
  },
  {
    "id": 4,
    "collection_value": 2100,
    "level_reward": [
      [
        100136,
        5
      ]
    ],
    "bass_value": 200,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 4",
    "reward_summary": "无奖励"
  },
  {
    "id": 5,
    "collection_value": 3900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 250,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 5",
    "reward_summary": "无奖励"
  },
  {
    "id": 6,
    "collection_value": 6600,
    "level_reward": [
      [
        103,
        2
      ]
    ],
    "bass_value": 300,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 6",
    "reward_summary": "无奖励"
  },
  {
    "id": 7,
    "collection_value": 10400,
    "level_reward": [
      [
        100102,
        3
      ]
    ],
    "bass_value": 350,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 7",
    "reward_summary": "无奖励"
  },
  {
    "id": 8,
    "collection_value": 15500,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 400,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 8",
    "reward_summary": "无奖励"
  },
  {
    "id": 9,
    "collection_value": 22100,
    "level_reward": [
      [
        100131,
        3
      ]
    ],
    "bass_value": 450,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 9",
    "reward_summary": "无奖励"
  },
  {
    "id": 10,
    "collection_value": 30400,
    "level_reward": [
      [
        1001,
        1
      ]
    ],
    "bass_value": 500,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 10",
    "reward_summary": "无奖励"
  },
  {
    "id": 11,
    "collection_value": 40600,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 550,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 11",
    "reward_summary": "无奖励"
  },
  {
    "id": 12,
    "collection_value": 52900,
    "level_reward": [
      [
        100166,
        3
      ]
    ],
    "bass_value": 600,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 12",
    "reward_summary": "无奖励"
  },
  {
    "id": 13,
    "collection_value": 67500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 650,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 13",
    "reward_summary": "无奖励"
  },
  {
    "id": 14,
    "collection_value": 84600,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 700,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 14",
    "reward_summary": "无奖励"
  },
  {
    "id": 15,
    "collection_value": 104400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 750,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 15",
    "reward_summary": "无奖励"
  },
  {
    "id": 16,
    "collection_value": 127100,
    "level_reward": [
      [
        100138,
        3
      ]
    ],
    "bass_value": 800,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 16",
    "reward_summary": "无奖励"
  },
  {
    "id": 17,
    "collection_value": 152900,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 850,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 17",
    "reward_summary": "无奖励"
  },
  {
    "id": 18,
    "collection_value": 182000,
    "level_reward": [
      [
        103,
        2
      ]
    ],
    "bass_value": 900,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 18",
    "reward_summary": "无奖励"
  },
  {
    "id": 19,
    "collection_value": 214600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 950,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 19",
    "reward_summary": "无奖励"
  },
  {
    "id": 20,
    "collection_value": 250900,
    "level_reward": [
      [
        1001,
        1
      ]
    ],
    "bass_value": 1000,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 20",
    "reward_summary": "无奖励"
  },
  {
    "id": 21,
    "collection_value": 291100,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 1050,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 21",
    "reward_summary": "无奖励"
  },
  {
    "id": 22,
    "collection_value": 335400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 1100,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 22",
    "reward_summary": "无奖励"
  },
  {
    "id": 23,
    "collection_value": 384000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 1150,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 23",
    "reward_summary": "无奖励"
  },
  {
    "id": 24,
    "collection_value": 437100,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 1200,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 24",
    "reward_summary": "无奖励"
  },
  {
    "id": 25,
    "collection_value": 494900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 1250,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 25",
    "reward_summary": "无奖励"
  },
  {
    "id": 26,
    "collection_value": 557600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 1300,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 26",
    "reward_summary": "无奖励"
  },
  {
    "id": 27,
    "collection_value": 625400,
    "level_reward": [
      [
        1,
        30000
      ]
    ],
    "bass_value": 1350,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 27",
    "reward_summary": "无奖励"
  },
  {
    "id": 28,
    "collection_value": 698500,
    "level_reward": [
      [
        104,
        1
      ]
    ],
    "bass_value": 1400,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 28",
    "reward_summary": "无奖励"
  },
  {
    "id": 29,
    "collection_value": 777100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 1450,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 29",
    "reward_summary": "无奖励"
  },
  {
    "id": 30,
    "collection_value": 861400,
    "level_reward": [
      [
        1001,
        1
      ]
    ],
    "bass_value": 1500,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 30",
    "reward_summary": "无奖励"
  },
  {
    "id": 31,
    "collection_value": 951600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 1550,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 31",
    "reward_summary": "无奖励"
  },
  {
    "id": 32,
    "collection_value": 1047900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 1600,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 32",
    "reward_summary": "无奖励"
  },
  {
    "id": 33,
    "collection_value": 1150500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 1650,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 33",
    "reward_summary": "无奖励"
  },
  {
    "id": 34,
    "collection_value": 1259600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 1700,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 34",
    "reward_summary": "无奖励"
  },
  {
    "id": 35,
    "collection_value": 1375400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 1750,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 35",
    "reward_summary": "无奖励"
  },
  {
    "id": 36,
    "collection_value": 1498100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 1800,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 36",
    "reward_summary": "无奖励"
  },
  {
    "id": 37,
    "collection_value": 1627900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 1850,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 37",
    "reward_summary": "无奖励"
  },
  {
    "id": 38,
    "collection_value": 1765000,
    "level_reward": [
      [
        104,
        1
      ]
    ],
    "bass_value": 1900,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 38",
    "reward_summary": "无奖励"
  },
  {
    "id": 39,
    "collection_value": 1909600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 1950,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 39",
    "reward_summary": "无奖励"
  },
  {
    "id": 40,
    "collection_value": 2061900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 2000,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 40",
    "reward_summary": "无奖励"
  },
  {
    "id": 41,
    "collection_value": 2222100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2050,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 41",
    "reward_summary": "无奖励"
  },
  {
    "id": 42,
    "collection_value": 2390400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 2100,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 42",
    "reward_summary": "无奖励"
  },
  {
    "id": 43,
    "collection_value": 2567000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 2150,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 43",
    "reward_summary": "无奖励"
  },
  {
    "id": 44,
    "collection_value": 2752100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2200,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 44",
    "reward_summary": "无奖励"
  },
  {
    "id": 45,
    "collection_value": 2945900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 2250,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 45",
    "reward_summary": "无奖励"
  },
  {
    "id": 46,
    "collection_value": 3148600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 2300,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 46",
    "reward_summary": "无奖励"
  },
  {
    "id": 47,
    "collection_value": 3360400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2350,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 47",
    "reward_summary": "无奖励"
  },
  {
    "id": 48,
    "collection_value": 3581500,
    "level_reward": [
      [
        104,
        1
      ]
    ],
    "bass_value": 2400,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 48",
    "reward_summary": "无奖励"
  },
  {
    "id": 49,
    "collection_value": 3812100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 2450,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 49",
    "reward_summary": "无奖励"
  },
  {
    "id": 50,
    "collection_value": 4052400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 2500,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 50",
    "reward_summary": "无奖励"
  },
  {
    "id": 51,
    "collection_value": 4302600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2550,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 51",
    "reward_summary": "无奖励"
  },
  {
    "id": 52,
    "collection_value": 4562900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 2600,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 52",
    "reward_summary": "无奖励"
  },
  {
    "id": 53,
    "collection_value": 4833500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 2650,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 53",
    "reward_summary": "无奖励"
  },
  {
    "id": 54,
    "collection_value": 5114600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2700,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 54",
    "reward_summary": "无奖励"
  },
  {
    "id": 55,
    "collection_value": 5406400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 2750,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 55",
    "reward_summary": "无奖励"
  },
  {
    "id": 56,
    "collection_value": 5709100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 2800,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 56",
    "reward_summary": "无奖励"
  },
  {
    "id": 57,
    "collection_value": 6022900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 2850,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 57",
    "reward_summary": "无奖励"
  },
  {
    "id": 58,
    "collection_value": 6348000,
    "level_reward": [
      [
        105,
        1
      ]
    ],
    "bass_value": 2900,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 58",
    "reward_summary": "无奖励"
  },
  {
    "id": 59,
    "collection_value": 6684600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 2950,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 59",
    "reward_summary": "无奖励"
  },
  {
    "id": 60,
    "collection_value": 7032900,
    "level_reward": [
      [
        120001,
        1
      ]
    ],
    "bass_value": 3000,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 60",
    "reward_summary": "无奖励"
  },
  {
    "id": 61,
    "collection_value": 7393100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3050,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 61",
    "reward_summary": "无奖励"
  },
  {
    "id": 62,
    "collection_value": 7765400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 3100,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 62",
    "reward_summary": "无奖励"
  },
  {
    "id": 63,
    "collection_value": 8150000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 3150,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 63",
    "reward_summary": "无奖励"
  },
  {
    "id": 64,
    "collection_value": 8547100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3200,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 64",
    "reward_summary": "无奖励"
  },
  {
    "id": 65,
    "collection_value": 8956900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 3250,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 65",
    "reward_summary": "无奖励"
  },
  {
    "id": 66,
    "collection_value": 9379600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 3300,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 66",
    "reward_summary": "无奖励"
  },
  {
    "id": 67,
    "collection_value": 9815400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3350,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 67",
    "reward_summary": "无奖励"
  },
  {
    "id": 68,
    "collection_value": 10264500,
    "level_reward": [
      [
        105,
        1
      ]
    ],
    "bass_value": 3400,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 68",
    "reward_summary": "无奖励"
  },
  {
    "id": 69,
    "collection_value": 10727100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 3450,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 69",
    "reward_summary": "无奖励"
  },
  {
    "id": 70,
    "collection_value": 11203400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 3500,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 70",
    "reward_summary": "无奖励"
  },
  {
    "id": 71,
    "collection_value": 11693600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3550,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 71",
    "reward_summary": "无奖励"
  },
  {
    "id": 72,
    "collection_value": 12197900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 3600,
    "bass_reward": [
      [
        1,
        30000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 72",
    "reward_summary": "无奖励"
  },
  {
    "id": 73,
    "collection_value": 12716500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 3650,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ],
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 73",
    "reward_summary": "无奖励"
  },
  {
    "id": 74,
    "collection_value": 13249600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3700,
    "bass_reward": [
      [
        7001,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 74",
    "reward_summary": "无奖励"
  },
  {
    "id": 75,
    "collection_value": 13797400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 3750,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7001,
        1
      ],
      [
        7002,
        1
      ]
    ],
    "packaged_name": "掌柜等级 75",
    "reward_summary": "无奖励"
  },
  {
    "id": 76,
    "collection_value": 14360100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 3800,
    "bass_reward": [
      [
        102,
        1
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 76",
    "reward_summary": "无奖励"
  },
  {
    "id": 77,
    "collection_value": 14937900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 3850,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        102,
        1
      ],
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 77",
    "reward_summary": "无奖励"
  },
  {
    "id": 78,
    "collection_value": 15531000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 3900,
    "bass_reward": [
      [
        7002,
        2
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 78",
    "reward_summary": "无奖励"
  },
  {
    "id": 79,
    "collection_value": 16139600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 3950,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        7002,
        1
      ],
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 79",
    "reward_summary": "无奖励"
  },
  {
    "id": 80,
    "collection_value": 16763900,
    "level_reward": [
      [
        140002,
        1
      ]
    ],
    "bass_value": 4000,
    "bass_reward": [
      [
        7201,
        1
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ],
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 80",
    "reward_summary": "无奖励"
  },
  {
    "id": 81,
    "collection_value": 17404100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4050,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 81",
    "reward_summary": "无奖励"
  },
  {
    "id": 82,
    "collection_value": 18060400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 4100,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 82",
    "reward_summary": "无奖励"
  },
  {
    "id": 83,
    "collection_value": 18733000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 4150,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 83",
    "reward_summary": "无奖励"
  },
  {
    "id": 84,
    "collection_value": 19422100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4200,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 84",
    "reward_summary": "无奖励"
  },
  {
    "id": 85,
    "collection_value": 20127900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 4250,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 85",
    "reward_summary": "无奖励"
  },
  {
    "id": 86,
    "collection_value": 20850600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 4300,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 86",
    "reward_summary": "无奖励"
  },
  {
    "id": 87,
    "collection_value": 21590400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4350,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 87",
    "reward_summary": "无奖励"
  },
  {
    "id": 88,
    "collection_value": 22347500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 4400,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 88",
    "reward_summary": "无奖励"
  },
  {
    "id": 89,
    "collection_value": 23122100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 4450,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 89",
    "reward_summary": "无奖励"
  },
  {
    "id": 90,
    "collection_value": 23914400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 4500,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 90",
    "reward_summary": "无奖励"
  },
  {
    "id": 91,
    "collection_value": 24724600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4550,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 91",
    "reward_summary": "无奖励"
  },
  {
    "id": 92,
    "collection_value": 25552900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 4600,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 92",
    "reward_summary": "无奖励"
  },
  {
    "id": 93,
    "collection_value": 26399500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 4650,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 93",
    "reward_summary": "无奖励"
  },
  {
    "id": 94,
    "collection_value": 27264600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4700,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 94",
    "reward_summary": "无奖励"
  },
  {
    "id": 95,
    "collection_value": 28148400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 4750,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 95",
    "reward_summary": "无奖励"
  },
  {
    "id": 96,
    "collection_value": 29051100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 4800,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 96",
    "reward_summary": "无奖励"
  },
  {
    "id": 97,
    "collection_value": 29972900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 4850,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 97",
    "reward_summary": "无奖励"
  },
  {
    "id": 98,
    "collection_value": 30914000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 4900,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 98",
    "reward_summary": "无奖励"
  },
  {
    "id": 99,
    "collection_value": 31874600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 4950,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 99",
    "reward_summary": "无奖励"
  },
  {
    "id": 100,
    "collection_value": 32854900,
    "level_reward": [
      [
        150002,
        1
      ]
    ],
    "bass_value": 5000,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 100",
    "reward_summary": "无奖励"
  },
  {
    "id": 101,
    "collection_value": 33855100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5050,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 101",
    "reward_summary": "无奖励"
  },
  {
    "id": 102,
    "collection_value": 34875400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 5100,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 102",
    "reward_summary": "无奖励"
  },
  {
    "id": 103,
    "collection_value": 35916000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 5150,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 103",
    "reward_summary": "无奖励"
  },
  {
    "id": 104,
    "collection_value": 36977100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5200,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 104",
    "reward_summary": "无奖励"
  },
  {
    "id": 105,
    "collection_value": 38058900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 5250,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 105",
    "reward_summary": "无奖励"
  },
  {
    "id": 106,
    "collection_value": 39161600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 5300,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 106",
    "reward_summary": "无奖励"
  },
  {
    "id": 107,
    "collection_value": 40285400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5350,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 107",
    "reward_summary": "无奖励"
  },
  {
    "id": 108,
    "collection_value": 41430500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 5400,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 108",
    "reward_summary": "无奖励"
  },
  {
    "id": 109,
    "collection_value": 42597100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 5450,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        104,
        1
      ]
    ],
    "packaged_name": "掌柜等级 109",
    "reward_summary": "无奖励"
  },
  {
    "id": 110,
    "collection_value": 43785400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 5500,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 110",
    "reward_summary": "无奖励"
  },
  {
    "id": 111,
    "collection_value": 44995600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5550,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 111",
    "reward_summary": "无奖励"
  },
  {
    "id": 112,
    "collection_value": 46227900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 5600,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        105,
        1
      ]
    ],
    "packaged_name": "掌柜等级 112",
    "reward_summary": "无奖励"
  },
  {
    "id": 113,
    "collection_value": 47482500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 5650,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 113",
    "reward_summary": "无奖励"
  },
  {
    "id": 114,
    "collection_value": 48759600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5700,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 114",
    "reward_summary": "无奖励"
  },
  {
    "id": 115,
    "collection_value": 50059400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 5750,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        106,
        1
      ]
    ],
    "packaged_name": "掌柜等级 115",
    "reward_summary": "无奖励"
  },
  {
    "id": 116,
    "collection_value": 51382100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 5800,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 116",
    "reward_summary": "无奖励"
  },
  {
    "id": 117,
    "collection_value": 52727900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 5850,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 117",
    "reward_summary": "无奖励"
  },
  {
    "id": 118,
    "collection_value": 54097000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 5900,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        103,
        1
      ]
    ],
    "packaged_name": "掌柜等级 118",
    "reward_summary": "无奖励"
  },
  {
    "id": 119,
    "collection_value": 55489600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 5950,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7003,
        1
      ]
    ],
    "packaged_name": "掌柜等级 119",
    "reward_summary": "无奖励"
  },
  {
    "id": 120,
    "collection_value": 56905900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 6000,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        7201,
        1
      ]
    ],
    "packaged_name": "掌柜等级 120",
    "reward_summary": "无奖励"
  },
  {
    "id": 121,
    "collection_value": 58346100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6050,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 121",
    "reward_summary": "无奖励"
  },
  {
    "id": 122,
    "collection_value": 59810400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 6100,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 122",
    "reward_summary": "无奖励"
  },
  {
    "id": 123,
    "collection_value": 61299000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 6150,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 123",
    "reward_summary": "无奖励"
  },
  {
    "id": 124,
    "collection_value": 62812100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6200,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 124",
    "reward_summary": "无奖励"
  },
  {
    "id": 125,
    "collection_value": 64349900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 6250,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 125",
    "reward_summary": "无奖励"
  },
  {
    "id": 126,
    "collection_value": 65912600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 6300,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 126",
    "reward_summary": "无奖励"
  },
  {
    "id": 127,
    "collection_value": 67500400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6350,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 127",
    "reward_summary": "无奖励"
  },
  {
    "id": 128,
    "collection_value": 69113500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 6400,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 128",
    "reward_summary": "无奖励"
  },
  {
    "id": 129,
    "collection_value": 70752100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 6450,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 129",
    "reward_summary": "无奖励"
  },
  {
    "id": 130,
    "collection_value": 72416400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 6500,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 130",
    "reward_summary": "无奖励"
  },
  {
    "id": 131,
    "collection_value": 74106600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6550,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 131",
    "reward_summary": "无奖励"
  },
  {
    "id": 132,
    "collection_value": 75822900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 6600,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 132",
    "reward_summary": "无奖励"
  },
  {
    "id": 133,
    "collection_value": 77565500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 6650,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 133",
    "reward_summary": "无奖励"
  },
  {
    "id": 134,
    "collection_value": 79334600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6700,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 134",
    "reward_summary": "无奖励"
  },
  {
    "id": 135,
    "collection_value": 81130400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 6750,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 135",
    "reward_summary": "无奖励"
  },
  {
    "id": 136,
    "collection_value": 82953100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 6800,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 136",
    "reward_summary": "无奖励"
  },
  {
    "id": 137,
    "collection_value": 84802900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 6850,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 137",
    "reward_summary": "无奖励"
  },
  {
    "id": 138,
    "collection_value": 86680000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 6900,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 138",
    "reward_summary": "无奖励"
  },
  {
    "id": 139,
    "collection_value": 88584600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 6950,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 139",
    "reward_summary": "无奖励"
  },
  {
    "id": 140,
    "collection_value": 90516900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 7000,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 140",
    "reward_summary": "无奖励"
  },
  {
    "id": 141,
    "collection_value": 92477100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 7050,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 141",
    "reward_summary": "无奖励"
  },
  {
    "id": 142,
    "collection_value": 94465400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 7100,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 142",
    "reward_summary": "无奖励"
  },
  {
    "id": 143,
    "collection_value": 96482000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 7150,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 143",
    "reward_summary": "无奖励"
  },
  {
    "id": 144,
    "collection_value": 98527100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 7200,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 144",
    "reward_summary": "无奖励"
  },
  {
    "id": 145,
    "collection_value": 100600900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 7250,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 145",
    "reward_summary": "无奖励"
  },
  {
    "id": 146,
    "collection_value": 102703600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 7300,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 146",
    "reward_summary": "无奖励"
  },
  {
    "id": 147,
    "collection_value": 104835400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 7350,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 147",
    "reward_summary": "无奖励"
  },
  {
    "id": 148,
    "collection_value": 106996500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 7400,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 148",
    "reward_summary": "无奖励"
  },
  {
    "id": 149,
    "collection_value": 109187100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 7450,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 149",
    "reward_summary": "无奖励"
  },
  {
    "id": 150,
    "collection_value": 111407400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 7500,
    "bass_reward": [
      [
        1,
        10000
      ]
    ],
    "big_bass_reward": [
      [
        1,
        50000
      ]
    ],
    "packaged_name": "掌柜等级 150",
    "reward_summary": "无奖励"
  },
  {
    "id": 151,
    "collection_value": 113657600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 151",
    "reward_summary": "无奖励"
  },
  {
    "id": 152,
    "collection_value": 115937900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 152",
    "reward_summary": "无奖励"
  },
  {
    "id": 153,
    "collection_value": 118248500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 153",
    "reward_summary": "无奖励"
  },
  {
    "id": 154,
    "collection_value": 120589600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 154",
    "reward_summary": "无奖励"
  },
  {
    "id": 155,
    "collection_value": 122961400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 155",
    "reward_summary": "无奖励"
  },
  {
    "id": 156,
    "collection_value": 125364100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 156",
    "reward_summary": "无奖励"
  },
  {
    "id": 157,
    "collection_value": 127797900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 157",
    "reward_summary": "无奖励"
  },
  {
    "id": 158,
    "collection_value": 130263000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 158",
    "reward_summary": "无奖励"
  },
  {
    "id": 159,
    "collection_value": 132759600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 159",
    "reward_summary": "无奖励"
  },
  {
    "id": 160,
    "collection_value": 135287900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 160",
    "reward_summary": "无奖励"
  },
  {
    "id": 161,
    "collection_value": 137848100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 161",
    "reward_summary": "无奖励"
  },
  {
    "id": 162,
    "collection_value": 140440400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 162",
    "reward_summary": "无奖励"
  },
  {
    "id": 163,
    "collection_value": 143065000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 163",
    "reward_summary": "无奖励"
  },
  {
    "id": 164,
    "collection_value": 145722100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 164",
    "reward_summary": "无奖励"
  },
  {
    "id": 165,
    "collection_value": 148411900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 165",
    "reward_summary": "无奖励"
  },
  {
    "id": 166,
    "collection_value": 151134600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 166",
    "reward_summary": "无奖励"
  },
  {
    "id": 167,
    "collection_value": 153890400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 167",
    "reward_summary": "无奖励"
  },
  {
    "id": 168,
    "collection_value": 156679500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 168",
    "reward_summary": "无奖励"
  },
  {
    "id": 169,
    "collection_value": 159502100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 169",
    "reward_summary": "无奖励"
  },
  {
    "id": 170,
    "collection_value": 162358400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 170",
    "reward_summary": "无奖励"
  },
  {
    "id": 171,
    "collection_value": 165248600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 171",
    "reward_summary": "无奖励"
  },
  {
    "id": 172,
    "collection_value": 168172900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 172",
    "reward_summary": "无奖励"
  },
  {
    "id": 173,
    "collection_value": 171131500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 173",
    "reward_summary": "无奖励"
  },
  {
    "id": 174,
    "collection_value": 174124600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 174",
    "reward_summary": "无奖励"
  },
  {
    "id": 175,
    "collection_value": 177152400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 175",
    "reward_summary": "无奖励"
  },
  {
    "id": 176,
    "collection_value": 180215100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 176",
    "reward_summary": "无奖励"
  },
  {
    "id": 177,
    "collection_value": 183312900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 177",
    "reward_summary": "无奖励"
  },
  {
    "id": 178,
    "collection_value": 186446000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 178",
    "reward_summary": "无奖励"
  },
  {
    "id": 179,
    "collection_value": 189614600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 179",
    "reward_summary": "无奖励"
  },
  {
    "id": 180,
    "collection_value": 192818900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 180",
    "reward_summary": "无奖励"
  },
  {
    "id": 181,
    "collection_value": 196059100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 181",
    "reward_summary": "无奖励"
  },
  {
    "id": 182,
    "collection_value": 199335400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 182",
    "reward_summary": "无奖励"
  },
  {
    "id": 183,
    "collection_value": 202648000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 183",
    "reward_summary": "无奖励"
  },
  {
    "id": 184,
    "collection_value": 205997100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 184",
    "reward_summary": "无奖励"
  },
  {
    "id": 185,
    "collection_value": 209382900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 185",
    "reward_summary": "无奖励"
  },
  {
    "id": 186,
    "collection_value": 212805600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 186",
    "reward_summary": "无奖励"
  },
  {
    "id": 187,
    "collection_value": 216265400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 187",
    "reward_summary": "无奖励"
  },
  {
    "id": 188,
    "collection_value": 219762500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 188",
    "reward_summary": "无奖励"
  },
  {
    "id": 189,
    "collection_value": 223297100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 189",
    "reward_summary": "无奖励"
  },
  {
    "id": 190,
    "collection_value": 226869400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 190",
    "reward_summary": "无奖励"
  },
  {
    "id": 191,
    "collection_value": 230479600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 191",
    "reward_summary": "无奖励"
  },
  {
    "id": 192,
    "collection_value": 234127900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 192",
    "reward_summary": "无奖励"
  },
  {
    "id": 193,
    "collection_value": 237814500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 193",
    "reward_summary": "无奖励"
  },
  {
    "id": 194,
    "collection_value": 241539600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 194",
    "reward_summary": "无奖励"
  },
  {
    "id": 195,
    "collection_value": 245303400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 195",
    "reward_summary": "无奖励"
  },
  {
    "id": 196,
    "collection_value": 249106100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 196",
    "reward_summary": "无奖励"
  },
  {
    "id": 197,
    "collection_value": 252947900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 197",
    "reward_summary": "无奖励"
  },
  {
    "id": 198,
    "collection_value": 256829000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 198",
    "reward_summary": "无奖励"
  },
  {
    "id": 199,
    "collection_value": 260749600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 199",
    "reward_summary": "无奖励"
  },
  {
    "id": 200,
    "collection_value": 264709900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 200",
    "reward_summary": "无奖励"
  },
  {
    "id": 201,
    "collection_value": 268710100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 201",
    "reward_summary": "无奖励"
  },
  {
    "id": 202,
    "collection_value": 272750400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 202",
    "reward_summary": "无奖励"
  },
  {
    "id": 203,
    "collection_value": 276831000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 203",
    "reward_summary": "无奖励"
  },
  {
    "id": 204,
    "collection_value": 280952100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 204",
    "reward_summary": "无奖励"
  },
  {
    "id": 205,
    "collection_value": 285113900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 205",
    "reward_summary": "无奖励"
  },
  {
    "id": 206,
    "collection_value": 289316600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 206",
    "reward_summary": "无奖励"
  },
  {
    "id": 207,
    "collection_value": 293560400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 207",
    "reward_summary": "无奖励"
  },
  {
    "id": 208,
    "collection_value": 297845500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 208",
    "reward_summary": "无奖励"
  },
  {
    "id": 209,
    "collection_value": 302172100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 209",
    "reward_summary": "无奖励"
  },
  {
    "id": 210,
    "collection_value": 306540400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 210",
    "reward_summary": "无奖励"
  },
  {
    "id": 211,
    "collection_value": 310950600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 211",
    "reward_summary": "无奖励"
  },
  {
    "id": 212,
    "collection_value": 315402900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 212",
    "reward_summary": "无奖励"
  },
  {
    "id": 213,
    "collection_value": 319897500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 213",
    "reward_summary": "无奖励"
  },
  {
    "id": 214,
    "collection_value": 324434600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 214",
    "reward_summary": "无奖励"
  },
  {
    "id": 215,
    "collection_value": 329014400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 215",
    "reward_summary": "无奖励"
  },
  {
    "id": 216,
    "collection_value": 333637100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 216",
    "reward_summary": "无奖励"
  },
  {
    "id": 217,
    "collection_value": 338302900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 217",
    "reward_summary": "无奖励"
  },
  {
    "id": 218,
    "collection_value": 343012000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 218",
    "reward_summary": "无奖励"
  },
  {
    "id": 219,
    "collection_value": 347764600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 219",
    "reward_summary": "无奖励"
  },
  {
    "id": 220,
    "collection_value": 352560900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 220",
    "reward_summary": "无奖励"
  },
  {
    "id": 221,
    "collection_value": 357401100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 221",
    "reward_summary": "无奖励"
  },
  {
    "id": 222,
    "collection_value": 362285400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 222",
    "reward_summary": "无奖励"
  },
  {
    "id": 223,
    "collection_value": 367214000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 223",
    "reward_summary": "无奖励"
  },
  {
    "id": 224,
    "collection_value": 372187100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 224",
    "reward_summary": "无奖励"
  },
  {
    "id": 225,
    "collection_value": 377204900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 225",
    "reward_summary": "无奖励"
  },
  {
    "id": 226,
    "collection_value": 382267600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 226",
    "reward_summary": "无奖励"
  },
  {
    "id": 227,
    "collection_value": 387375400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 227",
    "reward_summary": "无奖励"
  },
  {
    "id": 228,
    "collection_value": 392528500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 228",
    "reward_summary": "无奖励"
  },
  {
    "id": 229,
    "collection_value": 397727100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 229",
    "reward_summary": "无奖励"
  },
  {
    "id": 230,
    "collection_value": 402971400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 230",
    "reward_summary": "无奖励"
  },
  {
    "id": 231,
    "collection_value": 408261600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 231",
    "reward_summary": "无奖励"
  },
  {
    "id": 232,
    "collection_value": 413597900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 232",
    "reward_summary": "无奖励"
  },
  {
    "id": 233,
    "collection_value": 418980500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 233",
    "reward_summary": "无奖励"
  },
  {
    "id": 234,
    "collection_value": 424409600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 234",
    "reward_summary": "无奖励"
  },
  {
    "id": 235,
    "collection_value": 429885400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 235",
    "reward_summary": "无奖励"
  },
  {
    "id": 236,
    "collection_value": 435408100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 236",
    "reward_summary": "无奖励"
  },
  {
    "id": 237,
    "collection_value": 440977900,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 237",
    "reward_summary": "无奖励"
  },
  {
    "id": 238,
    "collection_value": 446595000,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 238",
    "reward_summary": "无奖励"
  },
  {
    "id": 239,
    "collection_value": 452259600,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 239",
    "reward_summary": "无奖励"
  },
  {
    "id": 240,
    "collection_value": 457971900,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 240",
    "reward_summary": "无奖励"
  },
  {
    "id": 241,
    "collection_value": 463732100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 241",
    "reward_summary": "无奖励"
  },
  {
    "id": 242,
    "collection_value": 469540400,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 242",
    "reward_summary": "无奖励"
  },
  {
    "id": 243,
    "collection_value": 475397000,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 243",
    "reward_summary": "无奖励"
  },
  {
    "id": 244,
    "collection_value": 481302100,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 244",
    "reward_summary": "无奖励"
  },
  {
    "id": 245,
    "collection_value": 487255900,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 245",
    "reward_summary": "无奖励"
  },
  {
    "id": 246,
    "collection_value": 493258600,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 246",
    "reward_summary": "无奖励"
  },
  {
    "id": 247,
    "collection_value": 499310400,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 247",
    "reward_summary": "无奖励"
  },
  {
    "id": 248,
    "collection_value": 505411500,
    "level_reward": [
      [
        106,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 248",
    "reward_summary": "无奖励"
  },
  {
    "id": 249,
    "collection_value": 511562100,
    "level_reward": [
      [
        7013,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 249",
    "reward_summary": "无奖励"
  },
  {
    "id": 250,
    "collection_value": 517762400,
    "level_reward": [
      [
        7012,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 250",
    "reward_summary": "无奖励"
  },
  {
    "id": 251,
    "collection_value": 524012600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 251",
    "reward_summary": "无奖励"
  },
  {
    "id": 252,
    "collection_value": 530312900,
    "level_reward": [
      [
        7002,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 252",
    "reward_summary": "无奖励"
  },
  {
    "id": 253,
    "collection_value": 536663500,
    "level_reward": [
      [
        102,
        2
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 253",
    "reward_summary": "无奖励"
  },
  {
    "id": 254,
    "collection_value": 543064600,
    "level_reward": [
      [
        1,
        50000
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 254",
    "reward_summary": "无奖励"
  },
  {
    "id": 255,
    "collection_value": 549516400,
    "level_reward": [
      [
        7011,
        1
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 255",
    "reward_summary": "无奖励"
  },
  {
    "id": 256,
    "collection_value": 556019100,
    "level_reward": [
      [
        7003,
        3
      ]
    ],
    "bass_value": 0,
    "bass_reward": [
      [
        0
      ]
    ],
    "big_bass_reward": [
      [
        0
      ]
    ],
    "packaged_name": "掌柜等级 256",
    "reward_summary": "无奖励"
  }
];

export function levelUpById(id: number): BidKingLevelUpRow | undefined {
  return LevelUp.find((level) => level.id === id);
}
