// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Mail: BidKingRawTableRow[] = [
  {
    "id": "101",
    "table": "Mail",
    "columns": [
      "101",
      "",
      "",
      "0",
      "mail_title_101",
      "mail_sender_1",
      "mail_text_101",
      "[[]]",
      "3650",
      "text_Mail_101_9"
    ],
    "packaged_name": "邮件101",
    "packaged_desc": "邮件配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "102",
    "table": "Mail",
    "columns": [
      "102",
      "",
      "",
      "2",
      "mail_tiltle_102",
      "mail_sender_1",
      "mail_text_102",
      "[[]]",
      "30",
      "text_Mail_102_9"
    ],
    "packaged_name": "邮件102",
    "packaged_desc": "邮件配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "103",
    "table": "Mail",
    "columns": [
      "103",
      "",
      "",
      "2",
      "mail_tiltle_103",
      "",
      "mail_text_103",
      "[[]]",
      "30",
      "text_Mail_103_9"
    ],
    "packaged_name": "邮件103",
    "packaged_desc": "邮件配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "104",
    "table": "Mail",
    "columns": [
      "104",
      "",
      "",
      "2",
      "mail_tiltle_104",
      "mail_sender_1",
      "mail_text_104",
      "[[]]",
      "3650",
      "text_Mail_104_9"
    ],
    "packaged_name": "邮件104",
    "packaged_desc": "邮件配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "105",
    "table": "Mail",
    "columns": [
      "105",
      "",
      "",
      "2",
      "mail_tiltle_105",
      "mail_sender_1",
      "mail_text_105",
      "[[]]",
      "180",
      "text_Mail_105_9"
    ],
    "packaged_name": "邮件105",
    "packaged_desc": "邮件配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "106",
    "table": "Mail",
    "columns": [
      "106",
      "",
      "",
      "2",
      "mail_tiltle_106",
      "mail_sender_1",
      "mail_text_106",
      "[[]]",
      "180",
      "text_Mail_106_9"
    ],
    "packaged_name": "邮件106",
    "packaged_desc": "邮件配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "107",
    "table": "Mail",
    "columns": [
      "107",
      "",
      "",
      "2",
      "mail_tiltle_107",
      "mail_sender_1",
      "mail_text_107",
      "[[]]",
      "3650",
      "text_Mail_107_9"
    ],
    "packaged_name": "邮件107",
    "packaged_desc": "邮件配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "108",
    "table": "Mail",
    "columns": [
      "108",
      "",
      "",
      "2",
      "mail_tiltle_108",
      "mail_sender_1",
      "mail_text_108",
      "[[]]",
      "30",
      "text_Mail_108_9"
    ],
    "packaged_name": "邮件108",
    "packaged_desc": "邮件配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "201",
    "table": "Mail",
    "columns": [
      "201",
      "",
      "",
      "2",
      "mail_title_201",
      "",
      "mail_text_201",
      "[[]]",
      "30",
      "text_Mail_201_9"
    ],
    "packaged_name": "邮件201",
    "packaged_desc": "邮件配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "202",
    "table": "Mail",
    "columns": [
      "202",
      "",
      "",
      "2",
      "mail_title_202",
      "",
      "mail_text_202",
      "[[]]",
      "30",
      "text_Mail_202_9"
    ],
    "packaged_name": "邮件202",
    "packaged_desc": "邮件配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "109",
    "table": "Mail",
    "columns": [
      "109",
      "",
      "",
      "0",
      "mail_title_109",
      "mail_sender_1",
      "mail_text_109",
      "[[]]",
      "3650",
      "text_Mail_109_9"
    ],
    "packaged_name": "邮件109",
    "packaged_desc": "邮件配置行 11，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "110",
    "table": "Mail",
    "columns": [
      "110",
      "",
      "",
      "0",
      "mail_title_110",
      "mail_sender_1",
      "mail_text_110",
      "[[]]",
      "3650",
      "text_Mail_110_9"
    ],
    "packaged_name": "邮件110",
    "packaged_desc": "邮件配置行 12，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1001",
    "table": "Mail",
    "columns": [
      "1001",
      "",
      "",
      "0",
      "mail_title_1001",
      "",
      "mail_text_1001",
      "[[17,140009,1],[18,150019,1]]",
      "3650",
      "text_Mail_1001_9"
    ],
    "packaged_name": "邮件1001",
    "packaged_desc": "邮件配置行 13，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
