// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingMapRow } from '../schema';

export const Map: BidKingMapRow[] = [
  {
    "id": 101,
    "map_name": "map_name_101",
    "map_desc": "map_desc_101",
    "map_position": [
      -301,
      149
    ],
    "map_icon": "ui_map_pic_jianzhu_1",
    "auction_limit_notify": 100000,
    "entrust_value": 20000,
    "entrust_bidmap": 2101,
    "entrust_cost": [
      1,
      1,
      1000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      15,
      20
    ],
    "is_open": 1,
    "mapgroup": 101,
    "world_process": 0,
    "daily_counts": 100,
    "open_time": [
      []
    ],
    "packaged_name": "洛阳旧宫",
    "packaged_desc": "宫廷旧藏",
    "art_key": "container_palace"
  },
  {
    "id": 102,
    "map_name": "map_name_102",
    "map_desc": "map_desc_102",
    "map_position": [
      202,
      240
    ],
    "map_icon": "ui_map_pic_jianzhu_3",
    "auction_limit_notify": 500000,
    "entrust_value": 150000,
    "entrust_bidmap": 2201,
    "entrust_cost": [
      1,
      1,
      5000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      20,
      25
    ],
    "is_open": 1,
    "mapgroup": 102,
    "world_process": 0,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "江东商船",
    "packaged_desc": "江东商船",
    "art_key": "container_ship"
  },
  {
    "id": 103,
    "map_name": "map_name_103",
    "map_desc": "map_desc_103",
    "map_position": [
      -342,
      -214
    ],
    "map_icon": "ui_map_pic_jianzhu_5",
    "auction_limit_notify": 1000000,
    "entrust_value": 300000,
    "entrust_bidmap": 2301,
    "entrust_cost": [
      1,
      1,
      20000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      20,
      25
    ],
    "is_open": 1,
    "mapgroup": 103,
    "world_process": 0,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "西凉军库",
    "packaged_desc": "军需旧库",
    "art_key": "container_armory"
  },
  {
    "id": 104,
    "map_name": "map_name_104",
    "map_desc": "map_desc_104",
    "map_position": [
      584,
      -191
    ],
    "map_icon": "ui_map_pic_jianzhu_4",
    "auction_limit_notify": 2000000,
    "entrust_value": 500000,
    "entrust_bidmap": 2401,
    "entrust_cost": [
      1,
      1,
      50000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      25,
      30
    ],
    "is_open": 1,
    "mapgroup": 104,
    "world_process": 1,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "破败书院",
    "packaged_desc": "旧书院",
    "art_key": "container_academy"
  },
  {
    "id": 105,
    "map_name": "map_name_105",
    "map_desc": "map_desc_105",
    "map_position": [
      861,
      -131
    ],
    "map_icon": "ui_map_pic_jianzhu_2",
    "auction_limit_notify": 3000000,
    "entrust_value": 1000000,
    "entrust_bidmap": 2501,
    "entrust_cost": [
      1,
      1,
      100000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      30,
      35
    ],
    "is_open": 1,
    "mapgroup": 105,
    "world_process": 2,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "黑市密仓",
    "packaged_desc": "黑市密仓",
    "art_key": "container_black_market"
  },
  {
    "id": 201,
    "map_name": "map_name_201",
    "map_desc": "map_desc_201",
    "map_position": [],
    "map_icon": "",
    "auction_limit_notify": 0,
    "entrust_value": 0,
    "entrust_bidmap": 0,
    "entrust_cost": [
      0
    ],
    "entrust_prob": 0,
    "type": 0,
    "entrust_num": [
      0
    ],
    "is_open": 1,
    "mapgroup": 0,
    "world_process": 0,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "洛阳旧宫",
    "packaged_desc": "宫廷旧藏",
    "art_key": "container_palace"
  },
  {
    "id": 304,
    "map_name": "map_name_304",
    "map_desc": "map_desc_304",
    "map_position": [
      748,
      -330
    ],
    "map_icon": "ui_map_pic_jianzhu_304",
    "auction_limit_notify": 2000000,
    "entrust_value": 0,
    "entrust_bidmap": 2401,
    "entrust_cost": [
      0
    ],
    "entrust_prob": 500,
    "type": 1,
    "entrust_num": [
      0
    ],
    "is_open": 1,
    "mapgroup": 104,
    "world_process": 1,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "洛阳旧宫",
    "packaged_desc": "宫廷旧藏",
    "art_key": "container_palace"
  },
  {
    "id": 305,
    "map_name": "map_name_305",
    "map_desc": "map_desc_305",
    "map_position": [
      631,
      75
    ],
    "map_icon": "ui_map_pic_jianzhu_305",
    "auction_limit_notify": 3000000,
    "entrust_value": 0,
    "entrust_bidmap": 2501,
    "entrust_cost": [
      0
    ],
    "entrust_prob": 500,
    "type": 1,
    "entrust_num": [
      0
    ],
    "is_open": 1,
    "mapgroup": 105,
    "world_process": 2,
    "daily_counts": 0,
    "open_time": [
      []
    ],
    "packaged_name": "洛阳旧宫",
    "packaged_desc": "宫廷旧藏",
    "art_key": "container_palace"
  },
  {
    "id": 106,
    "map_name": "map_name_106",
    "map_desc": "map_desc_106",
    "map_position": [
      1164,
      108
    ],
    "map_icon": "ui_map_pic_jianzhu_7",
    "auction_limit_notify": 3000000,
    "entrust_value": 5000000,
    "entrust_bidmap": 2601,
    "entrust_cost": [
      1,
      1,
      500000
    ],
    "entrust_prob": 500,
    "type": 0,
    "entrust_num": [
      40,
      45
    ],
    "is_open": 1,
    "mapgroup": 106,
    "world_process": 3,
    "daily_counts": 0,
    "open_time": [
      [
        1,
        19,
        0,
        23,
        0
      ],
      [
        2,
        19,
        0,
        23,
        0
      ],
      [
        3,
        19,
        0,
        23,
        0
      ],
      [
        4,
        19,
        0,
        23,
        0
      ],
      [
        5,
        19,
        0,
        24,
        0
      ],
      [
        6,
        8,
        0,
        23,
        0
      ],
      [
        7,
        8,
        0,
        23,
        0
      ]
    ],
    "packaged_name": "古战场遗址",
    "packaged_desc": "战场残库",
    "art_key": "container_battlefield"
  }
];
