// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Notice: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "Notice",
    "columns": [
      "1",
      "",
      "",
      "2",
      "notice_system",
      "notice_1",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_1_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容1"
  },
  {
    "id": "2",
    "table": "Notice",
    "columns": [
      "2",
      "",
      "",
      "2",
      "notice_system",
      "notice_2",
      "ui_common_2",
      "0",
      "text_Notice_2_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容2"
  },
  {
    "id": "3",
    "table": "Notice",
    "columns": [
      "3",
      "",
      "",
      "2",
      "notice_system",
      "notice_3",
      "0",
      "0",
      "text_Notice_3_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容3"
  },
  {
    "id": "4",
    "table": "Notice",
    "columns": [
      "4",
      "",
      "",
      "2",
      "notice_system",
      "notice_4",
      "0",
      "0",
      "text_Notice_4_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容4"
  },
  {
    "id": "5",
    "table": "Notice",
    "columns": [
      "5",
      "",
      "",
      "2",
      "notice_system",
      "notice_5",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_5_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容5"
  },
  {
    "id": "6",
    "table": "Notice",
    "columns": [
      "6",
      "",
      "",
      "2",
      "notice_system",
      "notice_6",
      "",
      "",
      "text_Notice_6_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "暂无内容6"
  },
  {
    "id": "7",
    "table": "Notice",
    "columns": [
      "7",
      "",
      "",
      "2",
      "notice_system",
      "notice_7",
      "",
      "",
      "text_Notice_7_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "银币大于100000，才可以进入拍卖行"
  },
  {
    "id": "8",
    "table": "Notice",
    "columns": [
      "8",
      "",
      "text_Notice_8_2",
      "1",
      "",
      "notice_8",
      "",
      "",
      "text_Notice_8_8"
    ],
    "packaged_name": "获得BKB",
    "packaged_desc": "获得×{0}"
  },
  {
    "id": "9",
    "table": "Notice",
    "columns": [
      "9",
      "",
      "text_Notice_9_2",
      "2",
      "notice_system",
      "notice_9",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "购买道具超出系统回收价",
    "packaged_desc": "购买的藏品售价远超系统回收价"
  },
  {
    "id": "10",
    "table": "Notice",
    "columns": [
      "10",
      "",
      "text_Notice_10_2",
      "2",
      "",
      "notice_10",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "是否查看回放",
    "packaged_desc": "是否查看回放"
  },
  {
    "id": "11",
    "table": "Notice",
    "columns": [
      "11",
      "",
      "text_Notice_11_2",
      "2",
      "",
      "notice_11",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "是否退出回放",
    "packaged_desc": "是否退出回放"
  },
  {
    "id": "12",
    "table": "Notice",
    "columns": [
      "12",
      "",
      "text_Notice_12_2",
      "2",
      "",
      "notice_12",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "是否将玩家{0}踢出房间？",
    "packaged_desc": "是否将玩家 {0} 踢出房间？"
  },
  {
    "id": "13",
    "table": "Notice",
    "columns": [
      "13",
      "",
      "text_Notice_13_2",
      "2",
      "",
      "notice_13",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "进入房间将退出当前匹配队列",
    "packaged_desc": "进入房间将退出当前匹配队列"
  },
  {
    "id": "14",
    "table": "Notice",
    "columns": [
      "14",
      "",
      "text_Notice_14_2",
      "2",
      "",
      "notice_14",
      "ui_common_2",
      "ui_common_3",
      ""
    ],
    "packaged_name": "是否立即结束本场竞拍",
    "packaged_desc": "是否立即结束本场竞拍"
  },
  {
    "id": "15",
    "table": "Notice",
    "columns": [
      "15",
      "",
      "text_Notice_15_2",
      "",
      "notice_title_15",
      "notice_15",
      "ui_common_2",
      "",
      ""
    ],
    "packaged_name": "竞价确认",
    "packaged_desc": "出价超过确认阈值，请重新确认后再试"
  },
  {
    "id": "1001",
    "table": "Notice",
    "columns": [
      "1001",
      "",
      "",
      "1",
      "notice_system",
      "notice_1001",
      "0",
      "0",
      "text_Notice_1001_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "操作失败"
  },
  {
    "id": "10001",
    "table": "Notice",
    "columns": [
      "10001",
      "",
      "",
      "3",
      "notice_system",
      "notice_10001",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10001_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否弃权？"
  },
  {
    "id": "10002",
    "table": "Notice",
    "columns": [
      "10002",
      "",
      "",
      "1",
      "notice_system",
      "notice_10002",
      "0",
      "0",
      "text_Notice_10002_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "当前回合已经出过价，不能再出价！"
  },
  {
    "id": "10003",
    "table": "Notice",
    "columns": [
      "10003",
      "",
      "",
      "1",
      "notice_system",
      "notice_10003",
      "0",
      "0",
      "text_Notice_10003_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "当前回合已经出过价，不能使用道具！"
  },
  {
    "id": "10004",
    "table": "Notice",
    "columns": [
      "10004",
      "",
      "",
      "1",
      "notice_system",
      "notice_10004",
      "0",
      "0",
      "text_Notice_10004_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "当前回合已使用过道具，不能使用道具！"
  },
  {
    "id": "10005",
    "table": "Notice",
    "columns": [
      "10005",
      "",
      "",
      "1",
      "notice_system",
      "notice_10005",
      "0",
      "0",
      "text_Notice_10005_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "弃权后不能使用道具！"
  },
  {
    "id": "10006",
    "table": "Notice",
    "columns": [
      "10006",
      "",
      "",
      "1",
      "notice_system",
      "notice_10006",
      "0",
      "0",
      "text_Notice_10006_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "弃权后不能出价！"
  },
  {
    "id": "10007",
    "table": "Notice",
    "columns": [
      "10007",
      "",
      "",
      "1",
      "notice_system",
      "notice_10007",
      "0",
      "0",
      "text_Notice_10007_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "格子已被占用！"
  },
  {
    "id": "10008",
    "table": "Notice",
    "columns": [
      "10008",
      "",
      "",
      "2",
      "notice_system",
      "notice_10008",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10008_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "您要梭哈，确定吗？"
  },
  {
    "id": "10009",
    "table": "Notice",
    "columns": [
      "10009",
      "",
      "",
      "2",
      "notice_system",
      "notice_10009",
      "ui_common_2",
      "",
      "text_Notice_10009_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "藏品类型不正确"
  },
  {
    "id": "10010",
    "table": "Notice",
    "columns": [
      "10010",
      "",
      "",
      "2",
      "notice_system",
      "notice_10010",
      "ui_common_2",
      "",
      "text_Notice_10010_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "只有红色以上品质藏品才能放入收藏柜"
  },
  {
    "id": "10011",
    "table": "Notice",
    "columns": [
      "10011",
      "",
      "",
      "2",
      "notice_system",
      "notice_10011",
      "ui_common_2",
      "",
      "text_Notice_10011_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "领取太频繁，请等待 {0} 秒！"
  },
  {
    "id": "10012",
    "table": "Notice",
    "columns": [
      "10012",
      "",
      "",
      "2",
      "notice_system",
      "notice_10012",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10012_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "收藏柜没有藏品，请先放置藏品"
  },
  {
    "id": "10013",
    "table": "Notice",
    "columns": [
      "10013",
      "",
      "",
      "2",
      "notice_system",
      "notice_10013",
      "ui_common_2",
      "",
      "text_Notice_10013_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "绑定藏品无法放入收藏柜"
  },
  {
    "id": "10014",
    "table": "Notice",
    "columns": [
      "10014",
      "",
      "",
      "3",
      "notice_system",
      "notice_10014",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10014_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "卸载时将会把箱子内藏品移动到主仓库中"
  },
  {
    "id": "10015",
    "table": "Notice",
    "columns": [
      "10015",
      "",
      "",
      "1",
      "notice_system",
      "notice_10015",
      "",
      "",
      "text_Notice_10015_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "箱子数量已达到上限"
  },
  {
    "id": "10016",
    "table": "Notice",
    "columns": [
      "10016",
      "",
      "",
      "1",
      "notice_system",
      "notice_10016",
      "",
      "",
      "text_Notice_10016_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "未拥有该箱子，请前往兑换"
  },
  {
    "id": "10017",
    "table": "Notice",
    "columns": [
      "10017",
      "",
      "",
      "3",
      "notice_system",
      "notice_10017",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10017_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "花费 {0}金币购买通行证"
  },
  {
    "id": "10018",
    "table": "Notice",
    "columns": [
      "10018",
      "",
      "",
      "1",
      "notice_system",
      "notice_10018",
      "",
      "",
      "text_Notice_10018_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "当前藏品已售罄，无法兑换"
  },
  {
    "id": "10019",
    "table": "Notice",
    "columns": [
      "10019",
      "",
      "",
      "1",
      "notice_system",
      "notice_10019",
      "",
      "",
      "text_Notice_10019_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "银币不足"
  },
  {
    "id": "10020",
    "table": "Notice",
    "columns": [
      "10020",
      "",
      "",
      "1",
      "notice_system",
      "notice_10020",
      "",
      "",
      "text_Notice_10020_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "购买次数不足"
  },
  {
    "id": "10021",
    "table": "Notice",
    "columns": [
      "10021",
      "",
      "",
      "1",
      "notice_system",
      "notice_10021",
      "",
      "",
      "text_Notice_10021_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "兑换次数不足"
  },
  {
    "id": "10023",
    "table": "Notice",
    "columns": [
      "10023",
      "",
      "",
      "1",
      "notice_system",
      "notice_10023",
      "",
      "",
      "text_Notice_10023_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该商品当前没有挂售"
  },
  {
    "id": "10024",
    "table": "Notice",
    "columns": [
      "10024",
      "",
      "",
      "1",
      "notice_system",
      "notice_10024",
      "",
      "",
      "text_Notice_10024_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该商品已被出售"
  },
  {
    "id": "10025",
    "table": "Notice",
    "columns": [
      "10025",
      "",
      "",
      "3",
      "notice_system",
      "notice_10025",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10025_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "您的竞拍出价大于等于该商品的一口价 是否直接用一口价 {0}金币购买该商品？"
  },
  {
    "id": "10026",
    "table": "Notice",
    "columns": [
      "10026",
      "",
      "",
      "3",
      "notice_system",
      "notice_10026",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10026_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否消耗金币 {0}购买 1 个拍卖行出售位"
  },
  {
    "id": "10027",
    "table": "Notice",
    "columns": [
      "10027",
      "",
      "",
      "1",
      "notice_system",
      "notice_10027",
      "",
      "",
      "text_Notice_10027_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "拍卖行上架商品数量已满"
  },
  {
    "id": "10028",
    "table": "Notice",
    "columns": [
      "10028",
      "",
      "",
      "1",
      "notice_system",
      "notice_10028",
      "",
      "",
      "text_Notice_10028_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该物品无法上架拍卖行"
  },
  {
    "id": "10029",
    "table": "Notice",
    "columns": [
      "10029",
      "",
      "",
      "1",
      "notice_system",
      "notice_10029",
      "",
      "",
      "text_Notice_10029_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "协会成员已满"
  },
  {
    "id": "10030",
    "table": "Notice",
    "columns": [
      "10030",
      "",
      "",
      "1",
      "notice_system",
      "notice_10030",
      "",
      "",
      "text_Notice_10030_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "名称已存在"
  },
  {
    "id": "10031",
    "table": "Notice",
    "columns": [
      "10031",
      "",
      "",
      "1",
      "notice_system",
      "notice_10031",
      "",
      "",
      "text_Notice_10031_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "添加失败"
  },
  {
    "id": "10032",
    "table": "Notice",
    "columns": [
      "10032",
      "",
      "",
      "1",
      "notice_system",
      "notice_10032",
      "",
      "",
      "text_Notice_10032_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "协会成员已满，不能继续添加"
  },
  {
    "id": "10033",
    "table": "Notice",
    "columns": [
      "10033",
      "",
      "",
      "2",
      "notice_system",
      "notice_10033",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10033_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否退出协会？"
  },
  {
    "id": "10034",
    "table": "Notice",
    "columns": [
      "10034",
      "",
      "",
      "2",
      "notice_system",
      "notice_10034",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10034_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否修改协会信息？"
  },
  {
    "id": "10035",
    "table": "Notice",
    "columns": [
      "10035",
      "",
      "",
      "1",
      "notice_system",
      "notice_10035",
      "",
      "",
      "text_Notice_10035_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "未登录账号"
  },
  {
    "id": "10036",
    "table": "Notice",
    "columns": [
      "10036",
      "",
      "",
      "2",
      "notice_system",
      "notice_10036",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10036_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否要删除邮件？"
  },
  {
    "id": "10037",
    "table": "Notice",
    "columns": [
      "10037",
      "",
      "",
      "2",
      "notice_system",
      "notice_10037",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10037_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否要删除全部已读邮件？"
  },
  {
    "id": "10038",
    "table": "Notice",
    "columns": [
      "10038",
      "",
      "",
      "1",
      "notice_system",
      "notice_10038",
      "",
      "",
      "text_Notice_10038_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "自己挂拍的商品不能出价"
  },
  {
    "id": "10039",
    "table": "Notice",
    "columns": [
      "10039",
      "",
      "",
      "1",
      "notice_system",
      "notice_10039",
      "",
      "",
      "text_Notice_10039_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "名称可用。"
  },
  {
    "id": "10040",
    "table": "Notice",
    "columns": [
      "10040",
      "",
      "",
      "3",
      "notice_system",
      "notice_10040",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10040_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架商品 {0}，起拍价 {1}金币，一口价 {2}金币 ★本商品上架扣除 {3}金币上架费 ★上架商品被出价后无法下架 ★上架商品成交后，系统会按成交价格 10%收取拍卖税，卖方最终获得 90%成交金币"
  },
  {
    "id": "10041",
    "table": "Notice",
    "columns": [
      "10041",
      "",
      "",
      "3",
      "notice_system",
      "notice_10041",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10041_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架商品 {0}，起拍价 {1}金币，未设置一口价 ★本商品上架扣除 {2}金币上架费 ★上架商品被出价后无法下架 ★上架商品成交后，系统会按成交价格 10%收取拍卖税，卖方最终获得 90%成交金币"
  },
  {
    "id": "10042",
    "table": "Notice",
    "columns": [
      "10042",
      "",
      "",
      "1",
      "notice_system",
      "notice_10042",
      "",
      "",
      "text_Notice_10042_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架成功"
  },
  {
    "id": "10043",
    "table": "Notice",
    "columns": [
      "10043",
      "",
      "",
      "1",
      "notice_system",
      "notice_10043",
      "",
      "",
      "text_Notice_10043_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "下架成功"
  },
  {
    "id": "10044",
    "table": "Notice",
    "columns": [
      "10044",
      "",
      "",
      "1",
      "notice_system",
      "notice_10044",
      "",
      "",
      "text_Notice_10044_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架位置增加成功"
  },
  {
    "id": "10045",
    "table": "Notice",
    "columns": [
      "10045",
      "",
      "",
      "1",
      "notice_system",
      "notice_10045",
      "",
      "",
      "text_Notice_10045_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "出价成功"
  },
  {
    "id": "10046",
    "table": "Notice",
    "columns": [
      "10046",
      "",
      "",
      "1",
      "notice_system",
      "notice_10046",
      "",
      "",
      "text_Notice_10046_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架栏位不足，上架失败"
  },
  {
    "id": "10047",
    "table": "Notice",
    "columns": [
      "10047",
      "",
      "",
      "1",
      "notice_system",
      "notice_10047",
      "",
      "",
      "text_Notice_10047_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架商品数量不正确"
  },
  {
    "id": "10048",
    "table": "Notice",
    "columns": [
      "10048",
      "",
      "",
      "1",
      "notice_system",
      "notice_10048",
      "",
      "",
      "text_Notice_10048_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "上架起拍价必须大于 0金币"
  },
  {
    "id": "10049",
    "table": "Notice",
    "columns": [
      "10049",
      "",
      "",
      "1",
      "notice_system",
      "notice_10049",
      "",
      "",
      "text_Notice_10049_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "一口价必须大于起拍价"
  },
  {
    "id": "10050",
    "table": "Notice",
    "columns": [
      "10050",
      "",
      "",
      "3",
      "notice_system",
      "notice_10050",
      "ui_common_4",
      "ui_common_3",
      "text_Notice_10050_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "金币不足 是否前往购买金币"
  },
  {
    "id": "10051",
    "table": "Notice",
    "columns": [
      "10051",
      "",
      "",
      "1",
      "notice_system",
      "notice_10051",
      "",
      "",
      "text_Notice_10051_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该商品最低加价为 {0}金币"
  },
  {
    "id": "10052",
    "table": "Notice",
    "columns": [
      "10052",
      "",
      "",
      "3",
      "notice_system",
      "notice_10052",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10052_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "是否确认下架商品？"
  },
  {
    "id": "10053",
    "table": "Notice",
    "columns": [
      "10053",
      "",
      "",
      "2",
      "notice_system",
      "notice_10053",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10053_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "有正在进行的游戏，是否重新进入？"
  },
  {
    "id": "10054",
    "table": "Notice",
    "columns": [
      "10054",
      "",
      "",
      "1",
      "notice_system",
      "notice_10054",
      "",
      "",
      "text_Notice_10054_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "已替换"
  },
  {
    "id": "10055",
    "table": "Notice",
    "columns": [
      "10055",
      "",
      "",
      "1",
      "notice_system",
      "notice_10055",
      "",
      "",
      "text_Notice_10055_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "需要先转让会长。"
  },
  {
    "id": "10056",
    "table": "Notice",
    "columns": [
      "10056",
      "",
      "",
      "2",
      "notice_system",
      "notice_10056",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10056_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "现在退出协会后，协会将会解散，是否继续？"
  },
  {
    "id": "10057",
    "table": "Notice",
    "columns": [
      "10057",
      "",
      "",
      "1",
      "notice_system",
      "notice_10057",
      "",
      "",
      "text_Notice_10057_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "目标已是好友。"
  },
  {
    "id": "10058",
    "table": "Notice",
    "columns": [
      "10058",
      "",
      "",
      "2",
      "notice_system",
      "notice_10058",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10058_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "资产不足，有可领取的救济金，是否前往领取？"
  },
  {
    "id": "10059",
    "table": "Notice",
    "columns": [
      "10059",
      "",
      "",
      "1",
      "notice_system",
      "notice_10059",
      "",
      "",
      "text_Notice_10059_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "已达上限。"
  },
  {
    "id": "10060",
    "table": "Notice",
    "columns": [
      "10060",
      "",
      "",
      "1",
      "notice_system",
      "notice_10060",
      "",
      "",
      "text_Notice_10060_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "道具不足。"
  },
  {
    "id": "10061",
    "table": "Notice",
    "columns": [
      "10061",
      "",
      "",
      "1",
      "notice_system",
      "notice_10061",
      "",
      "",
      "text_Notice_10061_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "名称不可为空。"
  },
  {
    "id": "10062",
    "table": "Notice",
    "columns": [
      "10062",
      "",
      "",
      "1",
      "notice_system",
      "notice_10062",
      "",
      "",
      "text_Notice_10062_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "保存成功"
  },
  {
    "id": "10063",
    "table": "Notice",
    "columns": [
      "10063",
      "",
      "",
      "1",
      "notice_system",
      "notice_10063",
      "",
      "",
      "text_Notice_10063_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "您的仓库已满，请整理出空间后继续！"
  },
  {
    "id": "10064",
    "table": "Notice",
    "columns": [
      "10064",
      "",
      "",
      "1",
      "notice_system",
      "notice_10064",
      "",
      "",
      "text_Notice_10064_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该商品未设置一口价"
  },
  {
    "id": "10065",
    "table": "Notice",
    "columns": [
      "10065",
      "",
      "",
      "1",
      "notice_system",
      "notice_10065",
      "",
      "",
      "text_Notice_10065_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "藏品品质过低"
  },
  {
    "id": "10066",
    "table": "Notice",
    "columns": [
      "10066",
      "",
      "",
      "1",
      "notice_system",
      "notice_10066",
      "",
      "",
      "text_Notice_10066_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "收藏柜放置达到上限"
  },
  {
    "id": "10067",
    "table": "Notice",
    "columns": [
      "10067",
      "",
      "",
      "1",
      "notice_system",
      "notice_10067",
      "",
      "",
      "text_Notice_10067_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "绑定非特殊藏品无法放置"
  },
  {
    "id": "10068",
    "table": "Notice",
    "columns": [
      "10068",
      "",
      "",
      "1",
      "notice_system",
      "notice_10068",
      "",
      "",
      "text_Notice_10068_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "该藏品无法出售"
  },
  {
    "id": "10069",
    "table": "Notice",
    "columns": [
      "10069",
      "",
      "",
      "1",
      "notice_system",
      "notice_10069",
      "",
      "",
      "text_Notice_10069_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "当前版本无法弃权"
  },
  {
    "id": "10070",
    "table": "Notice",
    "columns": [
      "10070",
      "",
      "",
      "1",
      "notice_system",
      "notice_10070",
      "",
      "",
      "text_Notice_10070_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "DLC 奖励发放成功，请前往邮箱查收"
  },
  {
    "id": "10071",
    "table": "Notice",
    "columns": [
      "10071",
      "",
      "",
      "1",
      "notice_system",
      "notice_10071",
      "",
      "",
      "text_Notice_10071_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "DLC 奖励已全部到账，如有疑问请联系客服"
  },
  {
    "id": "10072",
    "table": "Notice",
    "columns": [
      "10072",
      "",
      "",
      "1",
      "notice_system",
      "notice_10072",
      "",
      "",
      "text_Notice_10072_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "未查询到 DLC 购买记录，如有疑问请联系客服"
  },
  {
    "id": "10073",
    "table": "Notice",
    "columns": [
      "10073",
      "",
      "",
      "2",
      "",
      "notice_10073",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10073_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "您当前设置的上架价格，远低于该物品的市场参考价格，请确认是否上架。"
  },
  {
    "id": "10074",
    "table": "Notice",
    "columns": [
      "10074",
      "",
      "",
      "1",
      "notice_system",
      "notice_10074",
      "",
      "",
      "text_Notice_10074_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "邮箱已满，无法上架"
  },
  {
    "id": "10075",
    "table": "Notice",
    "columns": [
      "10075",
      "",
      "",
      "1",
      "notice_system",
      "notice_10075",
      "",
      "",
      "text_Notice_10075_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "今日已达到该地图上限，快去其他地图试试吧。"
  },
  {
    "id": "10076",
    "table": "Notice",
    "columns": [
      "10076",
      "",
      "",
      "1",
      "notice_system",
      "notice_10076",
      "",
      "",
      "text_Notice_10076_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "验证未通过，请重新尝试"
  },
  {
    "id": "10077",
    "table": "Notice",
    "columns": [
      "10077",
      "",
      "",
      "1",
      "notice_system",
      "notice_10077",
      "",
      "",
      "text_Notice_10077_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "验证成功"
  },
  {
    "id": "10078",
    "table": "Notice",
    "columns": [
      "10078",
      "",
      "",
      "1",
      "notice_system",
      "notice_10078",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_10078_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "连续多次错误，请 {0} s 后再试"
  },
  {
    "id": "10079",
    "table": "Notice",
    "columns": [
      "10079",
      "",
      "",
      "1",
      "notice_system",
      "notice_10079",
      "",
      "",
      "text_Notice_10079_8"
    ],
    "packaged_name": "系统公告",
    "packaged_desc": "游戏版本过低，请退出重启游戏"
  },
  {
    "id": "2001",
    "table": "Notice",
    "columns": [
      "2001",
      "",
      "",
      "1",
      "",
      "notice_2001",
      "",
      "",
      "text_Notice_2001_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "送拍藏品总价不足"
  },
  {
    "id": "2002",
    "table": "Notice",
    "columns": [
      "2002",
      "",
      "",
      "1",
      "",
      "notice_2002",
      "",
      "",
      "text_Notice_2002_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "无法支付拍卖费"
  },
  {
    "id": "2003",
    "table": "Notice",
    "columns": [
      "2003",
      "",
      "",
      "2",
      "notice_songpai",
      "notice_2003",
      "ui_common_songpai",
      "ui_common_3",
      "text_Notice_2003_8"
    ],
    "packaged_name": "送拍",
    "packaged_desc": "提交委托后，有几率出现在正常对局中。拍卖成功后获得全部货款。可在邮件中查看拍卖记录。 注意：送拍立即扣除拍卖费，如果取消拍卖，集装箱中的货物将直接以系统价被回收。 估 价：{0} 手续费：{1}"
  },
  {
    "id": "2004",
    "table": "Notice",
    "columns": [
      "2004",
      "",
      "",
      "2",
      "notice_quxiaosongpai",
      "notice_2004",
      "ui_common_xiajia",
      "ui_common_3",
      ""
    ],
    "packaged_name": "取消送拍",
    "packaged_desc": "注意：取消送拍，集装箱中的货物将直接以系统价被回收。"
  },
  {
    "id": "2005",
    "table": "Notice",
    "columns": [
      "2005",
      "",
      "",
      "1",
      "",
      "notice_2005",
      "",
      "",
      "text_Notice_2005_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "集装箱已送拍"
  },
  {
    "id": "50001",
    "table": "Notice",
    "columns": [
      "50001",
      "",
      "",
      "5",
      "notice_quxiaosongpai",
      "notice_2006",
      "ui_common_2",
      "ui_common_3",
      "text_Notice_50001_8"
    ],
    "packaged_name": "取消送拍",
    "packaged_desc": "注意：关闭打包页面，当前的方案将不会保存。"
  },
  {
    "id": "2007",
    "table": "Notice",
    "columns": [
      "2007",
      "",
      "",
      "1",
      "",
      "notice_2007",
      "",
      "",
      "text_Notice_2007_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "刷新成功"
  },
  {
    "id": "2008",
    "table": "Notice",
    "columns": [
      "2008",
      "",
      "",
      "1",
      "",
      "notice_2008",
      "",
      "",
      "text_Notice_2008_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "这种类型的集装箱 需要放入 {0} 至 {1} 件藏品"
  },
  {
    "id": "2009",
    "table": "Notice",
    "columns": [
      "2009",
      "",
      "",
      "1",
      "",
      "notice_2009",
      "",
      "",
      "text_Notice_2009_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "送拍集装箱数量已达到上限"
  },
  {
    "id": "10022",
    "table": "Notice",
    "columns": [
      "10022",
      "",
      "",
      "1",
      "",
      "notice_10022",
      "",
      "",
      "text_Notice_10022_8"
    ],
    "packaged_name": "公告",
    "packaged_desc": "这种类型的集装箱最多放入 {0} 件藏品"
  },
  {
    "id": "2010",
    "table": "Notice",
    "columns": [
      "2010",
      "",
      "",
      "1",
      "",
      "notice_2010",
      "",
      "",
      "text_Notice_2010_8"
    ],
    "packaged_name": "问题反馈",
    "packaged_desc": "请输入您所遇到的问题"
  },
  {
    "id": "2011",
    "table": "Notice",
    "columns": [
      "2011",
      "",
      "",
      "1",
      "",
      "notice_2011",
      "",
      "",
      "text_Notice_2011_8"
    ],
    "packaged_name": "问题反馈",
    "packaged_desc": "您的问题我们已经收到，非常感谢您的反馈"
  },
  {
    "id": "2012",
    "table": "Notice",
    "columns": [
      "2012",
      "",
      "",
      "2",
      "",
      "notice_2012",
      "ui_exit",
      "",
      "text_Notice_2012_8"
    ],
    "packaged_name": "账号通知",
    "packaged_desc": "您已被封禁！ 因违反用户协议您已被禁止登录游戏，请访问客服中心获得更多信息。"
  }
];
