// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingNumberRow } from '../schema';

export const NumberTable: BidKingNumberRow[] = [
  {
    "Id": 101,
    "name": "number_name_101",
    "quality": 7,
    "counts": 500,
    "numberbonus": 0.126839167935058,
    "bg": "bg_number_101",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 500 件，收益加成 0.126839167935058。"
  },
  {
    "Id": 102,
    "name": "number_name_102",
    "quality": 7,
    "counts": 500,
    "numberbonus": 0.202942668696093,
    "bg": "bg_number_102",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 500 件，收益加成 0.202942668696093。"
  },
  {
    "Id": 103,
    "name": "number_name_103",
    "quality": 7,
    "counts": 500,
    "numberbonus": 0.380517503805175,
    "bg": "bg_number_103",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 500 件，收益加成 0.380517503805175。"
  },
  {
    "Id": 104,
    "name": "number_name_104",
    "quality": 7,
    "counts": 300,
    "numberbonus": 0.507356671740233,
    "bg": "bg_number_104",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 300 件，收益加成 0.507356671740233。"
  },
  {
    "Id": 105,
    "name": "number_name_105",
    "quality": 7,
    "counts": 300,
    "numberbonus": 0.76103500761035,
    "bg": "bg_number_105",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 300 件，收益加成 0.76103500761035。"
  },
  {
    "Id": 106,
    "name": "number_name_106",
    "quality": 7,
    "counts": 100,
    "numberbonus": 1.26839167935058,
    "bg": "bg_number_106",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 100 件，收益加成 1.26839167935058。"
  },
  {
    "Id": 107,
    "name": "number_name_107",
    "quality": 7,
    "counts": 8,
    "numberbonus": 1.26839167935058,
    "bg": "bg_number_107",
    "bid": 1,
    "packaged_name": "藏品收藏档",
    "packaged_desc": "需要 8 件，收益加成 1.26839167935058。"
  }
];
