// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Pay: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "Pay",
    "columns": [
      "1",
      "",
      "",
      "1",
      "pay_desc1",
      "700",
      "99",
      "70",
      "0",
      "pay_orderdesc_1",
      "ui_purchase_pic_1",
      "pay_steamdesc_1"
    ],
    "packaged_name": "充值档位1",
    "packaged_desc": "充值档位配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "Pay",
    "columns": [
      "2",
      "",
      "",
      "1",
      "pay_desc2",
      "3400",
      "499",
      "350",
      "20",
      "pay_orderdesc_2",
      "ui_purchase_pic_2",
      "pay_steamdesc_2"
    ],
    "packaged_name": "充值档位2",
    "packaged_desc": "充值档位配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "Pay",
    "columns": [
      "3",
      "",
      "",
      "1",
      "pay_desc2",
      "6800",
      "999",
      "700",
      "70",
      "pay_orderdesc_2",
      "ui_purchase_pic_3",
      "pay_steamdesc_3"
    ],
    "packaged_name": "充值档位3",
    "packaged_desc": "充值档位配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "Pay",
    "columns": [
      "4",
      "",
      "",
      "1",
      "pay_desc2",
      "13800",
      "1999",
      "1400",
      "210",
      "pay_orderdesc_2",
      "ui_purchase_pic_4",
      "pay_steamdesc_4"
    ],
    "packaged_name": "充值档位4",
    "packaged_desc": "充值档位配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "Pay",
    "columns": [
      "5",
      "",
      "",
      "1",
      "pay_desc2",
      "34500",
      "4999",
      "3500",
      "700",
      "pay_orderdesc_2",
      "ui_purchase_pic_5",
      "pay_steamdesc_5"
    ],
    "packaged_name": "充值档位5",
    "packaged_desc": "充值档位配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "Pay",
    "columns": [
      "6",
      "",
      "",
      "1",
      "pay_desc2",
      "69000",
      "9999",
      "7000",
      "1750",
      "pay_orderdesc_2",
      "ui_purchase_pic_6",
      "pay_steamdesc_6"
    ],
    "packaged_name": "充值档位6",
    "packaged_desc": "充值档位配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
