// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const PurchaseList: BidKingRawTableRow[] = [
  {
    "id": "1001",
    "table": "PurchaseList",
    "columns": [
      "1001",
      "1",
      "text_PurchaseList_1001_2",
      "text_PurchaseList_1001_3",
      "text_PurchaseList_1001_4",
      "text_PurchaseList_1001_5",
      "text_PurchaseList_1001_6",
      "external_url_1001_7",
      "external_url_1001_8",
      "False",
      "False",
      "text_PurchaseList_1001_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1001",
    "packaged_desc": "平台商品配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1002",
    "table": "PurchaseList",
    "columns": [
      "1002",
      "1",
      "text_PurchaseList_1002_2",
      "text_PurchaseList_1002_3",
      "text_PurchaseList_1002_4",
      "text_PurchaseList_1002_5",
      "text_PurchaseList_1002_6",
      "external_url_1002_7",
      "external_url_1002_8",
      "False",
      "False",
      "text_PurchaseList_1002_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1002",
    "packaged_desc": "平台商品配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1003",
    "table": "PurchaseList",
    "columns": [
      "1003",
      "1",
      "text_PurchaseList_1003_2",
      "text_PurchaseList_1003_3",
      "text_PurchaseList_1003_4",
      "text_PurchaseList_1003_5",
      "text_PurchaseList_1003_6",
      "external_url_1003_7",
      "external_url_1003_8",
      "False",
      "False",
      "text_PurchaseList_1003_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1003",
    "packaged_desc": "平台商品配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1004",
    "table": "PurchaseList",
    "columns": [
      "1004",
      "1",
      "text_PurchaseList_1004_2",
      "text_PurchaseList_1004_3",
      "text_PurchaseList_1004_4",
      "text_PurchaseList_1004_5",
      "text_PurchaseList_1004_6",
      "external_url_1004_7",
      "external_url_1004_8",
      "False",
      "False",
      "text_PurchaseList_1004_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1004",
    "packaged_desc": "平台商品配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1005",
    "table": "PurchaseList",
    "columns": [
      "1005",
      "1",
      "text_PurchaseList_1005_2",
      "text_PurchaseList_1005_3",
      "text_PurchaseList_1005_4",
      "text_PurchaseList_1005_5",
      "text_PurchaseList_1005_6",
      "external_url_1005_7",
      "external_url_1005_8",
      "False",
      "False",
      "text_PurchaseList_1005_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1005",
    "packaged_desc": "平台商品配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "1006",
    "table": "PurchaseList",
    "columns": [
      "1006",
      "1",
      "text_PurchaseList_1006_2",
      "text_PurchaseList_1006_3",
      "text_PurchaseList_1006_4",
      "text_PurchaseList_1006_5",
      "text_PurchaseList_1006_6",
      "external_url_1006_7",
      "external_url_1006_8",
      "False",
      "False",
      "text_PurchaseList_1006_11",
      "True",
      "True"
    ],
    "packaged_name": "平台商品1006",
    "packaged_desc": "平台商品配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
