// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const Rank: BidKingRawTableRow[] = [
  {
    "id": "101",
    "table": "Rank",
    "columns": [
      "101",
      "text_Rank_101_1",
      "text_Rank_101_2",
      "text_Rank_101_3",
      "text_Rank_101_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜101",
    "packaged_desc": "排行榜配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "102",
    "table": "Rank",
    "columns": [
      "102",
      "text_Rank_102_1",
      "text_Rank_102_2",
      "text_Rank_102_3",
      "text_Rank_102_4",
      "1",
      "1",
      "1",
      "1",
      "0"
    ],
    "packaged_name": "排行榜102",
    "packaged_desc": "排行榜配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "103",
    "table": "Rank",
    "columns": [
      "103",
      "text_Rank_103_1",
      "text_Rank_103_2",
      "text_Rank_103_3",
      "text_Rank_103_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜103",
    "packaged_desc": "排行榜配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "104",
    "table": "Rank",
    "columns": [
      "104",
      "text_Rank_104_1",
      "text_Rank_104_2",
      "text_Rank_104_3",
      "text_Rank_104_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜104",
    "packaged_desc": "排行榜配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "105",
    "table": "Rank",
    "columns": [
      "105",
      "text_Rank_105_1",
      "text_Rank_105_2",
      "text_Rank_105_3",
      "text_Rank_105_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜105",
    "packaged_desc": "排行榜配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "106",
    "table": "Rank",
    "columns": [
      "106",
      "text_Rank_106_1",
      "text_Rank_106_2",
      "text_Rank_106_3",
      "text_Rank_106_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜106",
    "packaged_desc": "排行榜配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "107",
    "table": "Rank",
    "columns": [
      "107",
      "text_Rank_107_1",
      "text_Rank_107_2",
      "text_Rank_107_3",
      "text_Rank_107_4",
      "1",
      "1",
      "1",
      "1",
      "0"
    ],
    "packaged_name": "排行榜107",
    "packaged_desc": "排行榜配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "108",
    "table": "Rank",
    "columns": [
      "108",
      "text_Rank_108_1",
      "text_Rank_108_2",
      "text_Rank_108_3",
      "text_Rank_108_4",
      "1",
      "1",
      "1",
      "2",
      "0"
    ],
    "packaged_name": "排行榜108",
    "packaged_desc": "排行榜配置行 8，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "109",
    "table": "Rank",
    "columns": [
      "109",
      "text_Rank_109_1",
      "",
      "text_Rank_109_3",
      "text_Rank_109_4",
      "1",
      "0",
      "0",
      "1",
      "1"
    ],
    "packaged_name": "排行榜109",
    "packaged_desc": "排行榜配置行 9，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "110",
    "table": "Rank",
    "columns": [
      "110",
      "text_Rank_110_1",
      "",
      "text_Rank_110_3",
      "text_Rank_110_4",
      "0",
      "0",
      "0",
      "1",
      "1"
    ],
    "packaged_name": "排行榜110",
    "packaged_desc": "排行榜配置行 10，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
