// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const RankReward: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "RankReward",
    "columns": [
      "1",
      "",
      "10002",
      "109",
      "[1,1]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励1",
    "packaged_desc": "榜单奖励配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "2",
    "table": "RankReward",
    "columns": [
      "2",
      "",
      "10002",
      "109",
      "[2,2]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励2",
    "packaged_desc": "榜单奖励配置行 2，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "3",
    "table": "RankReward",
    "columns": [
      "3",
      "",
      "10002",
      "109",
      "[3,3]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励3",
    "packaged_desc": "榜单奖励配置行 3，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "4",
    "table": "RankReward",
    "columns": [
      "4",
      "",
      "10002",
      "109",
      "[4,10]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励4",
    "packaged_desc": "榜单奖励配置行 4，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "5",
    "table": "RankReward",
    "columns": [
      "5",
      "",
      "10002",
      "109",
      "[11,20]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励5",
    "packaged_desc": "榜单奖励配置行 5，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "6",
    "table": "RankReward",
    "columns": [
      "6",
      "",
      "10002",
      "109",
      "[21,50]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励6",
    "packaged_desc": "榜单奖励配置行 6，保留结构、数值和资源键，显示文本使用本项目包装。"
  },
  {
    "id": "7",
    "table": "RankReward",
    "columns": [
      "7",
      "",
      "10002",
      "109",
      "[51,100]",
      "",
      "",
      "",
      ""
    ],
    "packaged_name": "榜单奖励7",
    "packaged_desc": "榜单奖励配置行 7，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
