// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingShopRow } from '../schema';

export const Shop: BidKingShopRow[] = [
  {
    "id": 1,
    "type": 1,
    "typeicon": "",
    "name": "shop_name_1",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 1",
    "packaged_desc": "类型 1，购买界面 0，固定商品。"
  },
  {
    "id": 2,
    "type": 2,
    "typeicon": "",
    "name": "shop_name_2",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 2",
    "packaged_desc": "类型 2，购买界面 0，固定商品。"
  },
  {
    "id": 4,
    "type": 4,
    "typeicon": "",
    "name": "shop_name_4",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 12,
    "autofresh": 1,
    "ticket": 0,
    "setting": 1,
    "random": 1,
    "packaged_name": "珍宝商铺 4",
    "packaged_desc": "类型 4，购买界面 0，自动刷新。"
  },
  {
    "id": 5,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_5",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 5",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  },
  {
    "id": 6,
    "type": 6,
    "typeicon": "",
    "name": "shop_name_6",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 6,
    "autofresh": 4,
    "ticket": 0,
    "setting": 1,
    "random": 1,
    "packaged_name": "珍宝商铺 6",
    "packaged_desc": "类型 6，购买界面 0，自动刷新。"
  },
  {
    "id": 7,
    "type": 7,
    "typeicon": "",
    "name": "shop_name_7",
    "shopicon": "",
    "tabname": "",
    "tap": 0,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 12,
    "autofresh": 1,
    "ticket": 0,
    "setting": 1,
    "random": 1,
    "packaged_name": "珍宝商铺 7",
    "packaged_desc": "类型 7，购买界面 0，自动刷新。"
  },
  {
    "id": 8,
    "type": 8,
    "typeicon": "",
    "name": "shop_name_8",
    "shopicon": "",
    "tabname": "",
    "tap": 0,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 12,
    "autofresh": 1,
    "ticket": 0,
    "setting": 1,
    "random": 1,
    "packaged_name": "珍宝商铺 8",
    "packaged_desc": "类型 8，购买界面 0，自动刷新。"
  },
  {
    "id": 9,
    "type": 9,
    "typeicon": "",
    "name": "shop_name_9",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 1,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 9",
    "packaged_desc": "类型 9，购买界面 0，自动刷新。"
  },
  {
    "id": 501,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_501",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 501",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  },
  {
    "id": 502,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_502",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 502",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  },
  {
    "id": 503,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_503",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 503",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  },
  {
    "id": 504,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_504",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 504",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  },
  {
    "id": 505,
    "type": 5,
    "typeicon": "",
    "name": "shop_name_505",
    "shopicon": "",
    "tabname": "",
    "tap": 1,
    "buyuitype": 0,
    "currencydisplay": [
      0
    ],
    "randcounts": 0,
    "autofresh": 0,
    "ticket": 0,
    "setting": 1,
    "random": 0,
    "packaged_name": "珍宝商铺 505",
    "packaged_desc": "类型 5，购买界面 0，固定商品。"
  }
];
