// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingSkillEffectRow } from '../schema';

export const SkillEffect: BidKingSkillEffectRow[] = [
  {
    "EffectId": 1000,
    "Category": 1,
    "Param": [
      0
    ],
    "effect_key": "category_1",
    "effect_desc": "显示轮廓尺寸"
  },
  {
    "EffectId": 2000,
    "Category": 2,
    "Param": [
      0
    ],
    "effect_key": "category_2",
    "effect_desc": "统计总占格"
  },
  {
    "EffectId": 3000,
    "Category": 3,
    "Param": [
      0
    ],
    "effect_key": "category_3",
    "effect_desc": "统计平均占格"
  },
  {
    "EffectId": 4000,
    "Category": 4,
    "Param": [
      0
    ],
    "effect_key": "category_4",
    "effect_desc": "统计命中数量"
  },
  {
    "EffectId": 5000,
    "Category": 5,
    "Param": [
      0
    ],
    "effect_key": "category_5",
    "effect_desc": "显示价格"
  },
  {
    "EffectId": 6000,
    "Category": 6,
    "Param": [
      0
    ],
    "effect_key": "category_6",
    "effect_desc": "显示藏品本体"
  },
  {
    "EffectId": 7000,
    "Category": 7,
    "Param": [
      0
    ],
    "effect_key": "category_7",
    "effect_desc": "显示品质"
  },
  {
    "EffectId": 8000,
    "Category": 8,
    "Param": [
      0
    ],
    "effect_key": "category_8",
    "effect_desc": "统计均价"
  },
  {
    "EffectId": 9000,
    "Category": 9,
    "Param": [
      0
    ],
    "effect_key": "category_9",
    "effect_desc": "统计格均价"
  },
  {
    "EffectId": 10000,
    "Category": 10,
    "Param": [
      0
    ],
    "effect_key": "category_10",
    "effect_desc": "统计总价"
  },
  {
    "EffectId": 11000,
    "Category": 11,
    "Param": [
      0
    ],
    "effect_key": "category_11",
    "effect_desc": "显示占格数"
  },
  {
    "EffectId": 12000,
    "Category": 12,
    "Param": [
      0
    ],
    "effect_key": "category_12",
    "effect_desc": "显示品质文本"
  },
  {
    "EffectId": 13000,
    "Category": 13,
    "Param": [
      0
    ],
    "effect_key": "category_13",
    "effect_desc": "显示品类文本"
  },
  {
    "EffectId": 14000,
    "Category": 14,
    "Param": [
      0
    ],
    "effect_key": "category_14",
    "effect_desc": "显示价格位数"
  },
  {
    "EffectId": 15000,
    "Category": 15,
    "Param": [
      6
    ],
    "effect_key": "category_15",
    "effect_desc": "技能效果类别15"
  },
  {
    "EffectId": 16001,
    "Category": 16,
    "Param": [
      1,
      1000
    ],
    "effect_key": "category_16",
    "effect_desc": "技能效果类别16"
  },
  {
    "EffectId": 16002,
    "Category": 16,
    "Param": [
      2,
      1
    ],
    "effect_key": "category_16",
    "effect_desc": "技能效果类别16"
  },
  {
    "EffectId": 17000,
    "Category": 17,
    "Param": [
      1,
      500
    ],
    "effect_key": "category_17",
    "effect_desc": "技能效果类别17"
  },
  {
    "EffectId": 17001,
    "Category": 17,
    "Param": [
      2,
      1000
    ],
    "effect_key": "category_17",
    "effect_desc": "技能效果类别17"
  },
  {
    "EffectId": 18001,
    "Category": 18,
    "Param": [
      1,
      500
    ],
    "effect_key": "category_18",
    "effect_desc": "技能效果类别18"
  },
  {
    "EffectId": 18002,
    "Category": 18,
    "Param": [
      2,
      1
    ],
    "effect_key": "category_18",
    "effect_desc": "技能效果类别18"
  },
  {
    "EffectId": 19000,
    "Category": 19,
    "Param": [
      800,
      500
    ],
    "effect_key": "category_19",
    "effect_desc": "技能效果类别19"
  },
  {
    "EffectId": 20001,
    "Category": 20,
    "Param": [
      1,
      1,
      500
    ],
    "effect_key": "category_20",
    "effect_desc": "技能效果类别20"
  },
  {
    "EffectId": 20002,
    "Category": 20,
    "Param": [
      2,
      1,
      100
    ],
    "effect_key": "category_20",
    "effect_desc": "技能效果类别20"
  },
  {
    "EffectId": 21001,
    "Category": 21,
    "Param": [
      1,
      1000
    ],
    "effect_key": "category_21",
    "effect_desc": "技能效果类别21"
  },
  {
    "EffectId": 21002,
    "Category": 21,
    "Param": [
      2,
      1
    ],
    "effect_key": "category_21",
    "effect_desc": "技能效果类别21"
  },
  {
    "EffectId": 22000,
    "Category": 22,
    "Param": [
      0
    ],
    "effect_key": "category_22",
    "effect_desc": "显示完整轮廓"
  },
  {
    "EffectId": 23001,
    "Category": 23,
    "Param": [
      1,
      1000
    ],
    "effect_key": "category_23",
    "effect_desc": "技能效果类别23"
  },
  {
    "EffectId": 23002,
    "Category": 23,
    "Param": [
      2,
      1
    ],
    "effect_key": "category_23",
    "effect_desc": "技能效果类别23"
  },
  {
    "EffectId": 24000,
    "Category": 24,
    "Param": [
      6
    ],
    "effect_key": "category_24",
    "effect_desc": "技能效果类别24"
  },
  {
    "EffectId": 25000,
    "Category": 25,
    "Param": [
      11,
      8001,
      1
    ],
    "effect_key": "category_25",
    "effect_desc": "技能效果类别25"
  },
  {
    "EffectId": 26001,
    "Category": 26,
    "Param": [
      1
    ],
    "effect_key": "category_26",
    "effect_desc": "技能效果类别26"
  },
  {
    "EffectId": 26002,
    "Category": 26,
    "Param": [
      2
    ],
    "effect_key": "category_26",
    "effect_desc": "技能效果类别26"
  },
  {
    "EffectId": 27000,
    "Category": 27,
    "Param": [
      1,
      11,
      0
    ],
    "effect_key": "category_27",
    "effect_desc": "技能效果类别27"
  },
  {
    "EffectId": 28001,
    "Category": 28,
    "Param": [
      1,
      1410101
    ],
    "effect_key": "category_28",
    "effect_desc": "技能效果类别28"
  },
  {
    "EffectId": 28002,
    "Category": 28,
    "Param": [
      2
    ],
    "effect_key": "category_28",
    "effect_desc": "技能效果类别28"
  }
];

export function skillEffectById(id: number): BidKingSkillEffectRow | undefined {
  return SkillEffect.find((effect) => effect.EffectId === id);
}
