// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingTicketRow } from '../schema';

export const Ticket: BidKingTicketRow[] = [
  {
    "id": 1,
    "name": "ticket_1",
    "type": 1,
    "recovertime": 0,
    "max": 20,
    "maxlimit": 0,
    "buyrefresh": 0,
    "buycounts": 0,
    "buyquantity": 0,
    "buycurrency": 0,
    "price": [
      0
    ],
    "reserveticket": 101,
    "reservetime": 0,
    "reservelimit": 0,
    "packaged_name": "竞拍票",
    "packaged_desc": "上限 20，恢复 0 秒，购买数量 0。"
  }
];
