// Generated by tools/generate-bidking-compat-data.mjs. Do not edit by hand.
import type { BidKingRawTableRow } from '../schema';

export const WareHouse: BidKingRawTableRow[] = [
  {
    "id": "1",
    "table": "WareHouse",
    "columns": [
      "1",
      "",
      "",
      "wh_allitem",
      "[2,3,4,5,6,7,8,16,19]"
    ],
    "packaged_name": "仓库分类1",
    "packaged_desc": "仓库分类配置行 1，保留结构、数值和资源键，显示文本使用本项目包装。"
  }
];
